### ISSUE TITLE
Appweb --log stdout:0

### ISSUE THREAD

**Issue by gioperez13** [embedthis/appweb#422]
Hi I'm running on
Version: 5.3.0
BuildType: Debug
CPU: x86
OS: linux
Host: user-VirtualBox
Configure: me configure

When I try to run appweb --log stdout:() it just shows my screen as if the commandline is in a infinite loop. Is it supposed to be like that?

**Comment by peterhale** [comment]
It is meant to block and serve requests.

**Comment by gioperez13** [comment]
So if run "appweb --log stdout:()" commandline would just be displaying something blank?

**Comment by embedthis** [comment]
Use
```
appweb --log stdout:1
```
