### ISSUE TITLE
Appweb can not upload file

### ISSUE THREAD

**Issue by chuangtim** [embedthis/appweb#423]
Following is my appweb.conf file below

    <Route /up>
        AddInputFilter uploadFilter
        UploadDir /tmp
        UploadAutoDelete on
        LimitUpload 200MB
    </Route>

Following is my front-end file below,it is simple

    <div class="col-xs-offset-2 col-xs-8 col-md-offset-5 col-md-4">
        <form method="post" action="/up" enctype="multipart/form-data">
          <input type="file" name="upfile" id="packet_file" multiple/>
          <input type="submit" value="upload"/>
        </form>
    </div>

please tell why it can not upload? thanks.

**Comment by embedthis** [comment]
Looks like you have a route called /up, but what is the actual document receiving the uploaded file? 
You need something like action="/up/myform.esp" where the myform.esp receives the request. 

See samples under test/web/upload.
