### ISSUE TITLE
Cookie / Session Issue

### ISSUE THREAD

**Issue by RobertAn** [embedthis/appweb#424]
Hi,

I'm going to raise an issue regarding session.
I might be wrong though but please hear me out first.

I copied the login form sample provided in esp and modified some configuration based on what I need. Then I used appwed to host the app.

For the pages in web document, where the user should login, all pages are in .html. 

And then I tested it, I logged in for the first time, checked if I could access html pages in the web document without logging in first And I was redirected to login page which is correct. Not I typed in my credentials and was successfully routed to the webpage that I want to see. Now here's the problem, I logged out by clicking the logout button. And when I checked if I could access the web pages from web document (I shouldn't  be able to access it, right?), I did. I was able to access the pages in the web document. 

I used all of the api's below at the same time. But it didn't work. I could still access the web pages.
-espDestroySession(getConn());
-espRemoveCookie(getConn(),"ProjectName");
-httpLogout(getConn());

Could you tell me if this a bug from your side or I did something wrong?
Thanks

**Comment by embedthis** [comment]
I think those samples have migrated to the esp repository. I've tested them there, and they seem to work fine.

To pursue, can you replicate using the dev branch of the esp repository and get the sample to fail?

**Comment by RobertAn** [comment]
okay. I'll do it and i'll  inform you of the result. thank you. 

I forgot to mention the appweb version..
I'm using appweb 5.3 and it is running on ubuntu.
