### ISSUE TITLE
Stand alone websocket controller changes name when port number is changed in the production environement

### ISSUE THREAD

**Issue by vivekjain007** [embedthis/appweb#426]
.       When ever I change the listen port of the appweb server the name of generated controller dll changes as it has some dependency on the hostname:port for calculating the hash value. Because of this I cannot generate the controller and switch off EspUpdate to stop the controller generation in the production environment. In production environment it is very likely that the port number would be changed and if that happens then appweb is not able to find the controller with the new name.
 
Example
 
Port number – 5000 leads to generation of controller_{AAA}.dll. This Dll is deployed in the production and the appweb.conf is changed to EspUpdate off and Listen port to 6000
Port number – 6000 leads to internal controller name generation as controller_{BBB}.dll. Appweb does not find this dll any longer.

**Comment by peterhale** [comment]
I don't think this is right.

The hash portion of the controller entry point is computed from this code:
```
    canonical = mprGetPortablePath(mprGetRelPath(source, route->documents));
    appName = eroute->appName ? eroute->appName : route->host->name;
    app->cacheName = mprGetMD5WithPrefix(sfmt("%s:%s", appName, canonical), -1, prefix);
```
This computes a relative path to the source from the route documents directory prefixed by the application name. The port is not used.

Make sure you install the controller in the same relative location on the target as you used on the host.

**Comment by vivekjain007** [comment]
Hi Peter,

Thanks for the timely response. See my reponse below in line in Green
Hope the further explanation is helpful to you.

Best Regards,

Vivek Jain
(RBEI/EST)
Tel +91 80 67837465

**Comment by peterhale** [comment]
Good to know, you can define a route name and that will be used. It is only using the port number because you have not defined a Name for the route.

**Comment by vivekjain007** [comment]
Hi Peter,

Thanks again for the promt reply.  So I should add RouteName directive in my route configuration.
Once again I really appreciate the support provided by you.

Best Regards,

Vivek Jain
(RBEI/EST)
Tel +91 80 67837465

**Comment by vivekjain007** [comment]
Hi Peter,

I tried by specifying the Name of the Route as shown below

<Route ^/ws/{controller}/{action}$>
                Name icp
                Prefix /ws
                ResetPipeline
                AddFilter webSocketFilter
                AddHandler espHandler
                Source apps/wsicp/wsicp.c
    Target run $1-$2
                RequestTimeout 60mins
                InactivityTimeout 60mins
    WebSocketsPing 60mins
    #WebSocketsProtocol chat
</Route>

With the above configuration the route->name is shown as icp when I debug in loadEspModule function but eroute->appName is still NULL.
Route->name is never used in calculating the controller cahched name in the below lines.


canonical = mprGetPortablePath(mprGetRelPath(source, route->documents));

appName = eroute->appName ? eroute->appName : route->host->name;

app->cacheName = mprGetMD5WithPrefix(sfmt("%s:%s", appName, canonical), -1, prefix);


Best Regards,

Vivek Jain
(RBEI/EST)
Tel +91 80 67837465

**Comment by vivekjain007** [comment]
Hi Peter,

Any updates on possible solution for this issue. The Route name is not considered for generating controller name hash in case of stand alone controllers.

Warm Regards
Vivek Jain

**Comment by embedthis** [comment]
Appweb 5.4.0 will solve this by ensuring all routes have an ESP default application name.

**Comment by vivekjain007** [comment]
Thanks for resolving the issue. I appreciate the support.


Best Regards,

Vivek Jain
(RBEI/EST)
Tel +91 80 67837465
