### ISSUE TITLE
websocket closed by server after exchanging data continuously for some time

### ISSUE THREAD

**Issue by vivekjain007** [embedthis/appweb#427]
filterPacket function in httpLib.c closes wesocket connection due to following condition with respect conn->limits->receiveBodySize in this function.
```
if (size >= conn->limits->receiveBodySize )
    {
        httpLimitError( conn, HTTP_CLOSE | HTTP_CODE_REQUEST_TOO_LARGE,
                        "Receive body of %'lld bytes (sofar) is too big. Limit %'lld", size, conn->limits->receiveBodySize );
    }
```
This seems to be incorrect since websocket is stream and should not have limits on amount of data exchanged between client and server once the connection has been upgraded.

**Comment by vivekjain007** [comment]
See the attahced log generated by appweb:-

appweb: 3: WebSocket: 2216: send "text" (1) frame, last 1, length 98
appweb: 7: Service queue netConnector-tx

>>>>>>>>>> Transmit prefix packet 4433, len 2 (conn 1) >>>>>>>>>> (binary)
81 62 
<<<<<<<<<< End Transmit packet, conn 1

>>>>>>>>>> Transmit content packet 4434, len 98 (conn 1) >>>>>>>>>>
{"jsonrpc":"2.0", "result":{"status":1,"objectid":1028,"objectpropertyid":1,"value":0}, "id":2217}<<<<<<<<<< End Transmit packet, conn 1
appweb: 6: netConnector: wrote 100, ask 100, qflags 10
appweb: 7: dispatchEvents for nonblock
appweb: 7: Call event httpTimer
appweb: 7: httpTimer: 1 active connections
appweb: 7: dispatchEvents for IO
appweb: 7: Call event IOEvent
appweb: 6: httpIOEvent for fd 528, mask 2
appweb: 6: http: readEvent read socket 237 bytes
appweb: 6: httpProtocol: IO, state 5, error 0
appweb: 7: pauseThreads: wait for threads to yield, timeout 100
appweb: 2: Error: Receive body of 524,356 bytes (sofar) is too big. Limit 524,288
appweb: 7: pauseThreads: waiting for threads to yield
appweb: 6: Event: "error" in state "content"
appweb: 0: wsicp.c: error event
appweb: 6: Disconnect socket 528

**Comment by embedthis** [comment]
Can you just set LimitRequestBody to zero. This sets it to the maximum integer size. Or do you really need infinite without any limit?

Typically apps must handle TCP/IP  closures as they cannot be fully prevented. Routers and TCP/IP may close connections due to congestion at any time. So your app must handle socket closure anyway.

**Comment by vivekjain007** [comment]
Hi ,

Thanks for looking into the issue.
I really need infinite without any limit. In my case there would be clients connected to the server 24x7 exchanging system controlling and monitoring messages with the server over web sockets. The disconnection should really be only due to network issues and not becuae of rx/tx data limits on the web socket connection. Closing websocket due to rx/tx limits will adversely affect my system properties.


Best Regards,

Vivek Jain
(RBEI/EST)
Tel +91 80 67837465

**Comment by embedthis** [comment]
The receiveBodySize is 64 bits. So you have a really big number if you set it to the max 64 bit integer.

In version 5, you have the alias "infinite" which means max64 integer.

We could in the future actually turn this off, but in all likelihood, you will get a network issue before this number expires. And your application must be written to handle this in any case.

**Comment by embedthis** [comment]
Last word.

We have disabled testing receiveBodySize for web sockets. 

Testing now in appweb 4 and 5

**Comment by vivekjain007** [comment]
Thanks for providing the solution. I appreciate the effort.


Best Regards,

Vivek Jain
(RBEI/EST)
Tel +91 80 67837465

**Comment by embedthis** [comment]
Sorry, but we are reverting this change.

It is a valid use case to sandbox a web socket connection for security. Users need to be able to specify that a web socket will at most receive or transfer a certain amount of data. Similar to applying timeout on a web socket connection.

So the default will not be to disable this. However, we will support setting the receiveBodyLimit and transmissionBodyLimit to "infinity" which WILL disable the limit. I think this gives you the feature you wanted, but also preserves the ability to sandbox a web socket connection.

**Comment by vivekjain007** [comment]
Thanks for the update. OK for me as long as there is some way for me to configure this behaviour for websocket. In which build I can expect this fix to be available so that I can go ahead with my testing here?


Best Regards,

Vivek Jain
(RBEI/EST)
Tel +91 80 67837465

**Comment by embedthis** [comment]
Here are some details.

You can set the LimitRequestBody and LimitResponseBody to "unlimited" or "infinity" to disable sandbox limits. You should do this only in a web socket route so that you preserve limits for other requests. 

For timeouts, you can do the same. We don't explicitly bypass limits for timeouts because the limits are 64 bit numbers which equates to a timeout period of 30 million years. i.e. don't need to explicitly disable timeouts.

The default limits for an ESP web socket route are unlimited request/response size, 5 minutes inactivity timeout and unlimited request timeout. The 5 minute timeout is so completely idle web socket connections are cleaned up. If you need to extend this, you can do this:

```
    "http": {
        "auth": {
            "store": "app"
        },
        "database": "default",
        "routes": [
            "esp-restful",
            {
                pattern: '^/{controller}/stream',
                limits: {
                    requestBody: 'unlimited'
                }
            }
        ]
    },
```

**Comment by vivekjain007** [comment]
Thanks for this update. In which build of appweb I can get this?


Best Regards,

Vivek Jain
(RBEI/EST)
Tel +91 80 67837465

**Comment by embedthis** [comment]
Couple of suggestions. 

* Suggest you not reply to github issues using your email with signature. It gets posted for all -- probably not what you want. It also clutters the readability of the issue thread
* Always edit your issue comments to format code properly. Again more readable.

The patch is just in the dev branch at the moment. It should arrive in the next release, but that is a flexible date at the moment.

**Comment by vivekjain007** [comment]
Suggestions taken. i was not aware of this. 
Is it OK if I take the dev branch from github for intermediate testing ?
