### ISSUE TITLE
have a questions about openssl when i cross compile appweb 5.3

### ISSUE THREAD

**Issue by auto-linux** [embedthis/appweb#429]
I cross compile appweb 5.3 on ubuntu 14.04 for arm platform .
the command :
```
make AR=/opt/arm-2014.05/bin/arm-none-linux-gnueabi-ar CC=/opt/arm-2014.05/bin/arm-none-linux-gnueabi-gcc LD=/opt/arm-2014.05/bin/arm-none-linux-gnueabi-ld  ARCH=arm PROFILE=release -f projects/appweb-linux-default.mk
```
then break a errror:
```
      [Info] Use make SHOW=1 to trace executed commands.
   [Compile] build/linux-arm-release/obj/httpLib.o
      [Link] build/linux-arm-release/bin/libhttp.so
      [Copy] build/linux-arm-release/inc/appweb.h
      [Copy] build/linux-arm-release/inc/customize.h
   [Compile] build/linux-arm-release/obj/config.o
   [Compile] build/linux-arm-release/obj/convenience.o
      [Link] build/linux-arm-release/bin/libappweb.so
      [Copy] build/linux-arm-release/inc/esp.h
   [Compile] build/linux-arm-release/obj/slink.o
      [Link] build/linux-arm-release/bin/libslink.so
   [Compile] build/linux-arm-release/obj/appweb.o
      [Link] build/linux-arm-release/bin/appweb
   [Compile] build/linux-arm-release/obj/authpass.o
      [Link] build/linux-arm-release/bin/authpass
      [Copy] build/linux-arm-release/bin/esp.conf
   [Compile] build/linux-arm-release/obj/espLib.o
      [Link] build/linux-arm-release/bin/libmod_esp.so
   [Compile] build/linux-arm-release/obj/esp.o
      [Link] build/linux-arm-release/bin/esp
      [Copy] build/linux-arm-release/bin/ca.crt
   [Compile] build/linux-arm-release/obj/http.o
      [Link] build/linux-arm-release/bin/http
   [Compile] build/linux-arm-release/obj/cgiHandler.o
      [Link] build/linux-arm-release/bin/libmod_cgi.so
   [Compile] build/linux-arm-release/obj/mprSsl.o
      [Link] build/linux-arm-release/bin/libmprssl.so
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: warning: library search path "/usr/lib" is unsafe for cross-compilation
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: warning: library search path "/usr/lib" is unsafe for cross-compilation
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: cannot find -lssl
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: cannot find -lcrypto
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: cannot find -lssl
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
make: *** [build/linux-arm-release/bin/libmprssl.so]
```

appweb 5.2.0 does not have this error. what can i do it?

**Comment by embedthis** [comment]
Use 

```
make SHOW=1
```
to see the actual commands. Then run manually to debug. Seems like the path to openssl isn't set right.

**Comment by auto-linux** [comment]
my openssl version is OpenSSL 1.0.2 22 Jan 2015. And i go to the path where is /usr/local/ssl, the files are shown:
drwxrwxrwx  2 book root  4096  2月 17 16:07 bin/
drwxrwxrwx  2 book root  4096  2月 17 16:07 certs/
drwxrwxrwx  3 book root  4096  2月 17 16:07 include/
drwxrwxrwx  4 book root  4096  2月 17 16:07 lib/
drwxrwxrwx  6 book root  4096  2月 17 16:07 man/
drwxrwxrwx  2 book root  4096  2月 17 16:07 misc/
-rwxrwxrwx  1 book root 10835  2月 17 16:07 openssl.cnf*
drwxrwxrwx  2 book root  4096  2月 17 16:07 private/
I add the command to set the path to openssl :ME_COM_OPENSSL_PATH=/usr/local/ssl Then cross compile appweb 5.3 with arm.An new error occurred.
   [Compile] build/linux-arm-release/obj/mprSsl.o
/opt/arm-2014.05/bin/arm-none-linux-gnueabi-gcc -c -o build/linux-arm-release/obj/mprSsl.o -fPIC -w -g -D_REENTRANT -DPIC -DME_COM_OPENSSL_PATH=/usr/local/ssl -DME_COM_CGI=1 -DME_COM_COMPILER=1 -DME_COM_DIR=1 -DME_COM_EJS=0 -DME_COM_ESP=1 -DME_COM_EST=0 -DME_COM_HTTP=1 -DME_COM_LIB=1 -DME_COM_MDB=1 -DME_COM_MPR=1 -DME_COM_OPENSSL=1 -DME_COM_OSDEP=1 -DME_COM_PCRE=1 -DME_COM_PHP=0 -DME_COM_SQLITE=0 -DME_COM_SSL=1 -DME_COM_VXWORKS=0 -DME_COM_WINSDK=1 -DME_COM_ZLIB=0  -DME_DEBUG -DME_COM_OPENSSL_PATH="/usr/local/ssl" "-Ibuild/linux-arm-release/inc" "-I/usr/local/ssl/include" src/paks/mpr/mprSsl.c
      [Link] build/linux-arm-release/bin/libmprssl.so
/opt/arm-2014.05/bin/arm-none-linux-gnueabi-gcc -shared -o build/linux-arm-release/bin/libmprssl.so '-rdynamic' '-Wl,--enable-new-dtags' '-Wl,-rpath,$ORIGIN/' -g -Lbuild/linux-arm-release/bin   "build/linux-arm-release/obj/mprSsl.o" -L"/usr/local/ssl/lib" -L"/usr/local/ssl" -L"/usr/local/ssl/lib" -L"/usr/local/ssl" -lmpr -lssl -lcrypto -lmpr -lssl -lcrypto -lrt -ldl -lpthread -lm 
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libssl.so when searching for -lssl
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libssl.a when searching for -lssl
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libssl.so when searching for -lssl
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libssl.a when searching for -lssl
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: cannot find -lssl
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libcrypto.so when searching for -lcrypto
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libcrypto.a when searching for -lcrypto
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libcrypto.so when searching for -lcrypto
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libcrypto.a when searching for -lcrypto
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: cannot find -lcrypto
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libssl.so when searching for -lssl
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libssl.a when searching for -lssl
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libssl.so when searching for -lssl
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libssl.a when searching for -lssl
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: cannot find -lssl
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libcrypto.so when searching for -lcrypto
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libcrypto.a when searching for -lcrypto
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libcrypto.so when searching for -lcrypto
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: skipping incompatible /usr/local/ssl/lib/libcrypto.a when searching for -lcrypto
/opt/arm-2014.05/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
make: *** [build/linux-arm-release/bin/libmprssl.so] 错误 1
It seem that cannot find these files.But the path where /usr/local/ssl/lib  has these files
drwxrwxrwx 2 book root    4096  2月 17 16:07 engines/
-rwxrwxrwx 1 book root 3423258  2月 17 16:07 libcrypto.a*
lrwxrwxrwx 1 book root      18  2月 17 16:07 libcrypto.so -> libcrypto.so.1.0.0*
-rwxrwxrwx 1 book root 2200521  2月 17 16:07 libcrypto.so.1.0.0*
-rwxrwxrwx 1 book root  652218  2月 17 16:07 libssl.a*
lrwxrwxrwx 1 book root      15  2月 17 16:07 libssl.so -> libssl.so.1.0.0*
-rwxrwxrwx 1 book root  498779  2月 17 16:07 libssl.so.1.0.0*
drwxrwxrwx 2 book root    4096  2月 17 16:07 pkgconfig/

**Comment by embedthis** [comment]
You need to supply a cross openssl for arm. You are referencing /usr/local/ssl which is a native ssl.

**Comment by auto-linux** [comment]
It is ok.Thank you very much!
