### ISSUE TITLE
Memory and handle counts creeping when using web sockets after embedding appweb in windows application

### ISSUE THREAD

**Issue by vivekjain007** [embedthis/appweb#430]
I have embedded appweb in my windows applicaiton. While communicating over websockets in this scenario I observe continuously creeping up of memory and handle count in long running process.

**Comment by embedthis** [comment]
More details please.

**Comment by vivekjain007** [comment]
Hi,


1)      Appweb version – 4.6.3

2)      Appweb integrated in my executable using native API’s

3)      Continuous message exchanged over web socket connections by 10 clients – Each message arround 250 bytes. Message frequency 1 second from each client so on average 1 message every 100 ms

4)      Server OS – Windows 7 64 bit professional edition

I have even got the logs that I can share in case required but the log file size is very huge approx ( 1 GB).

Let me know if you need more information on this.


Best Regards,

Vivek Jain
(RBEI/EST)
Tel +91 80 67837465

**Comment by peterhale** [comment]
How much does the memory grow from ... to?
Same for handles. WebSockets don't use any more handles than the core server, so handle count should not be going up. 

Is your application doing anything during these requests?  Can you test without your application logic?

Can you re-run without the log trace.
