### ISSUE TITLE
Cannot run CGI Process

### ISSUE THREAD

**Issue by RobertAn** [embedthis/appweb#431]
Im using Appweb 5.3 and it is running in ubuntu.

At first, I was using the ScriptAlias directive to run my CGI scripts. And it is working perfectly using the directive below

ScriptAlias /newPath/ "./cgi-bin 

But when I try to run using this

<Route /newPath/>
    Documents ./cgi-bin
    SetHandler cgiHandler
    Target run
</Route>

It always return this error message 

Cannot run CGI process: /flash/MyApp/cgi-bin, URI /newPath/myScript

I've referred to this document http://appwebserver.org/products/appweb/doc-4.3/guide/appweb/users/cgi.html

Did I miss anything?

**Comment by embedthis** [comment]
Try adding "$1" to the target run.

```
Documents ./cgi-bin
SetHandler cgiHandler
Target run $1
```

**Comment by RobertAn** [comment]
That didn't work. :(

**Comment by RobertAn** [comment]
Could you confirm if this is a bug on your side? Thank you.

**Comment by embedthis** [comment]
No bug, just a little more detail required on the route:

```
<Route ^/mycgi/(.*)$>
    SetHandler cgiHandler
    Documents cgi-bin
    Target run $1
</Route>
```

The route pattern must capture the rest of the URL which is supplied to the target via $1

**Comment by embedthis** [comment]
Documentation updated in 5.4.0

**Comment by RobertAn** [comment]
Great thanks!
