### ISSUE TITLE
Routing issues

### ISSUE THREAD

**Issue by RobertAn** [embedthis/appweb#432]
Im using appweb 5.3 and running in Ubuntu.

My appweb.conf has a route that looks like this:

   &lt;Route ^/public/&gt;
	   Prefix /public
	   Documents public
	   AuthType none
   &lt;/Route&gt;

   &lt;Route ^/&gt;
	   AuthStore System
	   Documents web
	   AuthType form AlliedwarePlus https:///public/login.html /user/login /user/logout https:///myPage.html https:///public/login.html
	
      &lt;Route ^/myCgi/(.*)$&gt;
		   SetHandler cgiHandler
		   Documents ./cgi-bin
	   	   Target run $1
      &lt;/Route&gt;
   &lt;/Route&gt;
I have a page that is called myPage.html and located in the web directory. I want that directory to be secured so I added the AuthType directive. I also have another directory called myCgi which contains my cgi scripts, I want to protect these cgi scripts as well. The problem is, once I logged in, I wasn't redirected to the landing page which is "myPage.html" .

why is that so?

**Comment by embedthis** [comment]
Post the HTTP headers from the appweb trace log.

Please review

https://github.com/embedthis/appweb/issues/419
