### ISSUE TITLE
Appweb Sessions Issue

### ISSUE THREAD

**Issue by smitig** [embedthis/appweb#434]
Hi,
 
      I am using Appweb version 4.5.4.

      In our application, everytime user logs in httpCreateSession is called to create a session and on every log out httpDestroySession is called.

      We are running a test, in which from six simultaneous sessions we are doing login and logout continuously for 12 hours.

      On running this test, sometimes after 6-8 hours we are getting the error "Too many sessions 100/100" on trying to do httpCreateSession.

      http->activeSessions is reaching 100 which is the max value allowed. Its not clear how and when http->activeSessions is being incremented and decremented.

      It will be really helpful if someone can explain what http->activeSessions represents and how it will be incremented and decremented.

      Thankyou.

**Comment by peterhale** [comment]
Http.activeSessions is not the real value. The value comes from mprGetCacheStats. The last value read is stored in activeSessions, but it really should not be used. We'll remove this in a future version.

The sessions are pruned as they expire. It is possible, that in a long test, you create a lot of sessions and you just happen to go over 100. It will go up and down as sessions are created and expire. 

You can use mprGetCacheStats to get the current number of active sessions. If you reduce the session inactivity timeout via SessionTimeout, you can reduce the number of outstanding sessions by making inactive sessions expire sooner.
