### ISSUE TITLE
Unable to configure 5.4.0 with makeme

### ISSUE THREAD

**Issue by vivekjain007** [embedthis/appweb#446]
Hi,

When I try to configure the newly released 5.4.0 source using makeme I get following error:-

D:\Work\ubuntu_share\iris2_production_1_3\trunk\Src\appweb-5.4.0>me --platform windows-x64-debug -configure .
      [Warn] Cannot find plugin: "installs" ... continuing
      [Warn] BB Cannot find plugin: "esp" ... continuing
me: ERROR: Cannot find blended module: esp

This use to work without any issues in 5.3.0 release. I am using makeme version 0.8.5 on windows 7 64 bit machine. I have Visual Studio 2012 installed. Also when I load the visual studio solution I no longer see the libmod_esp project as part of the solution.

**Comment by embedthis** [comment]
Release notes say MakeMe 0.8.6 required.
