### ISSUE TITLE
Unable to invoke the action from ESP controller

### ISSUE THREAD

**Issue by abhay4891** [embedthis/appweb#447]
**Environment**

Appweb version: 5.3.0, built from source
O/S: VxWorks 6.3 & also tried on Linux Ubuntu 12.10
Hardware: Embedded system running VxWorks and Linux Ubuntu VMWARE
Customization: None.

Build from source using appweb-vxworks-static.mk file
Code compilation was static

**Problem Description:**

When issuing the request:
http://localhost:80//greetings/hello

The following data is returned
**Access Error: 404 -- Not Found**

**Missing action for "greetings-hello"**

Though it should have displayed simply - **"Hello World"**

**Appweb.conf content dump is:**
ErrorLog stdout level=4 append

Listen localhost:80

LoadModule espHandler libmod_esp
AddHandler espHandler esp
EspUpdate on
EspKeepSource on
ShowErrors on

    <Route ^/greetings/{Action}$>
    Name greetings
    AddHandler espHandler
    EspDir controllers ./controllers
    EspDir cache ./cache
    Source greetings.c
    Target run greetings-$1
    </Route>

Include esp.conf

**greetings.c content dump is -**

#include "esp.h"
static void hello() {
    render("Hello World\n");
}
ESP_EXPORT int esp_controller_greetings(HttpRoute *route) {
    espDefineAction(route, "greetings-hello", hello);
    return 0;
}

**esp.conf contents are -**

    #

    #
    #   Default static compilation command
    #
    EspCompile ${CC} -c ${DEBUG} -Wall -Wno-unused-result -I. -I${APPINC} -I${INC} -L${LIBPATH} -Wl,--enable-new-dtags -Wl,-rpath,$ORIGIN/ ${CFLAGS} ${LIBS} ${LDFLAGS} -o ${OBJ} ${SRC}
    EspLink ${AR} -cr ${MOD}${ARLIB} ${OBJ} 

    <if macosx>
        EspCompile ${CC} -c ${DEBUG} -Wall -DPIC -fPIC -arch ${GCC_ARCH} -I. -I${APPINC} -I${INC} -c ${SRC} -o ${OBJ}
        EspLink ${AR} -cr ${MOD}${ARLIB} ${OBJ} 
    </if>

    <if windows>
        EspEnv VisualStudio
        EspCompile "${CC}" -LD ${DEBUG} -D_REENTRANT -D_MT -nologo -GR- -W3 -MDd -I. -I${APPINC} -I"${INC}" -Fd"${MOD}.pdb" -Fe"${MOD}${SHOBJ}" "${SRC}"
        EspLink ${AR} -nologo cr ${MOD}${ARLIB} ${OBJ} 
    </if>

    <if vxworks>
        #
        #   The esp-vxworks.conf file will be generated by 'configure'
        #   Alternately, comment out this include, and set WIND_BASE, WIND_HOME, WIND_PLATFORM, WIND_HOST_TYPE, WIND_GNU_PATH 
        #   and WIND_CCNAME in the environment.
        include ${BIN_DIR}/esp-vxworks.conf
        EspCompile "${WIND_GNU_PATH}/${WIND_HOST_TYPE}/bin/${WIND_CCNAME}" -c ${DEBUG} -DVXWORKS -DRW_MULTI_THREAD -D_REENTRANT -D_GNU_TOOL -DCPU=${VXCPU} -Wall -fno-builtin -fno-defer-pop -fvolatile "-I." "-I${APPINC}" "-I${WIND_BASE}/target/h" "-I${WIND_BASE}/target/h/wrn/coreip" -I${INC} -o ${MOD}${SHOBJ} ${SRC} 
        EspLink "${WIND_GNU_PATH}/${WIND_HOST_TYPE}/bin/${WIND_ARNAME}" ${DEBUG} -cr ${MOD}${ARLIB} ${OBJ} 
    </if>

**Comment by embedthis** [comment]
When building static, you must manually invoke the esp_controller_greetings function from your main program. When building dynamic, it is automatically called when loading the module.
