### ISSUE TITLE
Discrepency with Action/MimeTypes between the documentation and actual settings

### ISSUE THREAD

**Issue by jslagel-isb** [embedthis/appweb#449]
### Environment

Appweb version: 5.3.0 using pre-built binary
O/S: Windows 7
Hardware: PC

### Problem Description

Both the website documentation and the sample configuration files show the use of the  Action directive for changing the program used to execute a script by specifying its MimeType.  However the MimeType used in the examples doesn't match the MimeTypes found in the mime.types file packaged with the pre-built binary.  For example, the types in the examples are:

    Action application/x-appweb-perl /usr/bin/perl
    Action application/x-appweb-python /usr/bin/python

However in mime.types they are actually defined as:

    application/x-perl pl
    application/x-python py

This can lead to some confusion when the directive fails to assign the correct program.

### Files affected:

    appweb.conf
    sample.conf
    https://embedthis.com/appweb/doc/users/cgi.html
    http://www.appwebserver.org/products/appweb/doc-4.3/guide/appweb/users/cgi.html

**Comment by embedthis** [comment]
Thanks. Solution will be to remove the -appweb- portion and match the mime.types.
Will fix in 4.7.1 and 5.4.1
