### ISSUE TITLE
How to remove source file from controllers/ but don't effect it's working

### ISSUE THREAD

**Issue by Waching** [embedthis/appweb#452]
I've ported appweb-4.3.5 to my target arm board and it runs good with sample of "Hello World" controller. I cross-compiled the controllers/controller.c to generate controller_001d4eec0208422e2460bcf0b34e2a2e.so in cache/. When controller.c is in controllers/ and controller_001d4eec0208422e2460bcf0b34e2a2e.so is in cache/ it works good. But when i remove controller.c from controllers/ it cannot work again, the browser reports error: 
```
Access Error: 500 -- Internal Server Error
Cannot find controller to serve request
```
I don't know why, In my opinion, i have compiled controller.c to controller_001d4eec0208422e2460bcf0b34e2a2e.so and it should be enough to run without controller.c.

**Comment by Waching** [comment]
My question is how to let it work good without controller.c in controllers/.
My web folder include:
     +web
       -app.conf
       -appweb.conf
      +cache
         -controller_001d4eec0208422e2460bcf0b34e2a2e.so
      +controllers
         -controller.c
appweb.conf:
======================================
ErrorLog "stdout" level=2
Listen 80

AddOutputFilter chunkFilter
AddHandler fileHandler html gif jpeg jpg png pdf ico css js
LoadModule espHandler libmod_esp
AddHandler espHandler esp

<Route ^/test/{action}$>
    AddHandler espHandler
    Source     controllers/controller.c
    Target     run test-$1
</Route>

EspUpdate off
======================================
Thanks.

**Comment by embedthis** [comment]
This is confirmed and is a bug.

When running in "debug" mode, ESP watches the controller.c for changes and will recompile if the file changes. However, it should still serve the compiled module.

**Comment by Waching** [comment]
Thank you for the quick answer! So i have two solutions to resolve this problem:
1. Update appweb to a newer version or make a patch from server.
2. Can i run appweb in "release" mode or other non-debug mode to avoid this issue?
By the way, how to run appweb in "release" mode?

**Comment by embedthis** [comment]
Regarding (1) patch is not yet available. Will advise here when ready. Expect 1-2 weeks. This will be applied to 5.4. But you may be able to use the settings below.

In Appweb 5.4, there are two controlling parameters in the esp.json file

* http.update -- this defines whether ESP will try to compile modified controllers. If false, it will not recompile and reload modified controllers or ESP pages.
* esp.combine -- If true, ESP expects the app to be compiled in "combine" mode. i.e. all into one single application file.

In Appweb 4, you can use EspUpdate directive to control update.

    EspUpdate on
    EspUpdate off

and 

    EspApp name=.. ....... combined=true

**Comment by embedthis** [comment]
FYI: could you just leave an empty stub file. If update is false, it won't be recompiled anyway.

**Comment by Waching** [comment]
Thank you very much!
I've just tried empty controller.c and it does work fine. 
I need more time to try "combined=true" because i haven't used the setting of "EspApp...combined=true" before. 
But now i have another urgent issue to resolve, and if i cannot resolve it then i'll ask you for help again.
