### ISSUE TITLE
How to recognize upper case path and name when building esp controllers?

### ISSUE THREAD

**Issue by Waching** [embedthis/appweb#464]
# Environment
Appweb version: 4.3.5, built from source
O/S: Linux Ubuntu: 12.04.4 LTS(x86_64)
Hardware: PC

# Problem Description:
When I used esp application to compile controllers, I found it didn't support upper case path and name.
My compile command is like this: 
`<esp --platform /proj/MyWorkSpace/appweb/4.3.5/linux-arm-default --config appweb.conf compile>`
<p>As the path including upper character, the command failed.</p>
I cannot modify the path name since it was allocated by administrator.
Would you please give me any advice to fix or avoid this problem?

# Just a reminder
The name of **MyWorkSpace** is an phony example but it is enough to explain this issue because we can encounter upper case in our build environment anywhere.

**Comment by embedthis** [comment]
See: https://github.com/embedthis/appweb/issues/419

**Comment by embedthis** [comment]
That works fine here with upper case in platform paths.

What is the error message?
More details as we cannot reproduce.

**Comment by Waching** [comment]
The error is : 
`esp: Error: Cannot find platform /proj/myworkspace/appweb/4.3.5/linux-arm-default`

It seems like esp transferred the **MyWorkSpace** to **myworkspace** and then cannot find it.

**Comment by embedthis** [comment]
Quick patch:

```
diff --git a/src/esp/esp.c b/src/esp/esp.c
index 4c620b4..a38b802 100644
--- a/src/esp/esp.c
+++ b/src/esp/esp.c
@@ -290,7 +290,7 @@ PUBLIC int main(int argc, char **argv)
             if (argind >= argc) {
                 usageError();
             } else {
-                app->platform = slower(argv[++argind]);
+                app->platform = sclone(argv[++argind]);
             }

         } else if (smatch(argp, "quiet") || smatch(argp, "q")) {
```

**Comment by Waching** [comment]
It's OK, thank you!
