### ISSUE TITLE
Appweb cannot work when receive and send data frequently

### ISSUE THREAD

**Issue by Waching** [embedthis/appweb#466]
# Environment:
Appweb version: 4.3.4
O/S: Linux 
CPU: arm
# Problem Description:
We write a test program to send requirement(GET/POST) to appweb in cycles. But when running about some cycles, the appweb cannot work, and the client cannot connect to server again except for killing and restarting appweb process. 

Appweb didn't print any useful error message or log. But system print below log once in a while:
`ERROR!!! MlmeEnqueueForRecv(): un-recongnized mgmt->subtype=15`
I have no idea about above error, is it the root cause?
# Appweb's log:
`appweb: 2: Configuration for Embedthis Appweb`
`appweb: 2: ---------------------------------------------`
`appweb: 2: Version:            4.3.4-0`
`appweb: 2: BuildType:          Debug`
`appweb: 2: CPU:                arm`
`appweb: 2: OS:                 linux`
`appweb: 2: Host:               xxxx`
`appweb: 2: Directory:          /server/appweb/web`
`appweb: 2: Configure:          bit -d -q -platform linux-x86-default -configure . -gen make`
`appweb: 2: ---------------------------------------------`
`appweb: Error: Security risk, directory /server/appweb/web is writeable by others`
`appweb: Error: Security risk, Program /server/appweb/linux-arm-default/bin/appweb is writeable by others`
`appweb: 2: Using config file: "/server/appweb/web/appweb.conf"`
`appweb: 2: Activating native module espHandler`
`appweb: 2: Loading native module libmod_ssl.so`
`appweb: 2: Activating module (Builtin) espHandler`
`appweb: 2: Started HTTP  service on "*:80"`
`appweb: 2: Create worker.0, pool has 1 workers. Limits 0-5.`
`appweb: 2: GET /dir/file1 HTTP/1.1`
`appweb: 2: Loading native module controller_001d4eec0208422e2460bcf0b34e2a2e.so`
`appweb: 2:   HTTP/1.1 200 OK`
`appweb: 2: GET /favicon.ico HTTP/1.1`
`appweb: 2: fileHandler: Cannot find filename /server/appweb/web/favicon.ico from referrer http://192.168.1.101/dir/file1`
`appweb: 2: Error: Cannot find /favicon.ico`
`appweb: 2:   HTTP/1.1 404 Not Found`
`appweb: 2: GET /dir/file1 HTTP/1.1`
`appweb: 2:   HTTP/1.1 200 OK`
`appweb: 2: GET /dir/file2 HTTP/1.1`
`appweb: 2:   HTTP/1.1 200 OK`
`appweb: 2: GET /dir/file3 HTTP/1.1`
`appweb: 2:   HTTP/1.1 200 OK`
`appweb: 2: GET /dir/file4 HTTP/1.1`
`appweb: 2:   HTTP/1.1 200 OK`
`appweb: 2: GET /dir/file5 HTTP/1.1`
`appweb: 2:   HTTP/1.1 200 OK`
`appweb: 2: POST /dir/file5 HTTP/1.1`
`appweb: 2:   HTTP/1.1 200 OK`
`...`
`appweb: 2: GET /dir/file76 HTTP/1.1`
`appweb: 2:   HTTP/1.1 200 OK`
`appweb: 2: POST /dir/file76 HTTP/1.1`
`appweb: 2:   HTTP/1.1 200 OK`

**Comment by embedthis** [comment]
That is not an appweb error message. It is coming from some other library.

Can you reproduce on the latest 4.X version (4.7.1). All our longevity test suites pass with this kind of load. You should not be seeing this.

**Comment by Waching** [comment]
I used 4.7.1 but esp report build error which is ok on 4.3.4:
`esp: Error: Directory name is used as application name and must be a valid C identifier`
The directory is **/lib/appweb/4.7.1/linux-arm-default** and esp command is:
`esp --platform /lib/appweb/4.7.1/linux-arm-default --config appweb.conf compile`
How to resolve this error?

**Comment by embedthis** [comment]
The base directory name must be a valid C identifier.

i.e. the directory your application is in, must not contain special characters. In 5.4, you can override this by specifying a "name" property in your package.json or esp.json with the name of the application. But in 4.7, I think you must have the directory be a valid C identifier.

**Comment by Waching** [comment]
So, should the directory be written as **\/lib\/appweb\/4.7.1\/linux-arm-default**?

**Comment by Waching** [comment]
I have known the above error but has another error:
`esp: Error: Canot find suitable platform linux-arm-default`
Is the name of **linux-arm-default** cannot be recognized by new esp?

**Comment by Waching** [comment]
I see the document within 4.7.1, it says that cross compilation should use 
`esp --config cross.conf compile ...`, 
but I cannot search any example of the cross.conf.
So how can I cross build the esp controller for arm platform with the version of 4.7.1?

**Comment by embedthis** [comment]
Please don't mix topics in one issue. We want one issue document per topic.

**Comment by embedthis** [comment]
You are confusing two directories:

1. The platform directory
2. The current directory of your application

The platform directory is where the objects and libraries are for the cross platform target
The current directory must be a simple name that can be used as part of the ESP module load function for your application. It is used when creating the package.json name field. If you must use a directory name that is a non-valid C identifier, hand edit the package.json name field to be a unique application name and recompile.

The --config file contains the compilation rules for your cross platform target.  By default, it is called esp.conf and resides in the installation directory for Appweb. You can edit this, or copy and create your own based on this original file.

**Comment by Waching** [comment]
Thank you I found the root cause by debugging it. It's because appweb lack of execute attribution after copy to the target position.
