### ISSUE TITLE
Websocket protocol cannot work

### ISSUE THREAD

**Issue by Waching** [embedthis/appweb#475]
# Environment:
Appweb version: 4.7.1
O/S: Linux 
CPU: arm
# Problem description:
I've ported appweb4.7.1 to our arm platform and it works well on http protocol.
But it cannot work on websocket protocol.  I test the samples/websockets-echo, but got below logs:
`appweb: 2: GET /ws/test/echo HTTP/1.1`
`appweb: 2: Loading native module controller_78ad4285fbb61106034b122b66ce6f57.so`
`appweb: 2:   HTTP/1.1 101 Switching Protocols`
The test webpage only displayed "Web Sockets Test".
I have no any idea, please give me some advice!
# appweb.conf:
`ErrorLog "stdout" level=4`
`Listen 80`
`AddHandler fileHandler`
`LoadModule espHandler libmod_esp`
`AddHandler espHandler esp`
`Header remove Content-Security-Policy`
`<Route ^/ws/{controller}/{action}$>`
`    Reset                   pipeline`
`    Prefix                  /ws`
`    Documents               .`
`    AddFilter               webSocketFilter`
`    AddHandler              espHandler`
`    Source                  controllers/controller.c`
`    Target                  run $1-$2`
`    RequestTimeout          10mins`
`    InactivityTimeout       1min`
`    WebSocketsProtocol      chat`
`    LimitWebSocketsMessage  40MB`
`    LimitWebSocketsPacket   40MB`
`</Route>`
`EspUpdate off`

**Comment by Waching** [comment]
I added log in echo_callback to print the event received, and they are below:
`appweb: 0: echo.c: echo_callback event:1`
`appweb: 0: echo.c: echo_callback event:3`
`appweb: 0: echo.c: echo_callback event:4`
`appweb: 0: echo.c: echo_callback event:6`
`appweb: 0: echo.c: echo_callback event:1`
`appweb: 0: echo.c: echo_callback event:1`
`appweb: 0: echo.c: echo_callback event:1`
`appweb: 0: echo.c: echo_callback event:1`
`appweb: 0: echo.c: echo_callback event:5`

**Comment by embedthis** [comment]
FYI: you can group a block of log messages with one set of backticks characters. e.g.

```
line1
line2
```

**Comment by embedthis** [comment]
You should see this:
![screen shot 2015-06-08 at 8 38 25 am](https://cloud.githubusercontent.com/assets/168175/8038700/d3b9b71c-0db9-11e5-80c0-351d72329fd0.png)

**Comment by Waching** [comment]
# Logs after run "appweb -4"
```
appweb: 4: Create worker.0, pool has 1 workers. Limits 0-5.
appweb: 4: Start monitors: min 2147483647, max 0
appweb: 3: ### Incoming connection from 192.168.1.100:3066 to 192.168.1.102:80
appweb: 4: New request from 192.168.1.100:3066 to 192.168.1.102:80

>>>>>>>>>> Receive content packet 0, len 507 (conn 0) >>>>>>>>>>
GET /ws/test/echo HTTP/1.1
Host: 192.168.1.102
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: null
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-CN,zh;q=0.8
Sec-WebSocket-Key: fGp5ZOAmBoP8yZdF2ttHpw==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Protocol: chat

<<<<<<<<<< End Receive packet, conn 0
appweb: 3: Use endpoint: :80
appweb: 3: Use host :80
appweb: 3: Select route "/ws/{controller}/{action}$" target "run"
appweb: 3: Select handler: "espHandler" for uri "/ws/test/echo"
appweb: 3: Select output filter: "webSocketFilter"
appweb: 4: Select connector: "netConnector"
appweb: 4: webSocketFilter: Opening a new request
appweb: 4: EspUpdate is disabled for this route: /ws/{controller}/{action}$
appweb: 3: esp: loadEspModule: "controller", /3rd_rw/appweb/cast_server/controllers/controller.c
appweb: 2: Loading native module controller_78ad4285fbb61106034b122b66ce6f57.so


>>>>>>>>>> Transmit content packet 0, len 363 (conn 0) >>>>>>>>>>
HTTP/1.1 101 Switching Protocols
Sec-WebSocket-Protocol: chat
X-Inactivity-Timeout: 60
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Request-Timeout: 600
Date: Thu, 01 Jan 1970 14:13:59 GMT
Sec-WebSocket-Accept: 3p54IB+ZA2NCM3dYrIdoHbNJxXs=
X-XSS-Protection: 1; mode=block
Connection: Upgrade
Accept-Ranges: bytes
Upgrade: WebSocket

<<<<<<<<<< End Transmit packet, conn 0
```

**Comment by embedthis** [comment]
Looks good on the server side. Debug from the browser side.

**Comment by Waching** [comment]
Thank you very much, I found the root cause on the browser side.

**Comment by embedthis** [comment]
So others can learn, can you post what the issue was?

**Comment by Waching** [comment]
The reason is simple, I don't know the test page need connect internet before, so I didn't connect to internet before.
