### ISSUE TITLE
Appweb 5.4.1 Anchoring action with http action

### ISSUE THREAD

**Issue by M5Mathieu** [embedthis/appweb#480]
Anchoring actions with http action

Is it possible to anchor actions so that we have a url pattern like this :
/api/{controller}/{sub-doc}/action

Notice that the last parameter ("action") is not a variable.

I would like to have a HttpAction that is called when a request is make that fits that pattern.
Can it be done?

HW platform : multiple
O/S: Linux uCLibc
Customization: Custom auth store (not involved here)
~~~
GET /api2/j/d HTTP/1.1
Host: [masked]
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36
DNT: 1
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,fr;q=0.6
Cookie: _appwebSessionId_=9930eb3fd424ce2df0de1239844c9628; -http-session-=1::http.session::76bad37e7b0f6a665207ac2acb44b705

11:02:42 2-0-2-2 request.pipeline route='^/api2/{controller}/{action}' handler='actionHandler' target='run' endpoint='0.0.0.0:80' host=':::80' referrer='' filename=''

11:02:42 2-0-2-2 request.error msg='Cannot find action: /api2/j/d'
~~~

This sample does not have the final constant parameter, but that's because we are doing some initial tests. 
 
appweb.conf
~~~ 
   <Route ^/api2/{controller}/{action}>
      SetHandler actionHandler
   </Route>
~~~

C Side tried (all 4) :
~~~
//httpDefineAction("/api2/{controller}/{action}", actionTestTest);
 httpCreateActionRoute(0, "/api2/{controller}/{action}", actionTestTest);
//httpDefineAction("/api2/", actionTestTest);
//httpDefineAction("/api2", actionTestTest);
~~~

The C codes are called just after the appweb.conf file is parsed.

**Comment by embedthis** [comment]
Actions are simple bindings of URLs to C functions. No tokens like {controller}

ESP does do what you want to do.

**Comment by karthikssdi** [comment]
Is Appweb 4.7 supports EJS or Esp

**Comment by M5Mathieu** [comment]
karthikCig the answer is ways, depending on that parameters you used to build appweb, please refer to the documentation.

Unfortunately, size is a big matter for embedded systems. Appweb is already on the limit on the size aspects. Adding esp is an option, but I would prefer not having too if I can...

A brief search allowed me to find that with esp to add such a functionality with espBindProc. And espDefine actions mostly seems to call httpDefineRoute, define routes calls httpSetRoutePattern.
To me, it looks it's through that that the pattern matching is made. EspDefineAction seems to add the function to be called to an MprHash, in a very similar way of that of httpDefineAction.

So if I retro engineered well, creating a route for each action to bind and binding the action, it should work?

**Comment by embedthis** [comment]
Unfortunately no.

The action handler looks up a hash with the request URI (rx->pathInfo). So it only ever calls a fixed routine. You could define and action handler that then looked up a 2nd hash based on the route parameters. 
```
static void startAction(HttpQueue *q)
{
    HttpConn    *conn;
    HttpAction     action;
    cchar       *name;

    conn = q->conn;
    assert(!conn->error);
    assert(!conn->tx->finalized);

    name = conn->rx->pathInfo;
    if ((action = mprLookupKey(conn->tx->handler->stageData, name)) == 0) {
        httpError(conn, HTTP_CODE_NOT_FOUND, "Cannot find action: %s", name);
    } else {
        (*action)(conn);
    }
}
```

**Comment by M5Mathieu** [comment]
I'm not sure to follow...

It's alright that it calls a fix routine. Currently I have something like : 
/api/datatype1?table=p&variable=a
/api/datatype2?table=p&variable=a
/api/datatype3?table=p&variable=a
that calls a difference C fonction for each datatype.
I would prefer to call : 
/api/p/datayype1/a
/api/p/datayype2/a
/api/p/datayype3/a
They would still call a single method for each of the datatype, and p and a variable would act has params. So from what I got from routes, these could be 
/api/{table}/datayype1/{variable}
/api/{table}/datayype2/{variable}
/api/{table}/datayype3/{variable}

So I'm not sure if I have to create a custom Handler that calls a makes a look-up depending on the parameters, or that there's a way with actionHandler to create a method (your startAction) that will then call an other C function depending of the parameters.

But, creating a custom handler that acts on /api/{table}/[datatype]/{variable} could work? Not that I put datatype in [] because I'm not sure what the best way to deal with it is. Making a custom handler per datatype? Handling it by calling related function by considering it an parameter? Something else?

Thank you for your help!

**Comment by embedthis** [comment]
No, just use 

    PUBLIC cchar *httpGetRouteVar(HttpRoute *route, cchar *key);

to get the route {action} parameters.
