### ISSUE TITLE
Appweb 4.7.1 cannot enable EST

### ISSUE THREAD

**Issue by Waching** [embedthis/appweb#483]
# Environment:
Appweb version: 4.7.1
O/S: Linux 
CPU: arm
# Problem description:
I want to use EST module in appweb, and it can be enabled in appweb4.3.4 by modified **appweb-linux-default.mk**, but in appweb4.7.1 there are building errors when I set **ME_COM_EST** to **1**.
The first error is:
`src/mpr/mprSsl.c:787:20: fatal error: est.h: No such file or directory`
If I add include path to build mprSsl.c's command, it will get another error:
`ld: cannot find -lest`
It seems like est was not built or enabled by configuring **appweb-linux-default.mk**.
Then how to enable EST module in appweb4.7.1?

**Comment by embedthis** [comment]
make ME_COM_EST=1 ME_COM_OPENSSL=0

Tested in 4.7.2, works fine here on mac os/x.

You'll have to debug further.

make SHOW=1 ....

Look and see if you have est.h in the source code

Look and see if there is a rule for est.h in projects/*linux*.mk

**Comment by Waching** [comment]
I checked the porjects/linux.mk and only found this:
`$(BUILD)/inc/est.h: $(DEPS_12)`
It seems that no rule for est.h and no rule for libest.so.
Can I port the rules from 4.7.2?
But I didn't find appweb4.7.2's source code in archive, could you please give me a uri to get source code or just get rules for est.h and libest.so?

**Comment by Waching** [comment]
I've ported rules from 4.3.4.
