### ISSUE TITLE
Appweb blocks processing 3rd request, when 2 requests are in sleep state. 

### ISSUE THREAD

**Issue by AppuPuli** [embedthis/appweb#487]
Hi,
Appweb is unable to serve the 3rd request if 2 request are stuck in processing. 
To double confirm this, I did some experiments with blocking Handlers process with sleep.
1) Created the simple handler( Used simpleHandler.c ) with only open call back.
2) In open call back of simplehandler, I added sleep of 300sec ( 5 min). Nothing else in it.
3) Configured the simpleHandler to be trigger, in case of /data/ URI route.

On client side, I fired two requests with /data, Which will go and sleep on those.
On client side, I fired 3 rd request ( Can be any thing like: GET index.html) and saw its not getting served.

Since Appweb is multi threaded process, It should not block other modules/handlers, if 2 of his requests are blocked during processing.

I used existing default configuration and along with configuring SimpleHandler, Increasing threads.
LimitWorkers 20
MinWorkers 2

I am not sure, am i missing anything here. Please advise me. 

Appweb version: 4.5.4
Environment: # uname -a
Linux Localmachine 2.6.32-24-generic #43-Ubuntu SMP Thu Sep 16 14:17:33 UTC 2010 i686 GNU/Linux

Thanks in Advance.

**Comment by embedthis** [comment]
Tested this with full appweb and it does not block. so you will need to debug more.

Also a general comment: despite Appweb being multi-threaded, you should not do long sleeps in threads. Threads are expensive resources and there are non-blocking APIs so you can sleep without tying up a thread.
