### ISSUE TITLE
Specify location of libssl

### ISSUE THREAD

**Issue by wimpunk** [embedthis/appweb#488]
I'm trying to crosscompile appweb within ptxdist but I can't manage to specify the location of libssl.  It keeps looking in `/usr/include` for the include files.  I tried to use `--with ssl=/path/to/ssl` but that doesn't seem to work. Anyone who can help?

**Comment by embedthis** [comment]
Are you building openssl or using the openssl installed as part of the O/S? 

What O/S?

   configure --with openssl=/path/to/openssl

**Comment by wimpunk** [comment]
I'm crosscompiling it on debian for arm-linux.  I'm used to cross compile packages with the autoconf tools but I really can't get appweb compiled with the me thing.  It seems to compile wihout php and ssl but fails when I try to add one of them.

**Comment by embedthis** [comment]
MakeMe update coming in the next day or so to fix this.
