### ISSUE TITLE
How to get the sessionID in Appweb ESP framework

### ISSUE THREAD

**Issue by Venubk** [embedthis/appweb#498]
Hi all,
I am appwebsp Famework for handling HTTP post requests. how to get session ID of current session.
i tried  httpGetSessionID(conn));
           getSessionID());
           conn->rx->session->id;
all the above reurned NULL.
please help me to solve the issue.

regards
Venu

**Comment by embedthis** [comment]
httpGetSession(conn, CREATE) will get the session and create one if it does not exist if CREATE is 1.

It returns a HttpSession. Thereafter httpGetSessionID will return the ID.
