### ISSUE TITLE
How to use openssl in Appweb 6 Source Code?

### ISSUE THREAD

**Issue by johnsonhuan** [embedthis/appweb#500]
Environment

Appweb version: 6.0.0, built from source 
O/S: Windows 8.1 pro
Hardware: PC

Problem Description:

Appweb 6 Source Code directory  not have the openssl librarys.
If i set the ME_COM_SSL == 1, build the appweb-windows-default.sln with vs2013 will prompt unresolved external symbol _mprSslInit. Whether the function mprSslInit need to implement？

thanks!

**Comment by embedthis** [comment]
Appweb does not include the full source for OpenSSL. You need to download that from OpenSSL and build that separately yourself.

Soon, we'll be including MbedTLS (aka PolarSSL) as part of Appweb. Just waiting for their Apache license release.

**Comment by embedthis** [comment]
There is an issue with MakeMe where if you have OpenSSL libraries installed on linux, but not the openssl headers, you can get SSL half configured .... this will be fixed with a MakeMe update in the next few days.

**Comment by 0402zhuhui** [comment]
i want to realize the appweb with the openssl in windows,
i already finished 64bit's openssl appweb with makeme,
but i can not realize the 32bits appweb,
does the appweb not support 32 bits openssl?

**Comment by embedthis** [comment]
Yes, works fine with 32 bit.
