### ISSUE TITLE
Cannot load compiled esp module

### ISSUE THREAD

**Issue by Waching** [embedthis/appweb#502]
# Environment:
Appweb version: 4.7.1
O/S: Linux 
CPU: arm
# Problem description:
Today, we found an issue that is "Cannot load compiled esp module".
The server print below logs:
```
appweb: Error: Cannot find module "cache/controller_78ad4285fbb61106034b122b66ce6f57.so",cwd: "/3rd_rw/appweb/cast_server", search path "/3rd_rw/appweb/linux-arm-default/bin:/3rd_rw/appweb/linux-arm-default/bin:/usr/local/lib/appweb/4.7.1/bin"
```
I don't know why.
It was ok before and seems suddenly happened.
The *controller_78ad4285fbb61106034b122b66ce6f57.so* is indeed in /3rd_rw/appweb/cast_server/cache.

If it is because of search path, why it was ok before?
BTW, how to set search path?

**Comment by Waching** [comment]
I've resolved it by add path to **PATH** in makefile.

**Comment by embedthis** [comment]
What did you need to add to PATH?  That should not impact the ability of Appweb to find compiled modules. How did that change the module or appweb?
