### ISSUE TITLE
pak install esp-angular-skeleton results in an error

### ISSUE THREAD

**Issue by nidalk** [embedthis/appweb#504]
pulled the appweb code from git, then added the pak utility.
I  pak install ejscript successfully. However  pak install esp-angular-skeleton results in an error fails
[nidalk@localhost appweb]$ pak install esp-angular-skeleton
      [Info] Search catalog: "pak" for esp-angular-skeleton for version ~*
     [Cache] esp-angular-skeleton 5.4.2
     [Mkdir] /home/nidalk/.paks/esp-angular-skeleton/embedthis/5.4.2
       [Get] https://github.com/embedthis/esp-angular-skeleton/archive/v5.4.2.tar.gz
   [Extract] Extract to /home/nidalk/.paks/esp-angular-skeleton/embedthis/5.4.2
      [Info] Search catalog: "pak" for exp-ng for version ~0.1
     [Cache] exp-ng 0.1.0
     [Mkdir] /home/nidalk/.paks/exp-ng/embedthis/0.1.0
       [Get] https://github.com/embedthis/exp-ng/archive/v0.1.0.tar.gz
   [Extract] Extract to /home/nidalk/.paks/exp-ng/embedthis/0.1.0
       [Run] npm install -g uglifyjs
Cannot access npm, errno 2
Cannot run installation script "postcache" for exp-ng
Error Exception: Command failed: npm
Error Output: Cannot access command
Stack:
 [00] run
 [01] run
 [02] memory, line 2, default, Cmd.locate('uglifyjs') || run('npm install -g uglifyjs') ; Cmd.locate('ng-annotate') || run('npm install -g ng-annotate')
 [03] runScripts
 [04] cachePak
 [05] cacheDependencies
 [06] cachePak
 [07] installCommon
 [08] install
 [09] process
 [10] main
 [11] __initializer__

pak: ERROR: Cannot cache esp-angular-skeleton because of missing required dependency "exp-ng"

[nidalk@localhost appweb]$ pak install exp-ng
      [Info] Search catalog: "pak" for exp-ng for version ~*
     [Cache] exp-ng 0.1.0
     [Mkdir] /home/nidalk/.paks/exp-ng/embedthis/0.1.0
       [Get] https://github.com/embedthis/exp-ng/archive/v0.1.0.tar.gz
   [Extract] Extract to /home/nidalk/.paks/exp-ng/embedthis/0.1.0
       [Run] npm install -g uglifyjs
Cannot access npm, errno 2
pak: ERROR: Cannot run installation script "postcache" for exp-ng
Error Exception: Command failed: npm
Error Output: Cannot access command
Stack:
 [00] run
 [01] run
 [02] memory, line 2, default, Cmd.locate('uglifyjs') || run('npm install -g uglifyjs') ; Cmd.locate('ng-annotate') || run('npm install -g ng-annotate')
 [03] runScripts
 [04] cachePak
 [05] installCommon
 [06] install
 [07] process
 [08] main
 [09] __initializer__

Any ideas,
Thanks

**Comment by nidalk** [comment]
[nidalk@localhost appweb]$ pak list
                 angular  1.4.3    installed       local      ~*  @npm/angular
                   certs  0.1.2    installed    optional    ~0.1  embedthis/certs
                ejscript  2.6.1    installed    optional    ~2.6  embedthis/ejscript
                     esp  6.0.1    installed    optional    ~6.0  embedthis/esp
                    http  6.1.1    installed  dependency    ~6.1  embedthis/http
                     mpr  6.1.1    installed  dependency    ~6.1  embedthis/mpr
             mpr-openssl  0.3.0    installed    optional    ~0.3  embedthis/mpr-openssl
                   osdep  0.8.7    installed  dependency    ~0.8  embedthis/osdep
                    pcre  1.0.4    installed  dependency    ~1.0  embedthis/pcre
                     ssl  0.9.2    installed  dependency    ~0.9  embedthis/ssl
                watchdog  0.2.0    installed  dependency    ~0.2  embedthis/watchdog
                    zlib  1.0.3    installed       local      ~*  embedthis/zlib

**Comment by embedthis** [comment]
The error is:

```
Cannot access npm, errno 2
```

Some of the packages used by esp-angular-skeleton use utilities that are installed via npm.  The error message could be clearer.

See:

https://docs.npmjs.com/getting-started/installing-node

**Comment by embedthis** [comment]
We've updated the error message in the various dependency packages.

**Comment by armagardon** [comment]
npm is the package manage tool of node.js, install node.js and then install npm to solve this problem.
