### ISSUE TITLE
What's wrong with "authpass"?

### ISSUE THREAD

**Issue by armagardon** [embedthis/appweb#505]
I use the password tool "authpass" to generate an user password for my system, for example:
$authpass --password michael example.com zhang admin
then i get a password string, for example:
BF1:00128:4VuD5Te9a5S0W990:g1l6KAJnZISC4UBp77lMyxEJuT5Yhx1E

On the other hand, I use "mprCheckPassword" api to use the same username and password to verify the password, but it fails.

I think that there must be something wrong.

Can anybody helps me? Thanks.

BTW: I am using appweb 6.0.1 on an Ubuntu 14.04 X64 desktop PC.

**Comment by embedthis** [comment]
But check password does not use the username. It checks the password only against the password hash: BF1:00128:4VuD5Te9a5S0W990:g1l6KAJnZISC4UBp77lMyxEJuT5Yhx1E
