### ISSUE TITLE
Missing parameters for multipart/form-data with large numbers of input fields 

### ISSUE THREAD

**Issue by slagelwa** [embedthis/appweb#530]
Observed in Embedthis Appweb
Versions: 6.0.0 and 6.0.3
OS: Windows
CPU: x64

I noticed with an script I'm supporting  where not all of the input form elements are passed down to the subsequent CGI program.  The script makes a html form containing a reasonable number of input checkboxes (all named the same) and posts this form to a CGI program as multipart/form-data.  When the number of checked items reaches a certain size I start "losing" CGI parameters.  There doesn't seem to be a pattern to which parameters get lost -- meaning it can be any number of parameters and not necessarily the input checkboxes.  I used Firefox/Firebug to confirm that all of the fields were indeed being submitted in the http request in the right format, and turning on tracing/logging in appweb I didn't see anything indicative of an error.

Here's a very short script that demonstrates the problem.  (My apologies its in Perl, that's what I'm working with here.)  

```
#!perl
use CGI;

print "Content-type: text/html\n\n";
print "<HTML>\n";
print "<BODY BGCOLOR=\"\#FFFFFF\">\n";

if ( CGI::param('submit') ) {
   print "<h3>CGI parameters</h3>\n";
   for my $p ( CGI::param() ) {
      if ( $p eq 'src_files' ) {
         for my $m ( CGI::multi_param($p) ) {
            print "$p = $m<br>\n";
         }
      } else {
         print "$p = ", scalar CGI::param($p), "<br>\n";
      }
} else {
   print "<FORM ACTION='formbug.pl' METHOD='post' ENCTYPE='multipart/form-data'>\n";
   for ( 0..40 ) {
      print "<INPUT type='checkbox' name='src_files' value='${_}field' CHECKED>${_}field</INPUT<br>\n";
   }
   print "<INPUT type='submit' name='submit' value='Submit'>\n";
   print "</FORM>\n";
}
print "</BODY></HTML>\n";
````

**Comment by embedthis** [comment]
You have many input fields in your sample of the same name "src_files". These will overwrite the prior input field value of that name. If you make them unique, you should see them all.
