### ISSUE TITLE
ROM file system support broken in multiple places

### ISSUE THREAD

**Issue by rks2003** [embedthis/appweb#539]
with Appweb 6.1 and earlier versions

1) makerom.c is not included in appweb 5.x & 6.x (but in 3.x & 4.x)

2) Compile error in httpLib.c, if ME_ROM is defined (missing return value while function should return an int):
 PUBLIC int httpSendOpen(HttpQueue *q) { }
 
3) Appweb crashes after calling mprCreate in mprGetAbsPath, if ME_ROM is defined
because fs is used while not initialized:
```
#if ME_ROM
    result =  mprNormalizePath(path);
    mprMapSeparators(result, defaultSep(fs));
    return result;
#elif CYGWIN
```

4) wrong validations of relativ/absolut path names in Windows (C:\ expected) and Linux (/ expected), e.g. in httpSetFilename() while makerom does not support absolute paths 

5) On Linux, mprGetRelPath changes the path from "index.html" to something like "../../../../../../index.html" if ME_ROM is defined 

6) ROM hash table not working if romfiles.c contains multiple large files (results in file not found)

**Comment by embedthis** [comment]
Thanks. Makerom has been moved to an external package at:

https://github.com/embedthis/makerom

cd appweb-source
pak install makerom
me

This will download, install and build makerom for you.

Can you give more details on 4, 5 and 6.

**Comment by rks2003** [comment]
1) OK thank you. But it would be very helpful to add a hint to your appweb documentation were to find the tool.

4 & 5) I've changed the code in httpSetFilename

#ifndef ME_ROM
    if (!(tx->flags & HTTP_TX_NO_CHECK)) {
        if (!mprIsAbsPathContained(filename, conn->rx->route->documents)) {
            info->checked = 1;
            info->valid = 0;
            httpError(conn, HTTP_CODE_BAD_REQUEST, "Filename outside published documents");
            return 0;
        }
    }
#else
    while ((((char*)filename)[0] == '/') || (((char*)filename)[0] == '\\'))
    {
       memmove((char*)filename, (char*)(filename+1), strlen(filename));
    }
#endif

added #ifndef ME_ROM around the if statement [ (if (!(tx->flags & HTTP_TX_NO_CHECK)) { ]
to solve 4)
and added the #else to solve 5)
but I'm pretty sure that this are only workarounds!

without this changes ROM support does not work. I've tried to configure the server in different ways like maConfigureServer(NULL, "/", "/", "0.0.0.0", 80); or maConfigureServer(NULL, ".", ".", "0.0.0.0", 80); or maConfigureServer(NULL, "", "", "0.0.0.0", 80);

now (with the above changes) maConfigureServer(NULL, "/", "/", "0.0.0.0", 80); works for me

6) found the reason
Under windows the given path in the function call "static MprRomInode *lookup(MprRomFileSystem *rfs, cchar *path)" is something like "kendo\examples\grid\editing.html" with '\' but my romfiles.c contains '/'. Accessing the rom files works fine if the server runs on a linux machine but not on windows.

PUBLIC MprRomInode romFiles[] = {
    { "", 0, 0, 0 },
    { "conf/server.conf", _file_2, 2489, 2 },
    { "index.html", _file_3, 11, 3 },
    { "kendo/examples/content/shared/js/console.js", _file_4, 4444, 4 },
    { "kendo/examples/content/shared/styles/examples-offline.css", _file_5, 11657, 5 },
    { "kendo/examples/grid/editing.html", _file_6, 4116, 6 },
    { "kendo/js/jquery.min.js", _file_7, 92629, 7 },
    { "kendo/js/kendo.all.min.js", _file_8, 2491892, 8 },
    { "kendo/styles/kendo.common.min.css", _file_9, 243472, 9 },
    { "kendo/styles/kendo.dataviz.default.min.css", _file_10, 333, 10 },
    { "kendo/styles/kendo.dataviz.min.css", _file_11, 333, 11 },
    { "kendo/styles/kendo.default.min.css", _file_12, 59050, 12 },
    { "kendo/styles/kendo.rtl.min.css", _file_13, 12655, 13 },
    { 0, 0, 0, 0 },
};

7) it would be helpful to support something like mprSetLogHandler for the http trace, e.g. because the traceLogDirective is not supported if using ROM files.

**Comment by rks2003** [comment]
sorry,

the code changes:

#ifndef ME_ROM
if (!(tx->flags & HTTP_TX_NO_CHECK)) {
if (!mprIsAbsPathContained(filename, conn->rx->route->documents)) {
info->checked = 1;
info->valid = 0;
httpError(conn, HTTP_CODE_BAD_REQUEST, "Filename outside published documents");
return 0;
}
}
#else
while ((((char)filename)[0] == '/') || (((char)filename)[0] == '\'))
{
memmove((char)filename, (char)(filename+1), strlen(filename));
}
#endif

resolving only problem 4)
to solve 5) I use the following workaround

PUBLIC MprFileSystem *mprCreateFileSystem(cchar *path)
{
    MprFileSystem   *fs;
    char            *cp;

#if ME_ROM
    fs = (MprFileSystem*) mprCreateRomFileSystem(path);
#else
    fs = (MprFileSystem*) mprCreateDiskFileSystem(path);
#endif

#if ME_WIN_LIKE
    fs->separators = sclone("\\/");
    fs->newline = sclone("\r\n");
#elif CYGWIN
    fs->separators = sclone("/\\");
    fs->newline = sclone("\n");
#else
    fs->separators = sclone("/");
    fs->newline = sclone("\n");
#endif

#if ME_WIN_LIKE || MACOSX || CYGWIN
    fs->caseSensitive = 0;
#else
    fs->caseSensitive = 1;
#endif

#if ME_WIN_LIKE || VXWORKS || CYGWIN
    fs->hasDriveSpecs = 1;
#endif

    if (MPR->fileSystem == NULL) {
        MPR->fileSystem = fs;
    }
    fs->root = mprGetAbsPath(path);
    if ((cp = strpbrk(fs->root, fs->separators)) != 0) {
        *++cp = '\0';
    }
#if ME_WIN_LIKE || CYGWIN
    fs->cygwin = mprReadRegistry("HKEY_LOCAL_MACHINE\\SOFTWARE\\Cygwin\\setup", "rootdir");
    fs->cygdrive = sclone("/cygdrive");
#endif
    return fs;
}

**Comment by embedthis** [comment]
Quick question while we digest this.

Why are you using ME_ROM on windows?

**Comment by rks2003** [comment]
User should not be able to modify or delete web content files.

br,
Ralf


Am 23.10.2015 um 18:51 schrieb Embedthis Software:

**Comment by embedthis** [comment]
Okay, but they normally cannot do this.  You don't need to use ME_ROM for that.

You can designate that PUT and upload methods are not permitted or you can designate special directories for the uploaded content.

**Comment by rks2003** [comment]
I mean user (or admin) with access to the file system on the PC were the web based application will be installed. Deleting files will result in problems / errors, also changing images shall be prohibited.

**Comment by embedthis** [comment]
That is marginal security via obscurity. An admin user can simply remove the executable too or other critical files. So it really doesn't offer any meaningful security. Pushing that expectation on a web server is not appropriate.

What handlers do you plan to use?

The reason is that ESP loses a lot of functionality without dynamic loading and a file system.

Net/Net: we want ME_ROM to work, but the functionality is really reduced (or not available) for some handlers: ESP, Ejscript, PHP. So we are actively discouraging it.

Our GoAhead web server is a smaller, simpler web server and relies less on the file system. So compiling pages into rom is simpler with GoAhead.

**Comment by rks2003** [comment]
Difficult questions. Currently I'm only eveluating Appweb, whether it fit's to our needs. Also thought about GoAhead.
Removing the executable is true, nothing will work - but:
- if deleting only some ressource file may cause problems which will burden our support.
- changing images to remove cooperate design is a no go
- I'm currently not sure whether e.g. ESP really requires real FS access

Currently we plan only to support a Websocket handler with kendo UI scripts inside the ROM.

**Comment by embedthis** [comment]
We've been reviewing your suggested changes (and thank you very much for these). We may have a simpler approach to some of the edits.

By making mprGetCurrentPath (getcwd) return "/" as the current directory, and having all the files in the ROM index start with "/", then most of the mprGetAbs, mprGetRel just works. It is logically simpler to have the ROM file system be rooted at "/". 

This required a change to makerom and some to the mpr and appweb code. But the changes are minor. We're going to explore the same changes to GoAhead.

If you are interested, we can check those in for you to test. 

FYI: GoAhead does not support web sockets.

**Comment by rks2003** [comment]
At first let me thank you for your fast responses!
Yes, I'm comfortable with GoAhead and I know that there will be some challenges - that's why I'm currently evaluating Appweb.
And yes, I also thought about changing makerom, but I wasn't sure whether this will solve all my problems, mainly because I'm gradually explored them.

**Comment by rks2003** [comment]
and yes, you can provide me your changes and I will test them!

**Comment by embedthis** [comment]
Checked in now.

**Comment by rks2003** [comment]
Unfortunately I'm not able to load the latest 'makerom.c' version (only the master branch is accessible via Github!?)

**Comment by embedthis** [comment]
No, all branches are available on github and via command line download. You need to checkout the dev branch.

**Comment by rks2003** [comment]
You pointed me to the site https://github.com/embedthis/makerom
On this Github Web access is only a default branch 'master' available and no other active branches like dev!?

**Comment by embedthis** [comment]
Sorry, makerom only has a master branch. That is the right branch and the changes were just committed.

Appweb, you need the dev branch.

**Comment by rks2003** [comment]
It works! Thank you!

**Comment by rks2003** [comment]
Next problems:
- certificates in ROM file not supported (using OpenSSL)
- wrong normalization (Windows) from "cert/server.pem" to "\cert\server.pem"

**Comment by rks2003** [comment]
How to configure or code a passphrase for private key files?

**Comment by rks2003** [comment]
OK, it may make no sense to hold certificate files in the ROM, but you are validating whether such files exists inside the ROM FS while parsing the configuration (e.g. sslCertificateFileDirective ==> if (!mprPathExists...)) while your OpenSsl-Wrapper directly accesses the OS FS

**Comment by embedthis** [comment]
Please open new problems in new issue tickets and please provide more detail. Chat is fine, but if you want an issue looked at, you need to open an new issue and provide sufficient detail.

Please read: https://github.com/embedthis/goahead/issues/111
