### ISSUE TITLE
ROM with OpenSSL, ESP and Disk FS

### ISSUE THREAD

**Issue by rks2003** [embedthis/appweb#550]
1) while the used OpenSSL-API calls in the Appweb OpenSSL wrapper accessing certificates directly on the real FS, the sslCertificateFileDirective function (executed on parsing config file) validates whether the cert files are included into the ROM files: if (!mprPathExists(...))
a) this fails especially under Windows, because the path is normalized to "\cert\server.pem" while ROM file now works only with '/'
b) this fails if certificate files are not included into the ROM
==> so my current workaround is to include certificate files into the ROM-FS AND copy them on the real OS-FS, first to make the config parser happy, second for the OpenSSL API.
2) It seams that passphrase protected private key files are not supported (or how to configure)?

**Comment by embedthis** [comment]
We'll look into supporting certs from rom. But we won't actively support mixed mode or partial-ROM. So it may or may not work for you with documents in ROM and other files on a file system.

We definitely want full ROM to work however.

You don't want password protected certs. Otherwise, you must be there whenever the system is rebooted to enter the pass phrase.

**Comment by embedthis** [comment]
We've updated the mpr-openssl and mpr-mbedtls paks to support loading certificates, keys and revoke lists from ROM. This will be included in the next release.

**Comment by rks2003** [comment]
great, ty

**Comment by embedthis** [comment]
Can you please pin point the location where the windows mixed-path delimiter comparison occurs. you said:
```
a) this fails especially under Windows, because the path is normalized to "\cert\server.pem" while ROM file now works only with '/'
```

Also, if you are interested in helping. You could try the current dev branch which should have most of your suggested fixes. We plan on releasing later this month and it would be great to cover your use case in this release.

**Comment by rks2003** [comment]
here my change for Windows in mprLib.c:

PUBLIC MprFileSystem *mprCreateFileSystem(cchar *path)
{
    MprFileSystem   *fs;
    char            *cp;

#if ME_ROM
    fs = (MprFileSystem*) mprCreateRomFileSystem(path);
#else
    fs = (MprFileSystem*) mprCreateDiskFileSystem(path);
#endif

#if ME_WIN_LIKE
# if ME_ROM
    fs->separators = sclone("/\\");
# else // ME_ROM
    fs->separators = sclone("\\/");
# endif // ME_ROM
    fs->newline = sclone("\r\n");
#elif CYGWIN
    fs->separators = sclone("/\\");
    fs->newline = sclone("\n");
#else
    fs->separators = sclone("/");
    fs->newline = sclone("\n");
#endif

// ...

=====

I've tested your current dev branch code:

it crashes if ME_ROM is not set in mpr-openssl.c while calling the function configOss at:

 if (setKeyFile(ctx, ssl->keyFile) < 0)

because the key File is not configured (the certFile contains cert + key)

if ME_ROM is set, I get an SSL error!

**Comment by embedthis** [comment]
For windows, it may be a better approach to change makerom to generate "\" delimiters for windows. The rom lookup code should probably support both / and \ because that is how windows treats paths. Thoughts?

Thanks for the mpr-openssl fix. That is checked in now.

**Comment by rks2003** [comment]
I think tolerant lookup code would solve further possible problems.

For makerom it only has to be defined what to use, '/' is fine.
Otherwiese you also have to think about the root in windows (e.g. "C:\" ) as prefix for every path in the ROM!?

But if you anytime switch to mixed mode (ROM & real OS), you are prepared if you support
every notation (in appweb & makerom) today:
   ../xyz/test.txt
   /abc/def/test.txt
   ..\xyz\test.txt
   C:\abc\def\test.txt

**Comment by embedthis** [comment]
Windows + ROM is a use case that was never considered. 

However, the core appweb code handles windows paths correctly throughout, so it is probably best that we go down the path of putting Native windows paths in the romFile.c with \ delimiters and make the lookup code in mprLib handle both / and \. That way we are going down the path of least resistance.

The basic assumptions for windows ROM are:

* makerom generates \ delimiters
* lookup in mprLib will handle requests for paths with both / and \
* There is no drive spec for rom files. i.e. this is not drive C: so there must never be a drive on the filename
* The virtual current directory is "/" and cannot be changed. In reality, the application does have a current directory that is not "/", but for the ROM file system, it thinks the application is at the top of the ROM file system tree
* Need to change mprGetAbs path not to convert filenames to have a drive spec

Using ESP with windows ROM is probably another set of issues that needs checking.

**Comment by embedthis** [comment]
In doing this work, there may be a more flexible solution:

* Separate disk support from rom enable support. i.e. permit a rom file system and a disk file system
* Have a virtual rom mount point. For example: /rom/filenames
* Have a configuration "configure --rom --set mpr.disk=false" to disable disk support and have only a rom file system
* Add option to makerom to support the mount point "--mount /rom"
* Add a main.me configuration default for the mount point "mpr.romMount: '/rom'

Net / Net:

For your use case, you can enable rom AND keep disk support too:

    ./configure --rom

The following command will invoke makerom with a /rom mount point and compile the files under server/web into a rom file system => src/rom.c

    me -s rom
    me

This seems to be the best of both worlds. You can have pure ROM with no disk file system and you can have compiled web pages into code with a file system.

This patch also enables ESP pages in ROM. If you use 

    esp --combine compile

it will compile the web pages for the route and put them in cache/server.c. The src/server/appweb.c will then include "cache/server.c" and initialize these esp pages.

This should complete flexible ROM support for windows and ESP.

Will check this in shortly.

**Comment by embedthis** [comment]
Should be good to test now.

**Comment by rks2003** [comment]
Dont How to use!?

I've tried several path configurations/combinations with/without "/rom" prefix...

As first I cannot open the server.conf from ROM!?

MprRomFileSystem* fsRom = mprCreateRomFileSystem("/", romFiles);
// ...
maConfigureServer(NULL, "/", "/rom", "0.0.0.0", 80);
// ...
if (maParseConfig("/rom/conf/server.conf") < 0) 

makerom is called like this:
   ./makerom --prefix webfiles/ . webfiles/conf/server.conf webfiles/index.html webfiles/mom.html ... 
   webfiles/css/Default/sprite_kpi_2x.png > romfiles.c

**Comment by embedthis** [comment]
The new makerom is checked in (version 0.3). This added a mount point option. Use like this:

    makerom --mount /rom . web web/index.html appweb.conf ....

These files are then accessible at:
```
/rom/web/index.html
/rom/appweb.conf
```

Invoke appweb with

    appweb --conf /rom/appweb.conf

Set Documents to:

    /rom/web

**Comment by rks2003** [comment]
Sorry, not working for me!
I've tested on Windows.
I was able to retrieve server.conf and the SSL certificate from ROM, but no http request.
  https://10.103.35.85
  https://10.103.35.85/index.html
  https://10.103.35.85/rom/web/index.html
ended with Access Error: 404 -- Not Found

By the way, the new makerom option '--mount' is not compatible with '--prefix'
--mount /rom --prefix webfiles/  
on a file like /webfiles/web/index.html
generates /web/index.html 
but not /rom/web/index.html

**Comment by rks2003** [comment]
I can provide a .zip file containing my reduced project to reproduce the problem

**Comment by embedthis** [comment]
What do you mean "not compatible"?

The --prefix option will remove the "webfiles" portion of the filenames. This is typically not what you want to do. You need to separate the web content from the appweb.conf. So you typically should not be using --prefix.

NOTE: you should specific a Documents directory with appweb.conf of "/rom/webfiles". And then the URL will not have /rom or /webfiles int he URL.

**Comment by embedthis** [comment]
Added some doc:

https://embedthis.com/appweb/doc/developers/rom.html

**Comment by rks2003** [comment]
Unfortunately also not working on linux. Used your original appweb-dev code (instead of my integrated version) and the step by step instruction (https://embedthis.com/appweb/doc/developers/rom.html).
appweb.conf can be read from ROM, but I cannot access my index.html from ROM ("/rom/web" were my index.html resists was the configured directory in appweb.conf)

**Comment by embedthis** [comment]
A general comment:

When submitting issues, you need to provide more information. Just saying it doesn't work does not help us if it works fine here. So please submit a full description and a section of the HTTP request log like this:

```
GET /index.html HTTP/1.1
Accept: */*
Date: Fri, 27 Nov 2015 17:23:32 GMT
Host: 127.0.0.1:4100
Connection: close
User-Agent: Embedthis-http
Accept-Ranges: bytes
----
09:23:32 1-0-1-1 request.pipeline route='' handler='fileHandler' target='run' endpoint='127.0.0.1:4100' host='default' referrer='' filename='/rom/web/index.html'
```

Also, please use markdown to format your code snippets. See: https://help.github.com/articles/github-flavored-markdown/

That being said, we're continuing to test and have checked in two ROM related changes that may help.

**Comment by rks2003** [comment]
yes you are right, here some more information:

I tested your current dev version on Redhat Linux using
configure --rom 
and so on as you described in your latest documentation

---

if ErrLog error.log is set in appweb.conf (mixed mode ROM + real FS), writing the log file on real FS is not possible:

sudo ./appweb --conf /rom/appweb.conf
Cannot open log file /rom/error.log, errno=2
Cannot write to ErrorLog: /rom/error.log
Error with directive "ErrorLog". At line 9 in /rom/appweb.conf

---

HTTP trace is not supported if ME_ROM is defined (error parsing appweb.conf with appropriate instruction). Therefor the only output I can provide is:

sudo ./appweb --conf /rom/appweb.conf
11/27/15 18:50:14 2 appweb, Configuration for Embedthis Appweb
11/27/15 18:50:14 2 appweb, ----------------------------------
11/27/15 18:50:14 2 appweb, Version:            6.2.0
11/27/15 18:50:14 2 appweb, BuildType:          Release
11/27/15 18:50:14 2 appweb, CPU:                x64
11/27/15 18:50:14 2 appweb, OS:                 linux
11/27/15 18:50:14 2 appweb, Host:               ber-rd5083
11/27/15 18:50:14 2 appweb, Configure:          me configure --rom
11/27/15 18:50:14 2 appweb, ----------------------------------
11/27/15 18:50:14 0 info http, Started HTTP service on *:80
11/27/15 18:50:40 5 info mpr thread, Create worker.0, pool has 1 workers. Limits 0-16.

---

The above output is from starting appweb and requesting the one and only page.

the client always says: 404 file not found!

I've tried:
http://127.0.0.1
http://127.0.0.1/index.html
http://127.0.0.1/web/index.html
http://127.0.0.1/rom/web/index.html

while appweb.conf was read from ROM (see note #1: /rom/error.log problem after parsing appweb.conf from ROM)

---

my appweb.conf:

cat ../../../appweb.conf 
ErrorLog "stdout" size=1MB level=5 backup=0 anew

RequestTimeout 9223372036854775807

Home "."
Documents "/rom/web"

Listen 80

LimitWorkers 16
LimitClients 256
LimitRequestBody 419430400
LimitResponseBody 204857600

AddHandler fileHandler js html jpeg jpg gif png ico css eot ttf woff woff2 txt
Cache client=1day extensions="js,html,jpeg,jpg,gif,png,ico,css,eot,ttf,woff,woff2,txt"

---

my rom.c:

cat ../../../src/rom.c 
/*
    romFiles -- Compiled Files
 */
#include "mpr.h"

#if ME_ROM
static uchar _file_1[] = {
      69, 114, 114, 111, 114,  76, 111, 103,  32,  34, 115, 116, 100, 111, 117, 116,
      34,  32, 115, 105, 122, 101,  61,  49,  77,  66,  32, 108, 101, 118, 101, 108,
      61,  53,  32,  98,  97,  99, 107, 117, 112,  61,  48,  32,  97, 110, 101, 119,
      10,  10,  82, 101, 113, 117, 101, 115, 116,  84, 105, 109, 101, 111, 117, 116,
      32,  57,  50,  50,  51,  51,  55,  50,  48,  51,  54,  56,  53,  52,  55,  55,
      53,  56,  48,  55,  10,  10,  72, 111, 109, 101,  32,  34,  46,  34,  10,  68,
     111,  99, 117, 109, 101, 110, 116, 115,  32,  34,  47, 114, 111, 109,  47, 119,
     101,  98,  34,  10,  10,  76, 105, 115, 116, 101, 110,  32,  56,  48,  10,  10,
      76, 105, 109, 105, 116,  87, 111, 114, 107, 101, 114, 115,  32,  49,  54,  10,
      76, 105, 109, 105, 116,  67, 108, 105, 101, 110, 116, 115,  32,  50,  53,  54,
      10,  76, 105, 109, 105, 116,  82, 101, 113, 117, 101, 115, 116,  66, 111, 100,
     121,  32,  52,  49,  57,  52,  51,  48,  52,  48,  48,  10,  76, 105, 109, 105,
     116,  82, 101, 115, 112, 111, 110, 115, 101,  66, 111, 100, 121,  32,  50,  48,
      52,  56,  53,  55,  54,  48,  48,  10,  10,  65, 100, 100,  72,  97, 110, 100,
     108, 101, 114,  32, 102, 105, 108, 101,  72,  97, 110, 100, 108, 101, 114,  32,
     106, 115,  32, 104, 116, 109, 108,  32, 106, 112, 101, 103,  32, 106, 112, 103,
      32, 103, 105, 102,  32, 112, 110, 103,  32, 105,  99, 111,  32,  99, 115, 115,
      32, 101, 111, 116,  32, 116, 116, 102,  32, 119, 111, 102, 102,  32, 119, 111,
     102, 102,  50,  32, 116, 120, 116,  10,  67,  97,  99, 104, 101,  32,  99, 108,
     105, 101, 110, 116,  61,  49, 100,  97, 121,  32, 101, 120, 116, 101, 110, 115,
     105, 111, 110, 115,  61,  34, 106, 115,  44, 104, 116, 109, 108,  44, 106, 112,
     101, 103,  44, 106, 112, 103,  44, 103, 105, 102,  44, 112, 110, 103,  44, 105,
      99, 111,  44,  99, 115, 115,  44, 101, 111, 116,  44, 116, 116, 102,  44, 119,
     111, 102, 102,  44, 119, 111, 102, 102,  50,  44, 116, 120, 116,  34,  10,  10,
    0 };

static uchar _file_3[] = {
      60,  33,  68,  79,  67,  84,  89,  80,  69,  32, 104, 116, 109, 108,  62,  10,
      60, 104, 116, 109, 108,  62,  10,   9,  60, 104, 101,  97, 100,  62,  10,   9,
       9,  60, 116, 105, 116, 108, 101,  62,  77, 117, 108, 116, 105,  45,  79,  77,
      77,  32,  77,  97, 110,  97, 103, 101, 114,  60,  47, 116, 105, 116, 108, 101,
      62,  10,   9,   9,  60, 109, 101, 116,  97,  32,  99, 104,  97, 114, 115, 101,
     116,  61,  34, 117, 116, 102,  45,  56,  34,  62,  10,   9,   9,  60, 109, 101,
     116,  97,  32, 104, 116, 116, 112,  45, 101, 113, 117, 105, 118,  61,  34,  67,
     111, 110, 116, 101, 110, 116,  45,  84, 121, 112, 101,  34,  32,  99, 111, 110,
     116, 101, 110, 116,  61,  34, 116, 101, 120, 116,  47, 104, 116, 109, 108,  59,
      32,  99, 104,  97, 114, 115, 101, 116,  61, 117, 116, 102,  45,  56,  34,  62,
      10,   9,  60,  47, 104, 101,  97, 100,  62,  10,   9,  60,  98, 111, 100, 121,
      62,  10,   9,   9,  60, 110, 111, 115,  99, 114, 105, 112, 116,  62,  10,   9,
       9,   9,  60, 116,  97,  98, 108, 101,  32,  99, 101, 108, 108, 112,  97, 100,
     100, 105, 110, 103,  61,  48,  32, 119, 105, 100, 116, 104,  61,  49,  48,  48,
      37,  62,  10,   9,   9,   9,   9,  60, 116, 114,  62,  60, 116, 100,  32, 104,
     101, 105, 103, 104, 116,  61,  56,  48,  62,  60,  47, 116, 100,  62,  60,  47,
     116, 114,  62,  10,   9,   9,   9,  60,  47, 116,  97,  98, 108, 101,  62,  10,
       9,   9,   9,  60, 116,  97,  98, 108, 101,  32,  97, 108, 105, 103, 110,  61,
      99, 101, 110, 116, 101, 114,  32,  99, 101, 108, 108, 112,  97, 100, 100, 105,
     110, 103,  61,  49,  48,  32, 115, 116, 121, 108, 101,  61,  34,  98, 111, 114,
     100, 101, 114,  45, 119, 105, 100, 116, 104,  58,  49, 112, 120,  59,  32,  98,
     111, 114, 100, 101, 114,  45, 115, 116, 121, 108, 101,  58, 115, 111, 108, 105,
     100,  59,  32,  98, 111, 114, 100, 101, 114,  45,  99, 111, 108, 111, 114,  58,
      35,  49,  53,  51,  50,  53,  70,  59,  34,  62,  10,   9,   9,   9,   9,  60,
     116, 114,  62,  10,   9,   9,   9,   9,   9,  60, 116, 100,  32, 114, 111, 119,
     115, 112,  97, 110,  61,  50,  62,  10,   9,   9,   9,   9,   9,   9,  60, 105,
     109, 103,  32, 115, 114,  99,  61, 105, 109,  97, 103, 101, 115,  47, 119,  97,
     114, 110, 105, 110, 103,  46, 112, 110, 103,  32,  97, 108, 116,  61, 101, 114,
     114, 111, 114,  62,  10,   9,   9,   9,   9,   9,  60,  47, 116, 100,  62,  10,
       9,   9,   9,   9,   9,  60, 116, 100,  62,  10,   9,   9,   9,   9,   9,   9,
      60,  98,  62,  78, 111,  32,  74,  97, 118,  97,  83,  99, 114, 105, 112, 116,
      33,  60,  47,  98,  62,  10,   9,   9,   9,   9,   9,  60,  47, 116, 100,  62,
      10,   9,   9,   9,   9,   9,  60, 116, 100,  32,  97, 108, 105, 103, 110,  61,
     114, 105, 103, 104, 116,  62,  10,   9,   9,   9,   9,   9,  60,  47, 116, 100,
      62,  10,   9,   9,   9,   9,  60,  47, 116, 114,  62,  10,   9,   9,   9,   9,
      60, 116, 114,  62,  10,   9,   9,   9,   9,   9,  60, 116, 100,  32,  99, 111,
     108, 115, 112,  97, 110,  61,  50,  62,  84, 111,  32, 117, 115, 101,  32, 116,
     104, 101,  32,  77, 117, 108, 116, 105,  45,  79,  77,  77,  32,  77,  97, 110,
      97, 103, 101, 114,  32,  74,  97, 118,  97,  83,  99, 114, 105, 112, 116,  32,
     104,  97, 115,  32, 116, 111,  32,  98, 101,  32, 101, 110,  97,  98, 108, 101,
     100,  32, 105, 110,  32, 121, 111, 117, 114,  32,  98, 114, 111, 119, 115, 101,
     114,  33,  60,  47, 116, 100,  62,  10,   9,   9,   9,   9,  60,  47, 116, 114,
      62,  10,   9,   9,   9,  60,  47, 116,  97,  98, 108, 101,  62,  10,   9,   9,
      60,  47, 110, 111, 115,  99, 114, 105, 112, 116,  62,  10,   9,  60, 100, 105,
     118,  32, 105, 100,  61,  34, 101, 120,  97, 109, 112, 108, 101,  34,  62,  10,
       9,  60, 115, 112,  97, 110,  32, 105, 100,  61,  34, 110, 111, 116, 105, 102,
     105,  99,  97, 116, 105, 111, 110,  34,  62,  60,  47, 115, 112,  97, 110,  62,
      10,   9,  60, 115,  99, 114, 105, 112, 116,  62,  10,   9,   9, 119, 105, 110,
     100, 111, 119,  46, 108, 111,  99,  97, 116, 105, 111, 110,  46, 114, 101, 112,
     108,  97,  99, 101,  40,  39, 104, 116, 116, 112, 115,  58,  47,  47,  39,  32,
      43,  32, 108, 111,  99,  97, 116, 105, 111, 110,  46, 104, 111, 115, 116,  32,
      43,  32,  39,  47, 109, 111, 109,  46, 104, 116, 109, 108,  39,  41,  59,  10,
       9,  60,  47, 115,  99, 114, 105, 112, 116,  62,  10,   9,  60,  47,  98, 111,
     100, 121,  62,  10,  60,  47, 104, 116, 109, 108,  62,  10,
    0 };

PUBLIC MprRomInode romFiles[] = {
    { "/rom/appweb.conf", _file_1, 384, 1 },
    { "/rom/web", 0, 0, 0 },
    { "/rom/web/index.html", _file_3, 860, 3 },
    { 0, 0, 0, 0 },
};

PUBLIC MprRomInode *mprGetRomFiles() {
    return romFiles;
}
#else
PUBLIC int romDummy;
#endif /* ME_ROM */

**Comment by embedthis** [comment]
Some items not in order:

* Trace is supported with ROM, we use it here. You must have trace to see what is the filename that is actually being served
* You can use -4 on the command line to direct errors and trace at level 4 to the console
* Instead of RequestTimeout 9223372036854775807, use units of hours, days etc.  e.g. 30days
* Be careful with such long timeouts. That is a denial of service risk.
* When fetching, you do not include /rom or /rom/web in the URL.
* You should not have an error.log problem if you are using "stdout" in your appweb.conf file. You may have the wrong appweb.conf in your rom file
*

**Comment by rks2003** [comment]
#1: e.g. from your config.c ("#if !ME_ROM") ==> you support traces, but no HTTP traces, if appweb was build with ME_ROM defined!:

#if !ME_ROM
/*
    TraceLog path|-
        [size=bytes]
...        
        [type="common|detail"]
 */
static int traceLogDirective(MaState *state, cchar *key, cchar *value)
{
    HttpRoute   *route;
    char        *format, *option, *ovalue, *tok, *path, *formatter;

---

#2: also for http traces? (see #1) ?

---

#3 & 4: OK, thanks!

---

#5, thats why I've defined '  Documents "/rom/web" ' in my appweb.conf, but I've tried such URL's to determine the problem!

---

#6: please check my appweb.conf, I've provided it in my previous post

only exchanged
   ErrorLog "stdout" size=1MB level=5 backup=0 anew
by
   ErrorLog error.log size=1MB level=5 backup=0 anew

**Comment by embedthis** [comment]
1.Thanks for the pickup on that TraceLog. We tend to use -4 in dev. We'll correct that. -4 will enable both log and trace to the console and override the appweb.conf TraceLog and ErrorLog values.

6. Appweb.conf looks okay, look at the src/server/rom.conf that we use.

**Comment by rks2003** [comment]
your rom.conf is almost the same regarding the relevant configurations...

**Comment by embedthis** [comment]
Checked in the fix for TraceLog.

**Comment by rks2003** [comment]
not sure whether this is one new thing I should test!

Of course, the traces could help you detemine the 
problems but I think they are really good reproducable
without traces from my side ! ?

But if you need more input - please tell!

As you may noticed I'm working on several construction 
sites!

br & nice we,
Ralf

**Comment by embedthis** [comment]
It works here. Sorry, without trace, we cannot help much.

We do:
```
git clone ....
cd appweb
./configure --rom
me
me rom
me
cd appweb/src
appweb --conf /rom/rom.conf -4

http http://localhost:4100/index.html
```
works fine here.

**Comment by rks2003** [comment]
OK, will have a try on tuesday afer a loooong weekend ;-)

**Comment by rks2003** [comment]
I've found some time to try again and after retrieving the latest dev-branch code I was able to access web pages from new ROM, e.g. accessing http://127.0.0.1/index.html.
But this is my next problem.
  httpAddRouteIndex(httpGetDefaultHost()->defaultRoute, "index.html");
or
  httpAddRouteIndex(httpGetDefaultHost()->defaultRoute, "/rom/web/index.html");
does not work if trying to acces http://127.0.0.1

[0062] 16:19:02.999       APPWEB: 16:19:02 1-0-2-1 connection.accept.new peer='127.0.0.1' endpoint='127.0.0.1:80'
[0063] 16:19:03.004       APPWEB: 16:19:03 1-0-3-1 connection.accept.new peer='127.0.0.1' endpoint='127.0.0.1:80'
[0064] 16:19:03.006       APPWEB: 16:19:03 1-0-3-1 rx.first.server method='GET' uri='/' protocol='HTTP/1.1'
[0065] 16:19:03.015       APPWEB: 16:19:03 1-0-3-1 rx.headers.server
[0066] +                          ----
[0067] +                          GET / HTTP/1.1
[0068] +                          Host: 127.0.0.1
[0069] +                          User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0
[0070] +                          Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
[0071] +                          Accept-Language: de,en-US;q=0.7,en;q=0.3
[0072] +                          Accept-Encoding: gzip, deflate
[0073] +                          Connection: keep-alive
[0074] +                          Pragma: no-cache
[0075] +                          Cache-Control: no-cache
[0076] +                          ----
[0077] 16:19:03.078       APPWEB: 16:19:03 1-0-3-1 request.error msg='Cannot find document'
[0078] 16:19:03.083       APPWEB: 16:19:03 1-0-3-1 request.pipeline route='' handler='passHandler' target='run' endpoint='0.0.0.0:80' host='default' referrer='' filename='\rom\web'
[0079] 16:19:03.088       APPWEB: 16:19:03 1-0-3-1 tx.headers.server
[0080] +                          ----
[0081] +                          HTTP/1.1 404 Not Found
[0082] +                          Vary: Accept-Encoding
[0083] +                          X-Frame-Options: SAMEORIGIN
[0084] +                          Content-Type: text/html
[0085] +                          X-Content-Type-Options: nosniff
[0086] +                          Date: Sun, 29 Nov 2015 15:19:03 GMT
[0087] +                          Cache-Control: no-cache
[0088] +                          Content-Length: 223
[0089] +                          X-XSS-Protection: 1; mode=block
[0090] +                          Connection: Keep-Alive
[0091] +                          Accept-Ranges: bytes
[0092] +                          ----
[0093] 16:19:03.159       APPWEB: 16:19:03 1-0-3-1 tx.body.data length=223
[0094] +                          ----
[0095] +                          <!DOCTYPE html>
[0096] +                          <head>
[0097] +                              <title>Not Found</title>
[0098] +                              <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
[0099] +                          </head>
[0100] +                          <body>
[0101] +                          <h2>Access Error: 404 -- Not Found</h2>
[0102] +                          <pre></pre>
[0103] +                          </body>
[0104] +                          </html>
[0105] +                          ----
[0106] 16:19:03.224       APPWEB: 16:19:03 1-0-3-1 request.completion status=404 error=1 connError=0 elapsed=219 elapsedTicks=468356 received=331 sent=521
[0107] 16:19:08.775       APPWEB: 16:19:08 1-0-2-1 connection.close msg='Connection reset'

**Comment by embedthis** [comment]
Did you have directory entries in the rom file table?

**Comment by rks2003** [comment]
yes:

PUBLIC MprRomInode romFiles[] = {
    { "\\rom", 0, 0, 0 },
    { "\\rom\\conf", 0, 0, 0 },
    { "\\rom\\conf\\server.conf", _file_3, 1201, 3 },
    { "\\rom\\cert", 0, 0, 0 },
    { "\\rom\\cert\\server.pem", _file_5, 3005, 5 },
    { "\\rom\\web\\index.html", _file_6, 860, 6 },
    { "\\rom\\web\\mom.html", _file_7, 57484, 7 },
    { "\\rom\\web\\eula.txt", _file_8, 44070, 8 },
    { "\\rom\\web\\css", 0, 0, 0 },
    { "\\rom\\web\\css\\mitel.css", _file_10, 16953, 10 },
...

**Comment by embedthis** [comment]
No,

you are missing

\rom\web

Without the directory, you cannot do HTTP directory indexes.

**Comment by rks2003** [comment]
Oops. Yes this helped! 
So now .conf, certificate and content from ROM is working (tested on Windows, on Linux I'll take a look tomorrow).
TY!

**Comment by rks2003** [comment]
Also happy with linux :)
