### ISSUE TITLE
Large file transmission slow

### ISSUE THREAD

**Issue by rks2003** [embedthis/appweb#560]
Appweb 6.1.0
CentOS 6.0

Using an SSL connection (OpenSSL) to retrieve an html page which links to large JavaScript-Files (Kendo UI) I've observed that this is extremly slow if the server is running on Linux (no problems if running on Windows).
By looking into a Wireshark trace I found out, that there is a delay of 100ms on the server side for each frame!
Using a grep in Appweb I found the definition MPR_TIMEOUT_GC_SYNC and put a trace call into the pauseThreads function. Result: Called often while requesting large files. So I've reduced the timeout to 1ms and the file transfer was speed up like on Windows. Now I'm not sure whether this is the correct solution.

br,
Ralf

**Comment by embedthis** [comment]
That routine should only ever block (timeout) if some thread is not yielding. As all threads are meant to be non-blocking, this should almost never happen.

Can you see what thread is blocked and not yielding and why?

Do you have a custom non-yielding thread?

**Comment by rks2003** [comment]
I've temporary added the following printf in PauseThreads, which always writes 'main' as thread name, so the thread was created in mprCreate (not custom).

    do {
        lock(ts->threads);
        allYielded = 1;
        for (i = 0; i < ts->threads->length; i++) {
            tp = (MprThread*) mprGetItem(ts->threads, i);
            if (!tp->yielded) {
printf("%s %lu\n", tp->name ? tp->name : "", tp->pid);
                allYielded = 0;
                break;
            }
        }

**Comment by embedthis** [comment]
The appweb.c should say:
```
    mprYield(MPR_YIELD_STICKY);
    while (!mprIsStopping()) {
        mprSuspendThread(-1);
    }
    mprResetYield();
```
This does a permanent yield of the main thread. Please check your appweb.c for this code. Also, your mprCreateThread should not have USER_THREAD specified:
```
    if ((mpr = mprCreate(argc, argv, 0)) == NULL) {
        exit(1);
    }
```

**Comment by rks2003** [comment]
1) Added mprYield(MPR_YIELD_STICKY); ==> no change
2) Removed MPR_USER_EVENTS_THREAD from mprCreate => multipe trace output:
   "warn mpr event => mprServiceEvents called reentrantly"
3) This happens in my application main thread after initializing/starting appweb (using tcp for communication with other non-mpr threads of the application for communication with Appweb, e.g. for sending changed data from other thread which should be notified via WebSocket to the Client):

  while (42) 
   {
      iRet = mprServiceEvents(0, MPR_SERVICE_NO_BLOCK);

      // Try to receive internal signal from other (not an mpr) thread via tcp
      sig = (AppwebSig_t*)dossReceiveSignalWithTimeoutZero(MOM_APPWEB_QUEUE);

      if ((iRet == 0) && (sig == NULL))
      {
         XtSleep(0, 10); // Pause only if seems to be idle (no internal and no Appweb events)
      }

      if (sig)
      {
         // Handle received signal
         appweb_rcv_mom(sig);

         // Free signal
         dossFreeSignal(sig);

         sig = NULL;
      }
   }

**Comment by embedthis** [comment]
This does not happen in the standard Appweb.c main program, so this is being caused in your custom main.

Why are you calling ServiceEvents manually?

Have a look at the standard src/server/appweb.c and see if you can model that code initialization.

**Comment by rks2003** [comment]
OK, this was an integration error I made! Sorry & thank you!
