### ISSUE TITLE
First command fails due to improper initialization of conn->lastActivity

### ISSUE THREAD

**Issue by raveendrapadala** [embedthis/appweb#570]
File Name: httpLib.c
Function Call Flow: httpCreateConn() -> httpSetState() -> httpAddConn()

*The parameter conn->lastActivity is assigned to http->now(conn->lastActivity = http->now;) in function httpCreateConn
*where as http->now is initialized as http->now = mprGetTicks(); in httpAddConn.
*Now the condition (http->now - conn->lastActivity) > limits->inactivityTimeout) is becoming true as a result httpTimer is aborting first command.

From second command onwards it's fine because it http->now is initialized properly in the httpAddConn.

someone can share their views on this to resolve this issue.

**Comment by embedthis** [comment]
http->now is set at initialization time in updateCurrentDate which is called when the server starts up from httpCreate.

```
static void updateCurrentDate()
{
    Http        *http;
    MprTicks    diff;

    http = HTTP;
    http->now = mprGetTicks();
```

**Comment by raveendrapadala** [comment]
As per our logs, for the first command the difference between http->now and  conn->lastActivity is greater than 60 seconds resulting in inactivity timeout being set.

appweb: 7: Call event AcceptConn
appweb: 4: SG:httpAcceptConn:Printing http->now. http->now:63049 
appweb: 4: SG:httpCreateConn:Setting http->now.``` http->now:63049 ```
appweb: 4: SG:httpCreateConn:Setting lastActivity. http->now:63049 ,``` conn->lastActivity:63049```
appweb: 4: SG:httpAddConn:Setting http->now. ```http->now:134937 ```
appweb: 4: SG:updateCurrentDate:Setting http->now. http->now:134937
appweb: 4: SG:```Setting Inactivity Timeout```. http->now:135938 , conn->lastActivity:63049, limits->inactivityTimeout:60000

This results in first command failing due to inactivity timeout. The solution we have tried  is moving the setting of conn->lastActivity to httpAddConn after http->now is set there.

**Is this solution acceptable or there is already some solution existing for this  issue.**

Please share your thoughts.

**Comment by embedthis** [comment]
What O/S and Appweb versions are you using?

mprGetTicks should return the elapsed milliseconds. You jumped from 63049 to 134937 which is > 60 seconds between the AcceptConn and the AddConn.

Can you check the code assigning http->host in AddConn and updateCurrentDate. Both should be setting http->now = mprGetTicks()

**Comment by raveendrapadala** [comment]
We are using appweb version 4.5.4. Yes the difference is greater than 60 seconds. This happens only for the first command after server starts, from second command its working fine.

I added some more logs in AcceptConn . I am just printing current http->now then setting it http->now = mprGetTicks() and printing again.
appweb: 4: SG:httpAcceptConn:Printing http->now. http->now:68718
appweb: 4: SG:httpAcceptConn:Setting http->now. http->now:148532
appweb: 4: SG:httpCreateConn:Setting http->now. http->now:148532
appweb: 4: SG:httpCreateConn:Setting lastActivity. http->now:148532 , conn->lastActivity:148532
appweb: 4: SG:httpAddConn:Setting http->now. http->now:148533
appweb: 4: SG:updateCurrentDate:Setting http->now. http->now:148533

It seems like http->now is holding some old/junk value before being set in AcceptConn. If its set directly in AddConn which is after lastactivity being already set in CreateConn, resulting in the inactivity time out being set.

I checked the code assigning http->host in AddConn and updateCurrentDate. Both are setting http->now = mprGetTicks().

**Comment by raveendrapadala** [comment]
Sorry, I meant assigning http->now in AddConn and updateCurrentDate.

**Comment by embedthis** [comment]
Ah .... we were assuming you were using the latest version. Please read:

[How to Submit an Issue](https://github.com/embedthis/appweb/issues/419)

It saves a lot of time if you fully describe your platform and issue. Can you breakpoint at GetTicks and step into it and see what is happening?  Pay attention to if you use the code HAS_MONOTONIC HAS_MONOTONIC_RAW or if you are using the "last chance" code.

**Comment by raveendrapadala** [comment]
We are using the code HAS_MONOTONIC_RAW.
