### ISSUE TITLE
TLS

### ISSUE THREAD

**Issue by moc32** [embedthis/appweb#573]
I am using appweb 4.3.3 in a production embedded server. I’d like to use secured connection (HTTPS). I saw on your website that appweb is shipped with MbedTLS but you didn’t specify any version for MbedTLS. Also I would like to know if the included TLS version supports TLSv1.2.
 
Thank you in advance for your help.

**Comment by embedthis** [comment]
Appweb 4.3 does not support mbedtls. Appweb 5 & 6 do.

We're currently integrating mbedTLS 2.1.2
