### ISSUE TITLE
Appweb Upgrading from 3.4.x to 6

### ISSUE THREAD

**Issue by akariblitz** [embedthis/appweb#577]
I'm trying to get the latest version of Appweb built, but I have not been successful yet.

I had a question regarding the 'configure'.  In Appweb 2 & 3 the './configure' had a page that listed out all the configuration options such as those can could be used for '--with' and '--enable'.  But I don't see much for MakeMe.  Our original build had many features disabled and a few enabled, which varied based on which platform we cross-compiled to.

Currently we have 3 platforms: ARM, PPC and MIPS with very limited space.  So how do I know which things can be disabled/enabled?  Is there a list of options that I can look at?

**Comment by embedthis** [comment]
configure --help

Use --with and --without

E.g.

```
configure --without cgi --without ssl
```

**Comment by akariblitz** [comment]
I understand that "--with" and "--without" has a could of features that it can be used for: such as ssl and sqlite.  But what about options that used to be used with '--enable'?  Is there is list of keywords that can be used?

Below is one of the configurations from 3.4.1:
`./configure --prefix= --bindir=/usr/sbin --libdir=/usr/lib --moddir=/usr/lib/modules \
--libexecdir=/usr/lib --localstatedir=/var/www/tc \
--webdir=/var/www/tc --host=powerpc-6xx-linux \
--enable-complete-cross --disable-complete-native --shared --enable-cgi \
--enable-auth --enable-auth-file --enable-digest-auth --enable-upload \
--disable-db --disable-doc --disable-e4x --disable-egi --disable-test \
--disable-angel --disable-xml --without-sqlite --without-ejs \
--with-openssl=../../openssl/0.9.8o`

Would you be able to provide the equivalent to this configuration?

**Comment by sensedeep-lums** [comment]
There is no --enable.

Configure supports --set to tailor features. --help lists these
```
    --set mpr.logging=value                # Set the session cache size (items)
    --set mpr.ssl.cache=value              # Enable application message logging
    --set mpr.ssl.logLevel=value           # Starting logging level for SSL messages
    --set mpr.ssl.ticket=value             # Enable session resumption via ticketing - client side session caching
    --set mpr.ssl.timeout=value            # Session and ticketing duration in seconds
    --set mbedtls.compact=value            # Build a compact edition of MbedTLS
    --set mbedtls.aesRomTables=value       # Put AES tables in rom
    --set mbedtls.arc4=value               # Enable/Disable ARC4 ciphers
    --set mbedtls.camellia=value           # Enable/Disable Camellia ciphers
    --set mbedtls.cbc=value                # Enable/Disable CBC ciphers
    --set mbedtls.ccm=value                # Enable/Disable CCM ciphers
    --set mbedtls.des=value                # Enable/Disable DES ciphers
    --set mbedtls.padlock=value            # Enable/Disable Padlock support
    --set mbedtls.psk=value                # Enable/Disable Pre-Shared Keys
    --set mbedtls.sslv2Hello=value         # Enable/Disable SSLv2 Hello
    --set mbedtls.xtea=value               # Enable/Disable XTEA
    --set rom=value                        # Build without a file system (true|false)
```
