### ISSUE TITLE
Interacting with External Services Threads

### ISSUE THREAD

**Issue by sudipmaiti1990** [embedthis/appweb#578]
Environment:
Appweb version: 6.2.1;  O/S: Ubuntu 15.04 ; CPU: intel 64 bit

Problem description:
if we want to use   httpwrite(q,"Name")  inside a non appweb thread , its not working.
How can we pass the connection value of "q=conn->writeq" in to the non appweb thread ?
what is the procedure to send data to client webpage from a non appweb thread (like - MQListener) using appweb server connection ?

**Comment by embedthis** [comment]
See this from the doc:

```
Appweb uses many APIs that are not thread-safe. This is because Appweb code runs on a serialized per-thread event dispatcher. If you call from a foreign non-MPR thread into Appweb, you will corrupt critical Appweb structures. Rather, use mprCreateEventOutside to schedule an event callback to run inside the MPR to run your code.
```

Net/Net: you cannot call Appweb APIs from a non-appweb thread. Rather, you should call your business logic APIs from the relevant Appweb handler.

See: https://embedthis.com/appweb/doc/ref/memory.html

**Comment by sudipmaiti1990** [comment]
Thanks very much!!
Now, it is working fine using `mprCreateEventOutside` .
But, after using this the server is responding very slowly.  Is there any way to solve this problem?

**Comment by embedthis** [comment]
Hard to say what is causing the slowness. You would need to diagnose.
