### ISSUE TITLE
how to maintain httpConn, for different thread...

### ISSUE THREAD

**Issue by pavikon** [embedthis/appweb#580]
Hi,
We are using action handler for handling requests from different Url. But when ever we need to respond back to client from different thread, we are not able to use the same instance of httpConn. 

We used both non mprthread and mprthread as well. 

Kindly help us in FIGRUNG this. 
Thanks in advance.

**Comment by embedthis** [comment]
The doc covers this at:

    https://embedthis.com/appweb/doc/ref/multithread.html
