### ISSUE TITLE
Run loadable module in in ARM target

### ISSUE THREAD

**Issue by manikandanhcl** [embedthis/appweb#585]
### Environment

1. O/S Version: 

           Linux

2. Appweb Version: 

           **6.2.1**

3. Hardware: 

           **ARM**

1.    command line for compilation of appweb:
            **./configure --platform linux-arm-debug --with compiler="/usr/bin/arm-linux-gnueabi-gcc"**     
         
 2.   comand for esp dynamic webpage compilation :
               **appweb-esp --platform linux-arm-debug compile**

### Problem Description:
              Can't run loadble module in target same as running in Host OS. How to run dynamic library in target .If not so how to compile and run static esp application in target as seen in one of your forum for embedded system

**Comment by embedthis** [comment]
There are two fixes for this in the next release of MakeMe.

* ./configure --set compiler.hasDynLoad=true is fixed
* Configure will automatically set the hasDynLoad option for the cross environment.

Workaround: edit the build/*/platform.me settings.compiler.hasDynLoad to true.
