### ISSUE TITLE
Dynamic application run in ARM target -Appweb-6.2.2

### ISSUE THREAD

**Issue by manikandanhcl** [embedthis/appweb#586]
### Environment

1. O/S Version: 

           **Linux**

2. Appweb Version: 

           **6.2.2**

3. Hardware: 

           **ARM**

### Problem Description:
        
                        Can't load dynamic shared esp application in ARM target with version 6.2.2.
    
 Log:
---------------       
root@zc702-zynq7:~/chroot-server# ./server
Security risk, /home/root/chroot-server is writeable by others
Security risk, /home/root/chroot-server/server is writeable by others
06/01/16 15:57:19 2 appweb, Configuration for Embedthis Appweb
06/01/16 15:57:19 2 appweb, ----------------------------------
06/01/16 15:57:19 2 appweb, Version:            6.2.2
06/01/16 15:57:19 2 appweb, BuildType:          Debug
06/01/16 15:57:19 2 appweb, CPU:                arm
06/01/16 15:57:19 2 appweb, OS:                 linux
06/01/16 15:57:19 2 appweb, Host:               zc702-zynq7
06/01/16 15:57:19 2 appweb, Configure:          me configure --platform linux-arm-debug --with compiler=/usr/bin/arm-linux-gnueabi-gcc
06/01/16 15:57:19 2 appweb, ----------------------------------
06/01/16 15:57:19 2 info http, Started HTTP service on 192.168.2.30:80
06/01/16 15:57:19 0 critical http, Cannot change ownership on null
06/01/16 15:57:19 2 info http, Running as user "nobody" (65534), group "nogroup" (65534)
06/01/16 15:59:21 0 error mpr, mprLoadModule: /home/root/chroot-server/web/test.esp failed
06/01/16 15:59:21 0 error mpr, Product built without the ability to load modules dynamically
06/01/16 16:00:49 4 info esp, Module /home/root/chroot-server/cache/view_291742081f3791bcbb83b460b800ff01.so has been externally updated, relo.
06/01/16 16:00:49 0 error mpr, mprLoadModule: /home/root/chroot-server/web/test.esp failed
06/01/16 16:00:49 0 error mpr, Product built without the ability to load modules dynamically

**Comment by embedthis** [comment]
Looks like you did not build with the ability to dynamically load modules.

You need the latest MakeMe 0.10.4 and to reconfigure. Then check your build/*/platform.me has settings.compiler.hasDynLoad set to true.

Then rebuild with:

    me -r -s

You should be linking -ldl.

**Comment by manikandanhcl** [comment]
I am using sample application provided by appweb example  in /samples/chroot-server.I am using direct command rather than  makeme to compile application.Still i can't load 

Changed  hasDynLoad: true in platform.me 


# command for  generate Server.bin : 
-------------------------------------------------------------
arm-linux-gnueabi-gcc -c -o server.o  -Wno-unused-result -Wall -g -fPIC -DME_DEBUG=1 -D_REENTRANT -DPIC "-I." "-I/usr/local/lib/appweb/6.2.2/inc"  server.c

arm-linux-gnueabi-gcc -o server -g -rdynamic -Wl,--enable-new-dtags -Wl,-rpath,$ORIGIN/ -Wl,-rpath,/home/hmi/Downloads/appweb-6.2.2/samples/arm/appweb-6.2.2/build/linux-arm-debug/bin/ -L. -L/home/hmi/Downloads/appweb-6.2.2/samples/arm/appweb-6.2.2/build/linux-arm-debug/bin/ "server.o" -lappweb -lhttp -lmpr -lpcre -lrt -ldl -lpthread -lm -lappweb -lhttp -lmpr -lpcre -lrt -ldl -lpthread -lm

# command to generate loadable module:
--------------------------------------------------------------
 arm-linux-gnueabi-gcc  -shared -g -Wall -Wno-unused-result -DPIC -fPIC -I. -Isrc -I/home/hmi/Downloads/appweb-6.2.2/samples/arm/chroot-server/linux-arm-debug/inc -L/home/hmi/Downloads/appweb-6.2.2/samples/arm/chroot-server/linux-arm-debug/bin -Wl,--enable-new-dtags -Wl,-rpath,$ORIGIN/    -o cache/view_291742081f3791bcbb83b460b800ff01.so cache/view_291742081f3791bcbb83b460b800ff01.c


Log:
--------------------------------
root@zc702-zynq7:/home/chroot-server# ./server
Security risk, /home/chroot-server is writeable by others
Security risk, /home/chroot-server/server is writeable by others
06/02/16 20:01:25 2 appweb, Configuration for Embedthis Appweb
06/02/16 20:01:25 2 appweb, ----------------------------------
06/02/16 20:01:25 2 appweb, Version:            6.2.2
06/02/16 20:01:25 2 appweb, BuildType:          Debug
06/02/16 20:01:25 2 appweb, CPU:                arm
06/02/16 20:01:25 2 appweb, OS:                 linux
06/02/16 20:01:25 2 appweb, Host:               zc702-zynq7
06/02/16 20:01:25 2 appweb, Configure:          me configure --platform linux-arm-debug --with compiler=/usr/bin/arm-linux-gnueabi-gcc
06/02/16 20:01:25 2 appweb, ----------------------------------
06/02/16 20:01:25 2 info http, Started HTTP service on 192.168.2.30:80
06/02/16 20:01:25 0 critical http, Cannot change ownership on null
06/02/16 20:01:25 2 info http, Running as user "nobody" (65534), group "nogroup" (65534)
06/02/16 20:01:37 0 error mpr, mprLoadModule: /home/chroot-server/web/test.esp failed
06/02/16 20:01:37 0 error mpr, Product built without the ability to load modules dynamically
06/02/16 20:01:47 4 info esp, Module /home/chroot-server/cache/view_291742081f3791bcbb83b460b800ff01.so has been externally updated, reloading.
06/02/16 20:01:47 0 error mpr, mprLoadModule: /home/chroot-server/web/test.esp failed
06/02/16 20:01:47 0 error mpr, Product built without the ability to load modules dynamically

**Comment by manikandanhcl** [comment]
I resolved the issues by moving gcc and makeme in target(ARM).

## output: 

root@zc702-zynq7:~/chroot-server# me run
       [Run] appweb-esp -q compile
       [Run] ./server
06/06/16 16:10:33 2 appweb, Configuration for Embedthis Appweb
06/06/16 16:10:33 2 appweb, ----------------------------------
06/06/16 16:10:33 2 appweb, Version:            6.2.2
06/06/16 16:10:33 2 appweb, BuildType:          Debug
06/06/16 16:10:33 2 appweb, CPU:                arm
06/06/16 16:10:33 2 appweb, OS:                 linux
06/06/16 16:10:33 2 appweb, Host:               zc702-zynq7
06/06/16 16:10:33 2 appweb, Configure:          me configure
06/06/16 16:10:33 2 appweb, ----------------------------------
06/06/16 16:10:33 2 info http, Started HTTP service on 192.168.2.30:80
06/06/16 16:10:33 2 info http, Started HTTPS service on 192.168.2.30:443
06/06/16 16:10:33 0 critical http, Cannot change ownership on null
06/06/16 16:10:33 2 info http, Running as user "nobody" (65534), group "nogroup" (65534)
