### ISSUE TITLE
Com[ilation of Appweb with sqlite

### ISSUE THREAD

**Issue by manikandanhcl** [embedthis/appweb#587]
## Environment

1. O/S Version: 

           **Linux**

2. Appweb Version: 

           **6.2.2**

3. Hardware: 

           **PC**

## Problem Description:
        
                       Not able to compile appweb with sqlite
    
##  Log:
---------------       
 ./configure --with sqlite  --without mdb

    [Configure] linux-x86-debug
    me: ERROR: Required component "sqlite" is not enabled: Cannot find definition for component: sqlite.me

**Comment by moc32** [comment]
`Hello manikandanhcl, you should first get sqlite package using the pak tool. Once you got sqlite package, you will be able to configure and build with sqlite`
`If you do not have the pak tool installed, you can get it directly from the embedthis repository`
pak install sqlite

**Comment by manikandanhcl** [comment]
### Hi moc32:

                   sqlite added to Appweb.Thanks for your help.
