### ISSUE TITLE
Flicker effect in ESP based webpage

### ISSUE THREAD

**Issue by manikandanhcl** [embedthis/appweb#589]
### Environment

1. O/S Version: 

       **Linux**

2. Appweb Version: 
       **6.2.2**

3. Hardware: 
       **ARM**

### Problem Description:

       our ESP page refresh is based on below syntax using HTLM5
                     <meta http-equiv=”refresh” content=”5" />

**Comment by embedthis** [comment]
That is to be expected. You are asking the browser to do a complete page refresh. Nothing to do with esp.

**Comment by manikandanhcl** [comment]
Understand that appweb supports server side(Standlaone ESP pages) and client side(Action handler) scripting method and ESP pages(C + HTML5) no need javascript which server embedded dynamic data in HTML5 to render in broswer . Sample application taken from samples/chroot_server/test.esp  

How to refesh test.esp page every one second .Do i need to write client side program for it.
