### ISSUE TITLE
Configure and Build For linux-arm-release

### ISSUE THREAD

**Issue by lmchin** [embedthis/appweb#590]
Hi everyone, 

I am trying to build with Appweb 6.2.2, however I got an error when try to build. Did I miss out something ?
### Environment
1. O/S Version: **Ubuntu 10.10**
2. Appweb Version: **6.2.2**
3. Hardware: **ARM**
### Build

./configure --platform linux-arm-release --prefix /mnt/appweb
### Problem Description:

Failed to build Appweb 6.2.2
### Log:

$ sudo ./configure --platform linux-arm-release --prefix /mnt/appweb
 [Configure] linux-x86-debug
     [Found] compiler: C/C++ Compiler: /usr/bin/gcc
     [Found] esp: Embedthis ESP, the amazingly fast C-Language web framework
     [Found] http: Embedthis Http Library
     [Found] lib: Library Archive Tool: /usr/bin/ar
     [Found] mbedtls: MbedTLS Support: src/mpr-mbedtls
     [Found] mdb: Embedthis MDB Database
     [Found] mpr: Embedthis Multithreaded Portable Runtime
     [Found] osdep: O/S Dependent Layer
     [Found] pcre: PCRE Library
     [Found] ssl: Secure Socket Layer Interface (MbedTLS Support)
     [Found] watchdog: Embedthis Watchdog: build/linux-x86-debug/bin/appman
    [Create] build/linux-x86-debug/platform.me
    [Create] build/linux-x86-debug/inc/me.h
 [Configure] linux-arm-release
     [Found] compiler: C/C++ Compiler: /usr/bin/gcc
     [Found] esp: Embedthis ESP, the amazingly fast C-Language web framework
     [Found] http: Embedthis Http Library
     [Found] lib: Library Archive Tool: /usr/bin/ar
     [Found] mbedtls: MbedTLS Support: src/mpr-mbedtls
     [Found] mdb: Embedthis MDB Database
     [Found] mpr: Embedthis Multithreaded Portable Runtime
     [Found] osdep: O/S Dependent Layer
     [Found] pcre: PCRE Library
     [Found] ssl: Secure Socket Layer Interface (MbedTLS Support)
     [Found] watchdog: Embedthis Watchdog: build/linux-arm-release/bin/appman
    [Create] build/linux-arm-release/platform.me
    [Create] build/linux-arm-release/inc/me.h
    [Create] start.me
      [Info] Type "me" to build.
ysj265@linux-tt:~/arm/code/appweb-6.2.2$ sudo me
     [Build] linux-x86-debug
      [Copy] build/linux-x86-debug/inc/osdep.h
      [Copy] build/linux-x86-debug/inc/mbedtls.h
   [Compile] build/linux-x86-debug/obj/mbedtls.o
   [Archive] build/linux-x86-debug/bin/libmbedtls.a
      [Copy] build/linux-x86-debug/inc/mpr.h
   [Compile] build/linux-x86-debug/obj/mpr-mbedtls.o
   [Archive] build/linux-x86-debug/bin/libmpr-mbedtls.a
   [Compile] build/linux-x86-debug/obj/mprLib.o
      [Link] build/linux-x86-debug/bin/libmpr.so
   [Compile] build/linux-x86-debug/obj/pcre.o
      [Link] build/linux-x86-debug/bin/libpcre.so
      [Copy] build/linux-x86-debug/inc/http.h
   [Compile] build/linux-x86-debug/obj/httpLib.o
      [Link] build/linux-x86-debug/bin/libhttp.so
      [Copy] build/linux-x86-debug/inc/mpr-version.h
   [Compile] build/linux-x86-debug/obj/mpr-version.o
   [Archive] build/linux-x86-debug/bin/libmpr-version.a
      [Copy] build/linux-x86-debug/inc/esp.h
   [Compile] build/linux-x86-debug/obj/espLib.o
      [Link] build/linux-x86-debug/bin/libesp.so
      [Copy] build/linux-x86-debug/inc/appweb.h
   [Compile] build/linux-x86-debug/obj/config.o
   [Compile] build/linux-x86-debug/obj/convenience.o
   [Compile] build/linux-x86-debug/obj/rom.o
   [Compile] build/linux-x86-debug/obj/cgiHandler.o
   [Compile] build/linux-x86-debug/obj/espHandler.o
      [Link] build/linux-x86-debug/bin/libappweb.so
   [Compile] build/linux-x86-debug/obj/appweb.o
      [Link] build/linux-x86-debug/bin/appweb
   [Compile] build/linux-x86-debug/obj/authpass.o
      [Link] build/linux-x86-debug/bin/authpass
   [Compile] build/linux-x86-debug/obj/esp.o
      [Link] build/linux-x86-debug/bin/appweb-esp
      [Copy] extras => build/linux-x86-debug/bin
   [Compile] build/linux-x86-debug/obj/http.o
      [Link] build/linux-x86-debug/bin/http
      [Copy] install-certs => build/linux-x86-debug/bin
   [Compile] build/linux-x86-debug/obj/makerom.o
      [Link] build/linux-x86-debug/bin/makerom
   [Compile] build/linux-x86-debug/obj/watchdog.o
      [Link] build/linux-x86-debug/bin/appman
  [Complete] all
     [Build] linux-arm-release
      [Copy] build/linux-arm-release/inc/osdep.h
      [Copy] build/linux-arm-release/inc/mbedtls.h
   [Compile] build/linux-arm-release/obj/mbedtls.o
me: ERROR: Building target /home/ysj265/arm/code/appweb-6.2.2/build/linux-arm-release/obj/mbedtls.o

Command failure: cc1: error: unrecognized command line option "-mno-sched-prolog"

**Comment by sensedeep** [comment]
What version of GCC are you using?

**Comment by embedthis** [comment]
You can edit mno-sched-prolog out of the generated build/*/platform.me file.

**Comment by lmchin** [comment]
Do you mean remove the line mno-sched-prolog  in the platform.me file? 

gcc version 4.4.5 (Ubuntu/Linaro 4.4.4-14ubuntu5)

Previously I am using this Environment to Build AppWeb 3.3.2
