### ISSUE TITLE
AJAX support in ESP

### ISSUE THREAD

**Issue by manikandanhcl** [embedthis/appweb#592]
### Environment

```
O/S Version:

Linux

Appweb Version:
6.2.2

Hardware:
ARM
```
### Problem Description:

I have an HTML page with 5 sections.  I would like to refresh data in one of the sections without reloading other sections of the HTML page.  How do we go about it?  Does ESP support AJAX?

**Comment by mobrien** [comment]
Yes.

Ajax is a client side tech. When you request data from a browser using Ajax, you can connect that to an ESP method which will respond to data without a page refresh.
