### ISSUE TITLE
Accessing SQL Lite or ESP Memory Database using EDI  API

### ISSUE THREAD

**Issue by karthirv** [embedthis/appweb#593]
### Need sample for EDI Native API- database connectivity and access.

Need some sample for accessing database using SQL Lite and ESP Memory Database (MDB).
### Environment
1. O/S Version:  Linux or Windows 7
2. Appweb Version: 6.2.2
3. Hardware: 
### Problem Description:

Need to know the how to utilize the EDI Native API for connecting SQLLite or ESP Memory Database (MDB).

Regards
V. Karthikeyan

**Comment by mobrien** [comment]
See: https://github.com/embedthis/esp/tree/dev/samples/login-database
