### ISSUE TITLE
Updated DHKEY 1024->2048, Performance decreased by 3 times during SSL handshake (time_appconnect) 

### ISSUE THREAD

**Issue by raveendrapadala** [embedthis/appweb#595]
### Environment
1. O/S Version: Linux
2. Appweb Version: 4.5.4.
3. Hardware: Proprietary
### Problem Description:

Patched Appweb 4.5.4 with attached patch to increase the DH Key from 1024 to 2048 but the performance decreased by 4 times during handshake.i.e., 0.675sec to 2.307sec.

Data is collected using curl command with time_appconnect.Data taken over 100 samples doing handshake every time.

curl command Details:
for i in {1..100};do curl -s -w "@curlconffile" -k https://<IP Address>/redfish/v1; done
curlconffile content:
\n
            time_namelookup:  %{time_namelookup}\n
            time_connect:     %{time_connect}\n
            time_appconnect:  %{time_appconnect}\n
            time_pretransfer: %{time_pretransfer}\n
                            ----------\n
                 time_total:  %{time_total}\n
\n
## 

<img width="721" alt="time_appconnect_timing_graph" src="https://cloud.githubusercontent.com/assets/6459140/17839403/51e5674e-6804-11e6-944a-a73bcd5c1cbf.PNG">
[AppwebDefect.xlsx](https://github.com/embedthis/appweb/files/429042/AppwebDefect.xlsx)

Few More details:
we are using near latest version of open ssl i.e., version detail: openssl 1.0.2g -fips.
Patch:

[appweb_4.5.4_CVE_2015_4011.txt](https://github.com/embedthis/appweb/files/429043/appweb_4.5.4_CVE_2015_4011.txt)

```
```

**Comment by embedthis** [comment]
That is to be expected on a modest CPU. The time is spent totally in OpenSSL and the time to compute the keys is (unfortunately) exponential.

If your CPU is not powerful enough, and you don't have hardware SSL acceleration, then you may need to reduce the key size.

Note: that when using the web server over https from a browser, keep-alive will reuse a connection many times per handshake.

**Comment by raveendrapadala** [comment]
so nothing much can be done apart from reuse the connection. Ok. Any other thoughts?

**Comment by mobrien** [comment]
You can design your pages to eliminate parallel requests. i.e. fetch graphics, style sheets etc asynchronously from code and in series. Then you may be able to get away with just one socket connection.
