### ISSUE TITLE
HTTP compression support in Appweb

### ISSUE THREAD

**Issue by manikandanhcl** [embedthis/appweb#597]
Environment:

O/S Version:
       VxWorks- 7

Appweb Version:
       6.2.2

Hardware:
       ARM

Question:

Appweb have any supports for HTTP compression or Is it possible to add  3rd partycompression library  intergrate with Appweb.

**Comment by mobrien** [comment]
You can gzip your files at dev time and Appweb will then serve those instead of the plain versions.

See:

https://embedthis.com/appweb/doc/users/dir/route.html#map
