### ISSUE TITLE
My events thread probabilistic is dead-lock??

### ISSUE THREAD

**Issue by zhaoqingtao-hik** [embedthis/appweb#598]
### Issue Submission Template

Please follow this template when submitting each and every issue. Issues without these details will be marked as "Incomplete" and will not get attention. Make sure you use:
- Use markdown to format. Format code with three back ticks. Look at the source of this issue to see how it is done. 
- Edit down any logs. Please do not t just dump large unedited logs. Only post the relevant portions.
- Use the MakeMe **http** command in preference to a browser to trigger the issue. It is more controllable.
- Wherever possible, create an isolated test case, separate from your application to demonstrate the issue. This helps the team to recreate your issue.
- Include these details on ALL issues.
### Environment
1. O/S Version: linux-3.4.35
2. Appweb Version: 3.2.3
3. Hardware: cortex-A7
### Problem Description:

When the device is to very quickly respond to event's thread，there will be a serious problem. The problem is that I cann't log in the device, when I capture package, I find a RST package. And the recv-Q is not zero always. Nothing I can do that.  At last I find the events thread is dead-locked, but I do not know why this thing is happened. 

My email: 312204643@qq.com

**Comment by zhaoqingtao-hik** [comment]
For example, I use this events thread write and read the NAS very frequently？？？

**Comment by mobrien** [comment]
Can you please provide more details. 

You say "capture package". What is a package and what is capture?  These are not terms that Appweb uses.

Appweb reads from sockets, so how are you getting a RST packet?  These are not ready by Appweb. Rather they are interpreted as a close event. 

You say the events threat is "dead-locked".  How have you determined it is dead locked.

Sorry I cannot help, but I don't understand what you are describing.
