### ISSUE TITLE
Cannot upload files (Client supplied insufficient upload data)

### ISSUE THREAD

**Issue by Nivswisa** [embedthis/appweb#601]
### Environment

1. O/S Version: VxWorks (for Intel(R) ATOM(TM) Luna Pier Platform (MoonCreek)) version 6.8.
Kernel: WIND version 2.13.

2. Appweb Version: 7.0.1

### Build
```
Configuration for Embedthis WebSvr
----------------------------------
Version:            7.0.1
BuildType:          Debug
CPU:                x86
OS:                 vxworks
Host:               EMU
Configure:          me -d -q -platform vxworks-x86-static -static -configure . -gen make
----------------------------------
Started HTTP service on *:80
```

### Problem Description:

Pre Description: 
Using your example in (test/web/upload/upload.html), and creating new directory inside root.

The Problem:
First when was trying to upload file i got this msg:
```
---------------------------------------------------------------------------------
-> 00:00:47 1-0-5-6 rx.first.server method='POST' uri='/uploadFile' protocol='HTTP/1.1'
00:00:47 1-1-5-6 request.error msg='Cannot find document'
00:00:47 1-1-5-6 request.completion status=404 error=1 connError=0 elapsed=717 received=749 sent=521
---------------------------------------------------------------------------------
```
Than I figured out that maybe the path is problematic so I added new directory after the URI name (uploadFile) and i got this msg:
```
---------------------------------------------------------------------------------
00:01:10 1-0-5-7 rx.first.server method='POST' uri='/uploadFile' protocol='HTTP/1.1'
00:01:10 1-1-5-7 request.error msg='Client supplied insufficient upload data'
00:01:10 1-1-5-7 request.completion status=400 error=1 connError=0 elapsed=917 received=749 sent=586
---------------------------------------------------------------------------------
```
Seems that incomingUpload function get an empty packet content somehow.

***I have also add my .conf files, screenshot from wireshark and a suitable file for it (.pcapng) 
that might be helpful to understand the issue.

[uploadFileIssue.zip](https://github.com/embedthis/appweb/files/1449224/uploadFileIssue.zip)

Thank You for your time,
Niv.

**Comment by mobrien** [comment]
That test relies on the Ejscript javascript framework. It is not intended for use outside of the unit tests.
