### ISSUE TITLE
Setgid() function unsuccessful.

### ISSUE THREAD

**Issue by sunxinyu** [embedthis/appweb#606]
###Environment

1. O/S Version: linux  3.3.0+

2. Appweb Version:  7.0.1

3. Hardware:  armv5tejl

### Build

####Configure command line:

`**CC=arm-none-linux-gnueabi-gcc CFLAGS=-w ./configure --debug --platform linux-arm-debug**`

> ./appweb -v --home ./ --config ../web/appweb.conf
> Configuration for Embedthis Appweb                                              
> ----------------------------------                                              
> Version:            7.0.1                                                       
> BuildType:          Debug                                                       
> CPU:                arm                                                         
> OS:                 linux                                                       
> Host:               linux                                                      
> Configure:          me configure --debug --platform linux-arm-debug             
> ----------------------------------                                              
> Started HTTP service on *:80                                                    
> Started HTTPS service on *:443   

### Problem Description:
I enter the ip address in the browser, the browser page has been loaded, can not display the default page. Only root user, When I comment out the code in the **httpApplicationUserGroup** function in the source file **httpLib.c**:
```
/*
if (httpApplyChangedGroup () <0 || httpApplyChangedUser () <0) {
         return MPR_ERR_CANT_COMPLETE;
     }
*/
```
> ./appweb -v --home ./ --config ../web/appweb.conf
> Configuration for Embedthis Appweb                                              
> ----------------------------------                                              
> Version:            7.0.1                                                       
> BuildType:          Debug                                                       
> CPU:                arm                                                         
> OS:                 linux                                                       
> Host:               er9000                                                      
> Configure:          me configure --debug --platform linux-arm-debug             
> ----------------------------------                                              
> Started HTTP service on *:80                                                    
> Started HTTPS service on *:443                                                  
> **Running as user "nobody" (65534), group "nogroup" (65534)** 

Added a row of information：**Running as user "nobody" (65534), group "nogroup" (65534)** ，I found that the **setgid(http->gid)** function did not return, stopped there.
At this time I can open the default page in the browser and output the content：
...

> 01:56:16 1-0-1-1 rx.first.server method='GET' uri='/' protocol='HTTP/1.1'       
> 01:56:16 1-0-1-1 request.completion status=200 error=0 connError=0 elapsed=100 2
> 01:56:17 1-0-1-2 rx.first.server method='GET' uri='/screen.css' protocol='HTTP/'
> 01:56:17 1-0-1-2 request.completion status=200 error=0 connError=0 elapsed=579 7
> 01:56:17 1-0-1-3 rx.first.server method='GET' uri='/images/shadow.jpg' protocol'
> 01:56:17 1-0-1-3 request.completion status=200 error=0 connError=0 elapsed=616 4
> 01:56:17 1-0-1-4 rx.first.server method='GET' uri='/images/bottomShadow.jpg' pr'
> 01:56:17 1-0-1-4 request.completion status=200 error=0 connError=0 elapsed=698 0
> 01:56:17 1-0-1-5 rx.first.server method='GET' uri='/images/banner.jpg' protocol'
> 01:56:17 1-0-1-5 request.completion status=200 error=0 connError=0 elapsed=792 2

...
This proves that this is a correct request, right?
Will **setgid(http->gid)** function does not continue to run down what may be the reasons? I want to understand this problem, thank you.

**Comment by mobrien** [comment]
The setgid function should not hang. It is a low level syscall. You must have something serious wrong with your system configuration. I'd check the system logs and see if you can create a simple test program that uses setgid.

setgid is used to change the user account and/or group from the GroupAccount and UserAccount directives in the appweb.conf.

These directives improve security by running Appweb at a lower level of privilege. For testing, you can omit those directives in the appweb.conf.
