### ISSUE TITLE
‘’appweb/samples/simple-module/” issue

### ISSUE THREAD

**Issue by Smartbenz** [embedthis/appweb#618]
I cant run this samples.
errors: 
davis@laptop9273:~/workstation/appweb-7.0.3/samples/simple-module$ sudo me run
      [Run] appweb
      me: ERROR: Error with target: run
      Command failure: Cannot load module libmod_simple.so, reason: "libmod_simple.so: cannot open                               
      shared object file: No such file or directory"
      Cannot load module libmod_simple.so, reason: "libmod_simple.so: cannot open shared object file: 
      No such file or directory"
      Error with directive "LoadModule". At line 12 in appweb.conf '''

**Comment by mobrien** [comment]
Tested here and works.

Did you build the module?  Is the module file present in your directory?

**Comment by Smartbenz** [comment]
Yes，I have used command `me` to build the this module. But, when I use command 'me run', it  report an error like this.

**Comment by Ting87** [comment]
Hi @Smartbenz 
Have you solved issue?
