### ISSUE TITLE
configure Appweb as reverse proxy

### ISSUE THREAD

**Issue by raveendrapadala** [embedthis/appweb#620]
### Environment

1. O/S Version: Linux 3.10

2. Appweb Version: 4.5.4 (patched with security & memory leak patches of latest versions)

3. Hardware: Proprietary

### Problem Description:
Can i configure appweb as both a webserver and as a reverse proxy(also-known-as a "gateway" server.) for another server like apache? 
If yes,

- In which version this is supported because i am using old version 4.5.4?
- Do we have instructions anywhere. kindly share them

From the appweb [documentation](https://www.embedthis.com/appweb/doc/ref/architecture.html), i understand appweb can be configured as backend server but not reverse proxy server. Please confirm.
> Proxied
> Appweb is an ideal application web server when running behind a reverse proxy. The reverse proxy dispatches incoming requests to a set of Appweb instances which can effectively host ESP, or PHP applications.

**Comment by mobrien** [comment]
There is no built-in reverse proxy capability.

You could create one as a handler using the Appweb APIs.
