### ISSUE TITLE
How can I disable "PUT" and "DELETE" method?

### ISSUE THREAD

**Issue by allenhu12** [embedthis/appweb#621]
### Environment

1. O/S Version: Linux kernel 3.14.43

2. Appweb Version: appweb-3.4.2

3. Hardware: arm platform

### Problem Description:

It seems that the APPWEB default support "PUT" and "DELETE" risky method, can we disable these two method?

```
nmap -p 443 --script http-methods <IP>                                                                          
	
	Starting Nmap 7.01 ( https://nmap.org ) at 2018-09-13 11:12 CST
	Nmap scan report for <IP>
	Host is up (0.00062s latency).
	PORT    STATE SERVICE
	443/tcp open  https
	| http-methods: 
	|   Supported Methods: OPTIONS GET HEAD POST PUT DELETE
	|_  Potentially risky methods: PUT DELETE
```

**Comment by allenhu12** [comment]
> Appweb 7 does not enable by default and must be enabled via:
> 
> ```
> Methods add DELETE PUT OPTIONS
> ```
> Please don't use Appweb 3 as it is over 10 years old. Appweb 3 is not supported and new security fixes are not applied to Appweb 3.

hi, mobrien
Thank you for responding. We are using Appweb 3 in a legacy device we don't have plan to replace it :(. So according to you, is it possible to disable "DELETE" and "PUT" in Appweb 3?

**Comment by dev-embedthis** [comment]
See: https://www.embedthis.com/appweb/doc-3/guide/appweb/users/dir/location.html#putMethod

This will control both the PUT and DELETE methods.
