### ISSUE TITLE
Appweb cpu consumption is very high during file upload

### ISSUE THREAD

**Issue by venkyvxl** [embedthis/appweb#623]
Environment:

1. O/S Version:  Linux 3.16

2. Appweb Version: 4.5.4 (patched with security & memory leak patches of latest version)

3. Hardware: Proprietary

Problem Description:
  During file uploads, cpu consumption of appweb is staying between 70~80% which is very high
  Please anyone guide me , to see why its consuming so much of cpu and how to reduce this number.
  
Attached is the appweb cpu consumption graph:

[AppwebCpuConsumption_GitHub.xlsx](https://github.com/embedthis/appweb/files/2511472/AppwebCpuConsumption_GitHub.xlsx)

**Comment by venkyvxl** [comment]
pls can I get any update on this?

**Comment by mobrien** [comment]
Do you see the same CPU load with a currently supported version, Appweb 7?  

Also, for security, folks shouldn't click on embedded XLSX/DOCX documents. Better to post a JPG.

Regarding your issue, not sure why Appweb 4 would use a lot of CPU for you. I'd recommend you test with Appweb 7 and see if that solves the issue and consider upgrading to Appweb 7.

Thanks.

**Comment by venkyvxl** [comment]
Hi mobrien, 
Thanks for response. 
With Appweb7, I am yet to test. 
With Appweb 4, its consistent behavior of over cpu consumption. So, I am trying to get any pointers to resolve/rootcause this issue.

**Comment by dev-embedthis** [comment]
If the network is very fast, a high CPU usage may not be abnormal. Are you testing locally or over a slow network?

If locally, you would expect the browser and Appweb to consume all available CPU. So 70% could be totally normal. The file should upload very quickly.

Can you give more details:
- Size of the file
- Time taken for the upload
- Are you using SSL
- What is your CPU architecture and speed
- O/S

**Comment by dev-embedthis** [comment]
I'm closing for now, but feel free to reopen if you get extra info.
