### ISSUE TITLE
Cannot find module "libmod_ssl"

### ISSUE THREAD

**Issue by venkyvxl** [embedthis/appweb#628]
Environment:

O/S Version: Linux 3.16

Appweb Version: 7.0.3

Hardware: Proprietary

Problem Description:
As posted in #623 and suggestion by @mobrien , I upgraded the appweb to 7.0.3, built and flashed the image. Flashing is successful and system boots properly. But GUI is not working. So, by looking at appweb logs, i am getting the below error:
01/10/19 21:14:08 0 error mpr, Cannot find module "libmod_ssl", cwd: "/usr/local/etc/appweb", search path "/usr/local/bin:/usr/local/bin:/usr/local/lib/appweb/7.0.3/bin"

Even though I couldnt find libmod_ssl.so file in any of the directory mentioned above as well in whole linux OS which is flashed into system, but curious to know, how appweb 4.5.4 is generating this in /usr/local/lib folder.

**Comment by venkyvxl** [comment]
To give more info about above issue, I tried to change the config flags from
BIT_MPR_LOGGING=1 \  BIT_MPR_TRACING=1 \  BIT_MAX_LOGLINE=1024 \  BIT_PACK_CGI=1 \
BIT_PACK_DIR=1 \   BIT_PACK_OPENSSL=1 \   SHOW=1 
to            
ME_MPR_LOGGING=1 \   ME_MPR_TRACING=1 \  ME_MAX_LOGLINE=1024 \  ME_COM_CGI=1 \ ME_COM_DIR=1 \   ME_COM_OPENSSL=1 \   SHOW=1
But this change results in build failure. Getting below error:
gcc/sh4-linux/4.7.2/ld: cannot find -lmpr-version

Pls let me know, how to resolve this build error or how to generate libmod_ssl as specified in description.

**Comment by mobsense** [comment]
Recommend you use the Appweb 7 makefiles rather than trying to port your makefiles. mpr-version needs to be built which the Appweb 7 makefiles will build.

**Comment by venkyvxl** [comment]
In 4.5.4 , we were configuring compiler option BIT_COM_ESP=0 . But this needs to changed to ME_COM_ESP=1 and this results in building mpr-version and goes further for successful code build..
