### ISSUE TITLE
Appweb version 4.5.4 : "Inactive connection timed out" error observed within inactivityTimeout

### ISSUE THREAD

**Issue by sankar2078** [embedthis/appweb#629]
Environment:

O/S Version: Linux 3.16

Appweb Version: 4.5.4

Hardware: Proprietary

Problem Description:
I am using Appweb version 4.5.4. 
we have configured inactivityTimeout as 60sec.
When we run winrm commands, "Inactive connection timed out" error observed within inactivityTimeout.
this error observed between receiving header and body content from the client. the logs are mentioned below. 

**appweb: 6: httpProtocol: IO, state 5, error 0
appweb: 6: filterPacket: read 0 bytes, useful 0, remaining 198, more 0**
appweb: 5: Inactive connection timed out
appweb: 5:   State 5, uri /wsman
appweb: 2: Error: Request exceeded inactivity timeout of 60 sec
appweb: 6: httpIOEvent for fd 12, mask 6
appweb: 6: http: readEvent read socket 198 bytes
appweb: 6: httpProtocol: IO, state 5, error 1

Actually here, appweb throwing error without waiting for 60 sec.

But when i tried to send only header using curl, i could see **sessionTimeoutMonitor** logs after below line.
**appweb: 6: filterPacket: read 0 bytes, useful 0, remaining 198, more 0**

**Example:**
appweb: 6: httpProtocol: IO, state 5, error 0
**appweb: 6: filterPacket: read 0 bytes, useful 0, remaining 198, more 0**
appweb: 5: sessionTimeoutMonitor:586::=======> iterating through sessionMap,sessionentries [0]
appweb: 5: sessionTimeoutMonitor:704::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor_rf:239::=======> iterating through sessionXAuthMap_rf,sessionentries [0]
appweb: 5: sessionTimeoutMonitor_rf:305::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor:586::=======> iterating through sessionMap,sessionentries [0]
appweb: 5: sessionTimeoutMonitor:704::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor_rf:239::=======> iterating through sessionXAuthMap_rf,sessionentries [0]
appweb: 5: sessionTimeoutMonitor_rf:305::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor:586::=======> iterating through sessionMap,sessionentries [0]
appweb: 5: sessionTimeoutMonitor:704::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor_rf:239::=======> iterating through sessionXAuthMap_rf,sessionentries [0]
appweb: 5: sessionTimeoutMonitor_rf:305::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor:586::=======> iterating through sessionMap,sessionentries [0]
appweb: 5: sessionTimeoutMonitor:704::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor_rf:239::=======> iterating through sessionXAuthMap_rf,sessionentries [0]
appweb: 5: sessionTimeoutMonitor_rf:305::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor:586::=======> iterating through sessionMap,sessionentries [0]
appweb: 5: sessionTimeoutMonitor:704::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor_rf:239::=======> iterating through sessionXAuthMap_rf,sessionentries [0]
appweb: 5: sessionTimeoutMonitor_rf:305::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor:586::=======> iterating through sessionMap,sessionentries [0]
appweb: 5: sessionTimeoutMonitor:704::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor_rf:239::=======> iterating through sessionXAuthMap_rf,sessionentries [0]
appweb: 5: sessionTimeoutMonitor_rf:305::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor:586::=======> iterating through sessionMap,sessionentries [0]
appweb: 5: sessionTimeoutMonitor:704::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor_rf:239::=======> iterating through sessionXAuthMap_rf,sessionentries [0]
appweb: 5: sessionTimeoutMonitor_rf:305::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor:586::=======> iterating through sessionMap,sessionentries [0]
appweb: 5: sessionTimeoutMonitor:704::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor_rf:239::=======> iterating through sessionXAuthMap_rf,sessionentries [0]
appweb: 5: sessionTimeoutMonitor_rf:305::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor:586::=======> iterating through sessionMap,sessionentries [0]
appweb: 5: sessionTimeoutMonitor:704::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor_rf:239::=======> iterating through sessionXAuthMap_rf,sessionentries [0]
appweb: 5: sessionTimeoutMonitor_rf:305::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor:586::=======> iterating through sessionMap,sessionentries [0]
appweb: 5: sessionTimeoutMonitor:704::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor_rf:239::=======> iterating through sessionXAuthMap_rf,sessionentries [0]
appweb: 5: sessionTimeoutMonitor_rf:305::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor:586::=======> iterating through sessionMap,sessionentries [0]
appweb: 5: sessionTimeoutMonitor:704::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor_rf:239::=======> iterating through sessionXAuthMap_rf,sessionentries [0]
appweb: 5: sessionTimeoutMonitor_rf:305::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor:586::=======> iterating through sessionMap,sessionentries [0]
appweb: 5: sessionTimeoutMonitor:704::<======= sleeping [5] seconds
appweb: 5: sessionTimeoutMonitor_rf:239::=======> iterating through sessionXAuthMap_rf,sessionentries [0]
appweb: 5: sessionTimeoutMonitor_rf:305::<======= sleeping [5] seconds
appweb: 5: Inactive connection timed out
appweb: 5:   State 5, uri /wsman
appweb: 2: Error: Request exceeded inactivity timeout of 60 sec
appweb: 6: httpIOEvent for fd 12, mask 4
appweb: 6: httpProtocol: IO, state 5, error 1
appweb: 6: filterPacket: read 0 bytes, useful 0, remaining 198, more 0

I have verified appweb - 7.1.0 code, but i did not see any difference in code. can some one help me in fixing this issue/give us some pointers to proceed further on this.

**Comment by mobsense** [comment]
There is a separate timeout between HTTP headers and receipt of the body called the RequestParseTimeout.

See: https://www.embedthis.com/appweb/doc/users/dir/route.html#requestParseTimeout
