### ISSUE TITLE
Unable to serve html files in 7.0.3. 

### ISSUE THREAD

**Issue by venkyvxl** [embedthis/appweb#630]
Environment:

O/S Version: Linux 3.16

Appweb Version: 7.0.3

Hardware: Proprietary

Problem Description:
As posted in #628, I upgraded from 4.5.4 to 7.0.3 and changed all the relevant config directives in appweb.conf file which were changed from old 4.5.4 to 7.0.3. Configured Documents directive to system directory where our zipped html files present and added Map compressed directive to serve zipped files . Once this is done and when I run curl command to get html file, appweb returning 404, Not found error even though file is present. I tried with multiple accept headers , Accept encoding and accept-language options but result is still the same. 
For Ex: command curl -vk -H "Accept-Encoding: gzip, deflate, br" 'https://{ip}/test.html' gives 200OK in 4.5.4 but 404 in 7.0.3. 
Please let me know, how to resolve this. 
PS: While debugging root cause for this, I am seeing default appweb file handler is not getting executed to serve the file even though it is configured in conf file with directive Addhandler fileHandler.

**Comment by mobsense** [comment]
Please see https://github.com/embedthis/appweb/issues/419 and add log file data and other items recommended in this outline.

**Comment by venkyvxl** [comment]
As mentioned by @mobsense , below are the additional details:
1. Appweb is built from source with compiler flags: ME_MPR_LOGGING=1 \ ME_MPR_TRACING=1 \ ME_MAX_LOGLINE=1024 \ ME_COM_CGI=1 \ ME_COM_DIR=1 \ ME_COM_OPENSSL=1 \ SHOW=1

2. Issuing request: curl -vk -H "Accept-Encoding: gzip, deflate, br" 'https://{ip}/test.html'  or 
                              curl -vk  'https://{ip}/test.html'
    Data returned: 
       Access Error: 404 -- Not Found

3. HTTP Headers:
   Accept=*/* 
   Accept-Encoding=gzip, deflate, br
   User-Agent=curl/7.29.0
   Host={IP}

4. Logs: 
  > GET /start.html HTTP/1.1
> User-Agent: curl/7.29.0
> Host: {IP}
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Vary: Accept-Encoding
< Content-Type: text/html
< Date: Tue, 29 Jan 2019 03:13:32 GMT
< Cache-Control: no-cache
< Content-Length: 223
< Connection: Keep-Alive
< Accept-Ranges: bytes
<
<!DOCTYPE html>
<head>
    <title>Not Found</title>
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
</head>
<body>
<h2>Access Error: 404 -- Not Found</h2>
<pre></pre>
</body>
</html>
* Connection #0 to host {IP} left intact

PS: 1. Documents directive is correctly pointing to directory where test.html is present.  And this is working perfectly in 4.5.4 
      2. This is seen when appweb upgraded from 4.5.4 to 7.0.3 and by making relevant changes in appweb.conf file.

**Comment by mobsense** [comment]
Sounds like your appweb.conf isn't setup correctly for Appweb 7.

Try testing with a pure Appweb 7 using appweb.conf from the 7 release rather than porting your old appweb.conf. That should isolate the issue. Please post what it is because it is nice to correct upgrade issues to make it easier for all.

**Comment by venkyvxl** [comment]
This is resolved by changing code in our proprietary code.. In 4.5.4, all handlers were returning void, but in 7.0.3, openhandler returns int with value 0 as success scenario.. Changed return value of our openhandlers to return 0 and its working fine..
