### ISSUE TITLE
Setting UploadDir produces Internal Server Error

### ISSUE THREAD

**Issue by pacman1990** [embedthis/appweb#631]
### Environment

1. O/S Version: Embedded Linux (4.4.6)

2. Appweb Version: 6.2.3

3. Hardware:  Embedded Linux

### Build

1. If built from source, what was your configure command line:

```
----------------------------------
Version:            6.2.3
BuildType:          Debug
CPU:                mips
OS:                 linux
Host:               awplus
Configure:          me -d -q -platform linux-x86-default -configure . -gen make
----------------------------------
```

### Problem Description:

When uploading a file with a multipart form request, an internal server error is returned with the following message:
```
Cannot create upload temp file null. Check upload temp dir flash
```
The UploadDir directive is set to /flash, but the same error is produced when UploadDir is set to any directory (e.g. /tmp, /var). When UploadDir is not explicitly set in the configuration file, appweb sets the default upload directory internally to /tmp and files can be uploaded without error. 

appweb is invoked with:
```
appweb --home /mnt/gui --config /etc/appweb/appweb.conf
```
The appweb.conf file:
 ```
set LOG_DIR "/var/log/appweb"
set CACHE_DIR "/var/spool/appweb/cache"
Redirect secure
SSLCipherSuite "ALL"
SSLProtocol +TLSv1.1 +TLSv1.2
SSLCertificateFile "/var/www/ssl/self.crt"
SSLCertificateKeyFile "/var/www/ssl/self.key"
AuthStore system
LoadModule cmsgProxyHandler libmod_cmsgProxy
CmsgProxyInit
LoadModule apteryxHandler libmod_apteryx
LoadModule apiLogger libmod_apiLogger
ApteryxSchema /etc/apteryx/schema/apteryx.xsd
ApteryxSchemaPath /etc/apteryx/schema
LoadModule shellHandler libmod_shell
ErrorLog error.log size=10KB level=2 backup=5
TraceLog trace.log level=4 
AddHandler fileHandler gif jpeg jpg png pdf ico css js txt html
LimitKeepAlive 50
InactivityTimeout 30mins
SessionTimeout 30mins
RequestTimeout 10mins
CrossOrigin origin=null credentials=yes headers=Authorization
ErrorDocument 401 /unauth

<VirtualHost *:80 *:443>
        Listen 80
        ListenSecure 443
        Include /etc/appweb/ba.conf
</VirtualHost>
```
The ba.conf file contains the following route for the file upload API:

```
<Route ^/api/v1/fs/upload$>
    Prefix /api
    Methods set POST
    SetHandler cmsgProxyHandler
    AddOutputFilter apiLogger
    AuthType basic AlliedwarePlus
    SessionCookie disable
    Header set Cache-Control   "no-store"
    LimitRequestBody 100mb
    LimitUpload 100mb
    AddInputFilter uploadFilter
    UploadDir /flash
    UploadAutoDelete on
    ShowErrors              on
</Route>
```

## Trace log
```
20:20:27 1-0-6-1 connection.accept.new peer='192.168.1.1' endpoint='192.168.1.2:443'
20:20:27 1-0-6-1 connection.ssl msg='Connection secured without peer certificate' secure=true cipher='ECDHE-RSA-AES256-GCM-SHA384' session='85DC3D18690EB2C3671298163638FD85FE77F4A1D1A4A4AC708061934DF6860B'
20:20:27 1-0-6-1 rx.first.server method='POST' uri='/api/v1/fs/upload' protocol='HTTP/1.1'
20:20:27 1-0-6-1 rx.headers.server
----
POST /api/v1/fs/upload HTTP/1.1
Host: 192.168.1.2
Authorization: Basic bWFuYWdlcjpmcmllbmQ=
User-Agent: curl/7.58.0
Accept: */*
Content-Length: 48769847
Content-Type: multipart/form-data; boundary=------------------------944093ba3dfe4b68
Expect: 100-continue
----
```
## Curl response

```
> POST /api/v1/fs/upload HTTP/1.1
> Host: 192.168.1.2
> Authorization: Basic bWFuYWdlcjpmcmllbmQ=
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 48769847
> Content-Type: multipart/form-data; boundary=------------------------944093ba3dfe4b68
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 500 Internal Server Error
< Access-Control-Allow-Credentials: true
< Vary: Accept-Encoding
< X-Frame-Options: SAMEORIGIN
< Content-Type: text/html
< X-Content-Type-Options: nosniff
< Date: Sun, 03 Feb 2019 20:20:27 GMT
< Cache-Control: no-store
< Content-Length: 311
< X-XSS-Protection: 1; mode=block
< Access-Control-Allow-Origin: *
< Connection: Keep-Alive
< Access-Control-Allow-Headers: Authorization
< Accept-Ranges: bytes
* HTTP error before end of send, stop sending
< 
<!DOCTYPE html>
<head>
    <title>Internal Server Error</title>
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
</head>
<body>
<h2>Access Error: 500 -- Internal Server Error</h2>
<pre>Cannot create upload temp file null. Check upload temp dir flash</pre>
</body>
</html>
```

**Comment by venkyvxl** [comment]
Hi @pacman1990 , hope you resolved your issue by now.. If not, pls find below the possible root cause and work around..  Even though I didnt check 6.2.3 code repo, but I am guessing the root cause.
In new appweb versions post 4.5.4(current repo which I have), they are setting uploadDir to relative path of Home directive you configured. instead of path you directly configured in conf file. This results in non creation of uploaddir file and results in failure.. Pls check what is the uploadDir value during upload operation and you can see how to resolve this..

**Comment by mobsense** [comment]
Clarification: if the path in the config file is absolute, it will be used. If relative, it is relative to the server Home directory. So 

UploadDir /flash

Should result in upload dir being set to /flash.

The code for this is in route.c in function httpSetDir.

**Comment by venkyvxl** [comment]
Hi @mobsense , No. this is not the case.. In 7.1.0,  I did try with with absolute path in confing file, but its taking path relative to Home directory.. 
In httpLib.c:13953,  UPLOAD is passed to httpSetDir for setting UPLOAD_DIR key and in httpSetDir  , we do calling an api mprGetRelPath to get relative path w.r.t. Home directory.. 
If we see below logs from api httpSetDir when I configured UploadDir to /mnt/test in config file, we can see 

log1: 15605:: 02/11/19 22:34:07 0 info http name = UPLOAD value = /mnt/test curDir = /usr/local/bin
log2: 15609:: 02/11/19 22:34:07 0 info http, name = UPLOAD value = /mnt/test path = /mnt/test
log3: 15610:: 02/11/19 22:34:07 0 info http, name = UPLOAD value = /mnt/test path = /mnt/test home = /usr/local/bin
log4: 15617:: 02/11/19 22:34:07 0 info http, name = UPLOAD value = /mnt/test path = /mnt/test home = /usr/local/bin
log5:15618::  02/11/19 22:34:07 0 info http, name = UPLOAD value = /mnt/test path = /mnt/test home = /usr/local/bin rpath = ../../../mnt/test

rpath being relative path and  in httpSetRouteVar @ line no:15617, we are setting this variable(rpath)to UPLOAD_DIR directive..

**Comment by mobsense** [comment]
It is converting the abs path to a relative path for use internally. But the abs path and relative path are equivalent. The directory must exist. It is not created.

**Comment by pacman1990** [comment]
Hi there, I produced similiar results to @venkyvxl when starting appweb from a range of different home directories. 

For example, when UploadDir = /flash, and appweb is started with --home /mnt/gui, the relative path set inside httpSetDir = flash. This then produces an error as /mnt/gui/flash does not exist. 

I found if I removed the call to mprGetRelPath in httpSetDir and just used the variable "path" instead, this fixed the issue. However, I wasn't sure what effect this would have on the rest of appweb.

I realised that if I set the Home directive explicitly to /mnt/gui inside the Route in the .conf file, this fixed the issue. So we are using this as a work around for now, but it isn't ideal, as someone may want to start appweb with a different  --home option from the command line.

**Comment by venkyvxl** [comment]
@pacman1990 , thanks for confirming the behaviour.
@mobsense , directory does exist, but consider a scenario where I changed the current working directory of appweb by running a script which invokes the appweb..
Ex: In script, I did cd /usr/local/etc/webserver/appweb and configured home directory as /usr/local/bin in config file. Then with relative to home directory, rpath is created as ../../../mnt/test and set to UPLOAD_DIR, but when appweb tries to access that file being in /usr/local/etc/webserver/appweb during file uplod,  it says file inaccessible and returns Internal server error.
PS: I just listed one scenario where cwd may change and file accessibility becomes failure, but i see this as prone to many issues facing be users.

**Comment by mobsense** [comment]
The Appweb HOME directory must be the CWD.

You can invoke appweb via

    appweb --home /path

If you set HOME (by default it is set to "."), you must be in that directory.

So when you change directory to /usr/local/etc/webserver/appweb, you must set Home to this also. Note: this is the directory where appweb.conf should be.

You should thus not be setting Home to /usr/local/bin.

This is the cause of the issue. Appweb assumes it is running in /usr/local/bin and thus ../../../mnt/test would be a correct path to the upload directory. But you are not, in fact, in that directory.

**Comment by venkyvxl** [comment]
@mobsense , what you mentioned is correct.. Keep cwd and home directory same. But I still feel that, storing upload dir as relative path is source of confusion..
