### ISSUE TITLE
Limiting the number of events that can be queued

### ISSUE THREAD

**Issue by bernieh-atlnz** [embedthis/appweb#632]
Hi there, we're trying to implement a file download mechanism using Appweb (the built in file handler didn't fit our needs). Currently we schedule an event using the connection's dispatcher, something like:

```
static void
_StreamResponseSend(stream_response_data *data, MprEvent *event)
{
    HttpConn *conn = data->connection;

    httpWriteBlock(conn->writeq, data->data, data->length, HTTP_BUFFER);
    httpFlushQueue(conn->writeq, 0);

    free_stream_response_data(data);
}

void StreamResponseSend(stream_response_data *data)
{
    HttpConn *conn = data->connection;

    mprCreateEvent(conn->dispatcher, "StreamResponseSend", 0,
                   _StreamResponseSend, data, MPR_EVENT_STATIC_DATA);
}
```

A non-MPR thread passes chunks of the file to StreamResponseSend(). Our problem is that we need to limit the rate at which we call StreamResponseSend() so that Appweb doesn't run out of memory when sending a large file.

The only solution we can think of currently is to make the send operation block, by calling:

```
httpFlushQueue(conn->writeq, HTTP_BLOCK);
```

and to only allow one event to be scheduled at a time by checking whether a send event is currently being handled:

```
bool StreamConnBusy (void *connection)
{
    HttpConn *conn = (HttpConn *) connection;
    return mprGetEventCount (conn->dispatcher) > 0;
}
```

Is there a better way of achieving something like this?

**Comment by mobsense** [comment]
Please read: Appweb Multithreaded Programming:
    https://www.embedthis.com/appweb/doc/ref/multithread.html
and the WebSockets sample
    https://github.com/embedthis/appweb/tree/dev/samples/websockets-chat

You cannot safely access Appweb data structures from a non-appweb thread. i.e. you cannot do:

 HttpConn *conn = data->connection;

in a NON-Appweb thread. 

See the web sockets chat sample for how to do this safely.

**Comment by bernieh-atlnz** [comment]
Sorry I should have mentioned that we call httpBorrowConn() on the connection so that we can keep a pointer to it from a non-appweb thread. In my example, stream_response_data is just a custom structure for holding a pointer to a connection and the data that we want to send.

So from the websockets example, it seems that the solution would be to use an HttpNotifier and only allow additional chunks to be sent once we get an HTTP_EVENT_WRITABLE event?

**Comment by mobsense** [comment]
Yes, using HTTP_EVENT_WRITABLE is one way. As a non-blocking, non-polling solution is best.

Another way is to examine the queue counts q->count vs q->max and limiting your writes to not overflow the queues.

**Comment by dev-embedthis** [comment]
We're adding to version 7.1 and 8.X a new API called httpCreateEvent which you can use to invoke callbacks from foreign threads. It means you don't need to use borrow conn.
