### ISSUE TITLE
Appweb not responding to HTTP_EXPECT_CONTINUE request in sendContinue api

### ISSUE THREAD

**Issue by venkyvxl** [embedthis/appweb#633]
Environment:

O/S Version: Linux 3.16

Appweb Version: 7.0.3

Hardware: Proprietary

Problem Description:
I am running an POST request from client which responds with "Expect: 100-continue" to wait for further data. In this meantime, appweb tries to send '100 Continue' message via sendContinue api by checking HTTP_EXPECT_CONTINUE flag in response.. Once appweb calls sendContinue, its not flushing the '100 Continue' message. 

----
```
With **sendContinue api which is posted below**:

static int sendContinue(HttpConn *conn)
{
    cchar      *response;
    int         mode;
    assert(conn);
    if (!conn->tx->finalized && !conn->tx->bytesWritten) {
        response = sfmt("%s 100 Continue\r\n\r\n", conn->protocol);
        mprLog("info http session", 2, "TEST1");
        mode = mprGetSocketBlockingMode(conn->sock);
        mprLog("info http session", 2, "TEST2");
        mprWriteSocket(conn->sock, response, slen(response));
        mprLog("info http session", 2, "TEST3");
        mprSetSocketBlockingMode(conn->sock, mode);
        mprLog("info http session", 2, "TEST4");
        mprFlushSocket(conn->sock);
        mprLog("info http session", 2, "TEST5");
    }
    return 0;
}
```
 **and tracelog with level 4:**
17:31:12 4-0-50-1 rx.headers.server
POST /test HTTP/1.1
Authorization: Basic cm9vdDpjYWx2aW4=
Accept: */*
Connection: Keep-Alive
Content-Type: application/soap+xml;charset=UTF-8
User-Agent: Microsoft WinRM Client
Content-Length: 1593
Host: 172.24.3.190
Expect: 100-continue

 **In mprSetSocketBlockingMode called from sendContinue**, 
able to see socket flag is setting to O_NONBLOCK by executing 
fcntl(sp->fd, F_SETFL, fcntl(sp->fd, F_GETFL) | O_NONBLOCK); line, then unlocking sp and returning to mprFlushSocket to get execute

**Appweb config directive flags:**
ME_EJS_DB=0 ME_EJS_DB=0 ME_EJS_MAIL=0 ME_EJS_MAPPER=0 ME_EJS_TAR=0 ME_EJS_TEMPLATE=0 
ME_EJS_WEB=0 ME_EJS_ZLIB=0 ME_ESP_MDB=0 ME_ESP_SDB=0 ME_MPR_LOGGING=1 ME_MPR_TRACING=1
ME_MAX_LOGLINE=1024 ME_COM_CGI=1 ME_COM_DIR=1 ME_COM_EJSCRIPT=0 ME_COM_ESP=1 \
ME_COM_EST=0 ME_COM_MOCANA=0 ME_COM_MATRIXSSL=0 ME_COM_OPENSSL=1 ME_COM_PHP=0 \
ME_COM_SQLITE=0 ME_DEBUG=0 ME_ROM=0 DEBUG=0 SHOW=1

**MprSocketProvider structure details:**
 sp->provider->name  printing as "mbedtls" and flushSocket address is NULL..

----

With all the description and observation detailed above, I can see logs till TEST4 and then appweb  gets crashed and core is getting generated. Please anyone let me know, why flushSocket is getting NULL address .

PS:  1. I ran POST with small amount of payload where HTTP_EXPECT_CONTINUE is not enabled, then appweb 7.0.3 works fine and POST operation gets executed successfully.
       2. In appweb 4.5.4, with large response payload,I ran the same scenario as mentioned in description and its working fine. mprFlushSocket is flushing the data immeditately and then client responds with response with status code 200OK.
     3. Content-length of response when appweb 7.0.3 is working fine is 1115.  And when its crashing, content-lenght of response is 2352.
     4. Bycomparing MprSocketProvider members in 4.5.4 and 7.0.3, I can see sp->provider->name in  as "mbedtls" and flushSocket address is NULL in 7.0.3.. And in 4.5.4, name is showing as "openssl" and flushSocket is pointing to valid address. 
5. I not enabled MBEDTLS in 7.0.3. config params as mentioned in config directive list provided above.

**Comment by mobsense** [comment]
Can you provide a stack backtrace with variable values?

**Comment by venkyvxl** [comment]
@mobsense ,  By default, SendContinue socket is taking mbedtls protocol and resulting in null reference to flush socket even though opsnssl is enabled by force with option ME_COM_OPENSSL=1 . So I tried to disable mbedtls with option ME_COM_MBEDTLS=0 and build, but getting build errors. 
So, as a result, I upgraded appweb version to 7.1.0 and disabling mbedtls with option ME_COM_MBEDTLS=0 is working fine.. This in turn resluts in picking openssl socket in sendContinue and hence issue got resolved.
