### ISSUE TITLE
appweb8.0 debug version HTTP2

### ISSUE THREAD

**Issue by chenxin20084809** [embedthis/appweb#634]
### Environment

1. O/S Version: Linux 3.6

2. Appweb Version: 8.0.0 debug version

3. Hardware: ARM

4. Curl version
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.0.1 zlib/1.2.3.4 nghttp2/1.35.1
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 

### Build

1. If built from source, what was your configure command line:

#define ME_HTTP_HTTP2           1

My appweb.conf file:
Listen 80
ListenSecure 443

AddHandler isapiHandler
<Route /ISAPI/>
   SetHandler isapiHandler
   Allow from all
</Route>

AddHandler sdkHandler
<Route /SDK/>
  SetHandler sdkHandler
  Allow from all
</Route>

AddHandler fileHandler

SSLCertificateFile      "/davinci/servcert.pem"
SSLCertificateKeyFile   "/davinci/servkey.pem"
SSLCipherSuite			"HIGH:MEDIUM:!RC4:!ADH:!3DES"
SSLProtocol				TLSv1 TLSv1.1 TLSv1.2

Documents "/home/webLib"
DirectoryIndex index.asp

LimitWorkers 20

### Problem Description:
Two problems were found when integrating appweb 8.0.0 with HTTP2.
1. Using curl to send HTTP2 requests to appweb on port 80, we found that after appweb parsed to upgrade, we did not send 101 switch to upgrade the protocol, but chose HTTP1.1 to communicate directly.
Moreover, the code reading found that the "upgrade" header was parsed in the processHeaders interface, but it was only used in the upgrade of websocket protocol, but not applied to HTTP2 protocol upgrade.

Like this:
* Expire in 0 ms for 6 (transfer 0x21d2ac0)
*   Trying 10.17.114.251...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x21d2ac0)
* Connected to 10.17.114.251 (10.17.114.251) port 80 (#0)
> GET / HTTP/1.1
> Host: 10.17.114.251
> User-Agent: curl/7.64.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
> 
< HTTP/1.1 200 OK
< Vary: Accept-Encoding
< X-Frame-Options: SAMEORIGIN
< Content-Type: text/html
< X-Content-Type-Options: nosniff
< Date: Fri, 15 Feb 2019 15:40:34 GMT
< ETag: 1550248033
< Content-Length: 480
< X-XSS-Protection: 1; mode=block
< Last-Modified: Wed, 05 Sep 2018 09:38:32 GMT
< Connection: close
< Accept-Ranges: bytes
< 
<!doctype html>
<html>
<head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" >
        <meta http-equiv="Pragma" content="no-cache" />
        <meta http-equiv="Cache-Control" content="no-cache, must-revalidate" />
        <meta http-equiv="Expires" content="0" />
</head>
<body>
</body>
<script>
        window.location.href = "/doc/page/login.asp?_" + (new Date()).getTime();
</script>
* Closing connection 0

Run Appweb with trace on to capture headers like this:
16:39:15 RECV event=http.rx.headers type=request method:'GET', uri:'/', protocol:'1'
16:39:15 RECV event=pipeline type=context route:'', handler:'fileHandler', target:'run', endpoint:':80', host:'default', referrer:'', filename:'/home/webLib/index.asp'
16:39:15 RECV event=http.completion type=result status:200, error:0, elapsed:19, received:0, sent:480

**Comment by dev-embedthis** [comment]
We support HTTP/2 over TLS using ALPN negotiation. This is the approach all browsers are using. i.e. we support h2c and not h2.

Curl should use ALPN negotiation.
