### ISSUE TITLE
Stale http->now and conn->lastActivity

### ISSUE THREAD

**Issue by sankar2078** [embedthis/appweb#635]
1. O/S Version: Linux 3.16

2. Appweb Version: 7.1.0

3. Hardware: Proprietary

Description of query:
when there is a new connection, **httpCreateConn** will be called and conn->lastActivity initialized with old HTTP->now.
conn->lastActivity = HTTP->now;
Then HTTP->now will be initialized with mprGetTicks in httpAddConn.
http->now = mprGetTicks();

Because of this some times httpTimer getting triggered as inactivity timeout when there is a more than 30 (inactivitytimeout=30) between requests.
else if ((http->now - conn->lastActivity) > limits->inactivityTimeout) {
                conn->timeout = HTTP_INACTIVITY_TIMEOUT;
                abort = 1;
            } 

1. Why are we not updating http->now with mprGetTicks before updating the lastActivity with http->now?
2. Is there any reason for this?
3. Do we see any issues if we update the http->now with mprGetTicks in **httpCreateConn**.
Please clarify my query.

**Comment by mobsense** [comment]
The httpTimer updates http->now every second, so it should never be more than 1 second late.

We don't update the time on each connection as if you are doing thousands of connections per second, it is a bit of overhead we can eliminate.

**Comment by sankar2078** [comment]
By enabling logs my observation is 
1. http->now is getting updated for every 1 sec when the request is there. but when appweb is idle http->now is not getting updated and resulting in very old time assigned to lastactivity.
2. It is getting updated in httpAddConn which called from **httpCreateConn**, thats means for every connection it is getting initialized.

**Comment by mobsense** [comment]
Yes, you are right.

When there are no requests, appweb does not update the time ... there is no need to. But after a long period of idle, as you say, lastActivity could be set to a stale value.

http->now is updated for each connection but not for each keep-alive request. So you can have 1000s of requests per connection. 

So setting the time at the start of the new connection would seem to be a solution as you point out.

**Comment by mobsense** [comment]
BTW: The slowness is not mprGetTicks, but updateCurrentDate which calculates the HTTP date header.

**Comment by sankar2078** [comment]
Thank you for the response. so adding http->now initialization in httpCreateConn will not make any issue right? do you see any side effects?.
If no side effects, will do the change in our current code.

**Comment by mobsense** [comment]
Correct. You can set http->now = mprGetTicks at any time without any ill effects.

**Comment by sankar2078** [comment]
Ok Thank you. I am doing the changes and closing this thread.

**Comment by sankar2078** [comment]
Can you please notify me when the fix available in your code branch.
