### ISSUE TITLE
appweb-4.5.4: ECDHE ciphers support patch needed

### ISSUE THREAD

**Issue by sankar2078** [embedthis/appweb#636]
### Environment

1. O/S Version: Linux 3.16

2. Appweb Version: 4.5.4

3. Hardware: Proprietary 

Description:
Currently we are using appweb-4.5.4 and we have applied some selective patches till appweb-7.1.0.
When we are checking for the supported ciphers ECDHE is missing in appweb-4.5.4. where as we have another system which is enabled with appweb-7.1.0 supporting ECDHE ciphers.
Upgrading 4.5.4 to 7.1.0 will be huge change for us. Can you please tell me which patch can help us to fix  the issue with appweb-4.5.4.

**Comment by dev-embedthis** [comment]
There is no patch for that. 

Elliptic curves were not in OpenSSL when Appweb 4 was released around 2007.

Upgrading to version 7 should not be a huge update.
