### ISSUE TITLE
code bug in httplib.c

### ISSUE THREAD

**Issue by Jeff-Kook** [embedthis/appweb#637]
I am not sure if I use it in right way...

My request header:
`Accept-Language: zh-CN,zh;q=0.9,en;q=0.8`

My conf file:
```
<Route /documents >
	Prefix /documents
	DefaultLanguage zh
	AddLanguageDir zh chinese-docs
	AddLanguageDir en english-docs
</Route>
```

The page is access the html in english-docs dir.
Debug code, I found some problem:
[Parser Code](https://github.com/embedthis/appweb/blob/master/src/http/httpLib.c#L17679)
Seem this line should be:
`language = stok(tok, ";", &quality);`
and this line should be
`language = stok(tok, ";q=", &quality);`

and the another problem:
[Compare function Code](https://github.com/embedthis/appweb/blob/master/src/http/httpLib.c#L17656)
`return scmp(*s1, *s2);`
and this line can be:
`return scmp(*s2, *s1);`

Finally, the q-factor weighting is working.

**Comment by dev-embedthis** [comment]
Thanks. Good pickup on this.

Not sure if the header will never have spaces after ";". i.e.

Is this legal:

;  q=10
;q=10

If so, then the parser should handle both.
