### ISSUE TITLE
Appweb not supporting TLS1.1 and TLS1.2 protocol

### ISSUE THREAD

**Issue by venkyvxl** [embedthis/appweb#638]
Environment:

O/S Version: Linux 3.16

Appweb Version: 7.1.0

Hardware: Proprietary

**Problem Description:**
When I configure my system hosting appweb server to TLS protocol 1.1 or 1.2, appweb is not able to communicate with clients. But its working fine when its configured for TLS1.0.

**Appweb build flags used:**
ME_MAX_LOGLINE=1024 ME_COM_CGI=1 ME_COM_DIR=1 ME_COM_EJSCRIPT=0
ME_COM_ESP=1 ME_COM_EST=0 ME_COM_MOCANA=0 ME_COM_MATRIXSSL=0
**ME_COM_MBEDTLS=0 ME_COM_OPENSSL=1** ME_COM_PHP=0 ME_COM_SQLITE=0 
ME_DEBUG=0 ME_ROM=0 DEBUG=0 SHOW=1

**Test command ran:**
openssl s_client -connect {ip}:443 -cipher 'RSA'

**Command o/p:**
CONNECTED(00000003)
139813781829536:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
no peer certificate available
No client certificate CA names sent
SSL handshake has read 0 bytes and written 129 bytes
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1551437094
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

**Appweb log error:**
02/28/19 04:06:49 5 info mpr ssl openssl, SSL_read error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
02/28/19 04:06:49 5 info mpr ssl openssl, SSL_read error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
02/28/19 04:06:49 5 info mpr ssl openssl, SSL_read error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol

**TraceLog o/p**
/tmp # tail -f trace.log
19:37:22 1-0-1-1 connection.accept.new peer='{ip}' endpoint='{ip}:443'
19:37:22 1-0-1-1 connection.close msg='error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol'

**CipherSuite used:**
 SSLCipherSuite ALL:!ADH:!EXPORT56:!RC4:!IDEA:!CBC:!3DES:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP:+eNULL.

Also tried with cipher suite given in sample appweb.conf file, but getting the same error.

**SSLProtocol string configured**:
SSLProtocol  ALL -SSLV2 -SSLV3 -TLSV1

**Appweb build flags used:**
ME_MAX_LOGLINE=1024  ME_COM_CGI=1  ME_COM_DIR=1 ME_COM_EJSCRIPT=0 
 ME_COM_ESP=1  ME_COM_EST=0  ME_COM_MOCANA=0  ME_COM_MATRIXSSL=0 
 **ME_COM_MBEDTLS=0  ME_COM_OPENSSL=1**  ME_COM_PHP=0 ME_COM_SQLITE=0 \
 ME_DEBUG=0  ME_ROM=0  DEBUG=0  SHOW=1

**PS:** 
1. Above openssl command works fine  only when system in TLS1.0 protocol and GUI also comes with with TLS1.0
2. Checked with appweb version 4.5.4, same cipher suite is working fine for all tls 1.0, 1.1 and 1.2 protocols.
3. Also curious to know, why sample appweb.conf file (https://github.com/embedthis/appweb/blob/master/src/server/sample.conf)  does **'NOT'** contain SSLProtocol directive example.

Please let me know, how to resolve this major security issue..

**Comment by sankar2078** [comment]
@mobsense  We are using appweb-7.1.0 with Linux 3.16 and proprietary hardware. When we try to enable TLSv1.1 or TLSv1.2 only, by default TLSv1.0 is enabled and we are not able to disable TLSv1.0.
Is there any way to disable TLSv1.0?

**Comment by dev-embedthis** [comment]
The default is:
