### ISSUE TITLE
Appweb allowing tls1.0 protocol when set for tls1.1 or tls1.2 only

### ISSUE THREAD

**Issue by venkyvxl** [embedthis/appweb#639]
Environment:

O/S Version: Linux 3.16

Appweb Version: 7.1.0

Hardware: Proprietary

Appweb build flags used:
ME_MAX_LOGLINE=1024 ME_COM_CGI=1 ME_COM_DIR=1 ME_COM_EJSCRIPT=0
ME_COM_ESP=1 ME_COM_EST=0 ME_COM_MOCANA=0 ME_COM_MATRIXSSL=0
**ME_COM_MBEDTLS=0 ME_COM_OPENSSL=1** ME_COM_PHP=0 ME_COM_SQLITE=0
ME_DEBUG=0 ME_ROM=0 DEBUG=0 SHOW=1

Problem Description:
I am configuring appweb to allow tls protocol of version 1.1 and higher  or 1.2 only.. But tls scan results  in both the cases shows, 1.0 is always getting allowed. This seems to be a **major security issue**.. 

**Case 1:**
    **Scenario**: TLS1.2 only
    **SSLProtocol directive**: all -sslv2 -sslv3 -tlsv1.0 -tlsv1.1 +tlsv1.2
    **Testssl tool's scan result**:   
     SSLv2      not offered (OK).
     SSLv3      not offered (OK).
     **TLS 1      offered**.
     **TLS 1.1    not offered.**
     **TLS 1.2    offered (OK)**.
     TLS 1.3    not offered.
     NPN/SPDY   not offered.

   **SSLScan tool's scan result**: 
           TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384  
           TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384 
           TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA 
           TLSv1.2  256 bits  DHE-RSA-AES256-GCM-SHA384 
           **TLSv1.0  256 bits  ECDHE-RSA-AES256-SHA**
           **TLSv1.0  256 bits  DHE-RSA-AES256-SHA**

**Case 2:**
    **Scenario**: TLS1.1 or higher
    **SSLProtocol directive**: all -sslv2 -sslv3 -tlsv1.0 +tlsv1.1 +tlsv1.2
    **Testssl tool's scan result**:  
     SSLv2      not offered (OK).
     SSLv3      not offered (OK).
     **TLS 1      offered**.
     **TLS 1.1    offered**.
     **TLS 1.2    offered (OK)**.
     TLS 1.3    not offered.
     NPN/SPDY   not offered.

**SSLScan tool's scan result**:    
     TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384  
     TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384 
     TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA 
     TLSv1.2  256 bits  DHE-RSA-AES256-GCM-SHA384 
     TLSv1.1  256 bits  ECDHE-RSA-AES256-SHA
     TLSv1.1  256 bits  DHE-RSA-AES256-SHA 
     TLSv1.1  256 bits  DHE-RSA-CAMELLIA256-SHA
     **TLSv1.0  256 bits  ECDHE-RSA-AES256-SHA**
     **TLSv1.0  256 bits  DHE-RSA-AES256-SHA**

Please let me know, how to resolve this.

**Comment by venkyvxl** [comment]
@embedthis , @mobsense, any update on this issue?

**Comment by dev-embedthis** [comment]
Did you try to debug this --- the community server depends on users helping to debug issues. It isn't just free support. You need to help fix issues too. Your help is appreciated.
