### ISSUE TITLE
Return immediately when one route matches in conf file 

### ISSUE THREAD

**Issue by venkyvxl** [embedthis/appweb#640]
Environment:

O/S Version: Linux 3.16

Appweb Version: 7.1.0

Hardware: Proprietary

Problem description:
  I need to check for specific request headers availability before selecting specific route for request. So, my appweb.conf looks like

**Route < ^/>
    Condition ! match ${header:Accept} json
    Alias /doc/error_406.json
</Route>
Route < ^/test>
    Alias /test /doc/test.json
</Route>**

Here what is happening is, when a request "curl -vk -H 'Accept:xml'  -X GET 'https://100.101.19.97/test' "  arrives,  as accept header is not being  json, it goes to serve error_406.json file, but immediately as request is matching test route, it is serving the test.json file.
Pls let me know, how to stop processing further if one rule is matched..

**Comment by dev-embedthis** [comment]
The first route is not matching because the condition is not matching. Therefore the test route is the next matching route. The Alias is not a matching condition and will be used when the request matches a route.

Also, you need to close your route blocks

```
Route < ^/>
Condition ! match ${header:Accept} json
Alias /doc/error_406.json
</Route>

Route < ^/test>
Alias /test /doc/test.json
</Route>
```
