### ISSUE TITLE
define and check variables in appweb config file

### ISSUE THREAD

**Issue by venkyvxl** [embedthis/appweb#642]
Environment:

O/S Version: Linux 3.16

Appweb Version: 7.1.0

Hardware: Proprietary

Problem Description:
 I want to define some variables and depending upon value , set appropriate response headers. But it seems , appweb conf file doesn't support operation like value check and proceed. Please let me know, how to handle this.

Ex: Consider I have one variable REDIRECT and if REDIRECT = 1, add HSTS response header else not to add the same. 
I tried like "if  REDIRECT" module directive and also like "Condition match $REDIRECT 1" , but none of these checks the value as needed. 
PS: REDIRECT  is defined in another script and can have value 0 or 1..

**Comment by dev-embedthis** [comment]
One way is to have a route that matches on the conditions you want and then set headers inside that route only.
