### ISSUE TITLE
Account management problems

### ISSUE THREAD

**Issue by Bussy-yang** [embedthis/appweb#643]
Hi, I have a problem,
edi = espGetRouteDatabase(route);
password = mprMakePassword("demo", 16, 12);
rec = ediCreateRec(edi, "user");
ediSetFields(rec, ediMakeJson("{ username: 'test197', password: '%s', email: 'temp@test.com', roles: 'user' }", password));
ediUpdateRec(edi, rec);
I cannot create this account in MDB.

**Comment by dev-embedthis** [comment]
More details please. We can't do much with so little information. Please read how to submit an issue and include full description, error messages and details.

**Comment by Bussy-yang** [comment]
as the kickstart's  demo descrite:
static int forward(Edi *db) {
    EdiRec  *rec;
    cchar   *password;
    
    ediAddTable(db, "user");
    ediAddColumn(db, "user", "id", EDI_TYPE_INT, EDI_AUTO_INC | EDI_INDEX | EDI_KEY);
    ediAddColumn(db, "user", "username", EDI_TYPE_STRING, 0);
    ediAddColumn(db, "user", "password", EDI_TYPE_STRING, 0);
    ediAddColumn(db, "user", "email", EDI_TYPE_STRING, 0);
    ediAddColumn(db, "user", "roles", EDI_TYPE_STRING, 0);

    /*
        The mprMakePassword API uses Blowfish. This call requests 16 bytes of salt and iterates 128 rounds.
        Use mprCheckPassword to check.
     */
    password = mprMakePassword("demo", 16, 128);
    rec = ediCreateRec(db, "user");
    ediSetFields(rec, ediMakeJson("{ username: 'admin11', password: '%s', email: 'dev@embedthis.com', roles: 'administrator' }", password));
    ediUpdateRec(db, rec);

    password = mprMakePassword("demo", 16, 16);
    rec = ediCreateRec(db, "user");
    ediSetFields(rec, ediMakeJson("{ username: 'guest', password: '%s', email: 'guest@example.com', roles: 'user' }", password));
    ediUpdateRec(db, rec);
    return 0;
}

I also use the same method to insert new users,but the kickstart.mdb has no user infomation which I inserted. I want to konw, when I create a new user infomation to the database , what  should I do first.
