### ISSUE TITLE
Heap memory usage keeps increasing with heavy traffic

### ISSUE THREAD

**Issue by kyeongy** [embedthis/appweb#645]
### Environment

1. O/S Version: Linux 4.4.6

2. Appweb Version: 6.2.3

3. Hardware: PowerPC e500

### Build

1. If built from source, what was your configure command line:

```
make SHOW=1 ME_COMPILER_HAS_PAM=1 ME_MPR_OSLOG=1 ME_COM_DIR=1
```

### Problem Description:

I have experienced that on a busy device with a lot of http GET operations the heap memory usage of appweb keeps increasing due to most of the garbage collection attempts was not successful (99%). I can understand all threads need to yield before the garbage collector thread is perform GC successfully (in 100ms) in pauseThreads(), which is fine normally. And when all traffic stops, the memory is fully freed at the end.

But on extremely busy web server, there are chances that some worker threads are busy processing backend logic and cannot yield most times. As the probability of successful GC goes significantly down, the heap memory usage seems steadily growing.

I'm looking for a way of better GC to avoid excessive memory usage of long-running appweb.
Are there any suggested way to improve GC to happen more often (or regularly)?
Note that in a couple of months, appweb heap memory usage increases to more than 500MB.

I can think of:
* In pauseThreads(), use longer timeout (e.g. 100 times of the default timeout 100ms) if GC attempt fails consecutively for many times (e.g. 200)

Some stats output is following:
````
Http Report: at 07/15/19 21:08:26
Connections     8.969 per/sec
Requests        8.952 per/sec
Sweeps          0.227 per/sec
Clients             1 active
Connections        19 active
Processes           0 active
Requests            9 active
Sessions            0 active
Workers             5 busy - 0 yielded, 0 idle, 5 max
Sessions          0.0 MB (cache)
Memory Stats:
  Memory                  25.9 MB
  Heap                    14.5 MB
  Heap-peak               64.8 MB
  Heap-used                0.4 MB
  Heap-free               14.1 MB
  Heap cache               0.0 MB (0.00 %)
  Heap limit             200.0 MB
  Heap redline           170.0 MB
  Cache Heap               0.0 MB
  Low Heap                 0.2 MB
  Errors                     0
  CPU cores                  4

Allocator Stats:
  Memory requests     11107228
  Region allocs           0.01 % (1495)
  Region unpins           0.01 % (1437)
  Reuse                  99.99 %
  Joins                  99.62 % (11065259)
  Splits                 99.60 % (11063004)
  Q races                 2.53 % (280661)
  Q contention            0.40 % (89501 / 22499026)
  Alloc retries           0.00 % (118 / 11107228)
  GC collections          0.00 % (90)
  Compact next            0.00 % (168)
  MprMem size               16
  MprFreeMem size           24
````
And my private debug shows: Total GC attempts: 18107, skip=18017, sweep=90

**Comment by dev-embedthis** [comment]
How long are you blocking threads doing backend logic?

The design of the server assumes that all threads do not block and call mprYield whenever they do block or during long running computations.

**Comment by kyeongy** [comment]
I happened to miss a useful API : mprYield (MPR_YIELD_STICKY).
That helped.
Thanks
