### ISSUE TITLE
Appweb not handling larger payload with POST operation

### ISSUE THREAD

**Issue by venkyvxl** [embedthis/appweb#647]
Environment:

O/S Version: Linux 3.16

Appweb Version: 7.1.0

Hardware: Proprietary

Problem description:
   When I try to upload large payload data(>100KB)  via curl/RESTlet client, appweb is not reading complete data and not closing the connection too. While analyzing the code, I found that, in filterPacket() api, httpSetEof():16740 of httpLib.c is not getting called due to condition not met.  But the same works when I give the smaller payload. Pls let me know, how to resolve this issue.

**Comment by dev-embedthis** [comment]
Thanks. Can you post a little test case using python or similar?

Then we can try to reproduce.

**Comment by venkyvxl** [comment]
@dev-embedthis , 
It is a simple test case. Just ran POST on resource with payload of 100KB. 
Ex: curl -vk -i -X POST -H "Content-Type:application/json" -d @data.json 'https://ipaddress/resource'.

data.json file contains payload data. If length of this file is <40KB, its working fine. If length exceeds 40KB(right now I have a payload of 120KB), its failing and I see httpSetEof() not getting called at all.

**Comment by dev-embedthis** [comment]
This depends on your request handler and content type. Some content types are streaming, some are non-streaming (typically forms). See the "StreamInput [!] mimeType [uri]" directive in the doc.

So when you use application/json, it is non-streaming and thus buffers all the data. In contrast, streaming requests pass their data progressively to their handler.  Streaming handlers must consume their data progressively.

Now if you are non-streaming all the input must buffer.  Appweb has strict queue limits to manage memory footprint. If the readq has more data than the queue max, then more data will not be read until the handler consumes the data. But in this case, the entire form will buffer before the handler gets a look in.

If you set your LimitBuffer to be bigger than the max form, it should work.

**Comment by dev-embedthis** [comment]
Lastly, the file upload handler is much more efficient than plain POST/PUT for large files as it filters the file upload.

**Comment by venkyvxl** [comment]
@dev-embedthis , I have file upload handler and it is used for other purposes. But for POST/PUT op, I need to standard rx/tx queues which were working with 4.5.4 version. Now when I upgraded it to current latest stable version of 7.1.0, these test cases are failing with larger payload. This is my concern. 
By changing LimitBuffer to 256K from current config of 32K, its working fine.. Thanks a lot for your kind support and time.
But on curious note , Just want to know, 
1. how appweb 4.5.4 is working fine with LimtBuffer config of 32K for payload of 120K 
2. what should be ideal size of LimitBuffer Config even though sample.conf in github shows as 32K.
3. what are the implications of changing LimitBuffer to 256K and on any other config directives like LimitMemory , LimitCache , LimitChunk  etc

**Comment by dev-embedthis** [comment]
Unsure about 4.5 -- that is a long time ago that version.

Increasing LimitBuffer is just a workaround and not ideal. LimitBuffer applies to all queue stages, so your memory footprint may increase.

We will probably make a change to use LimitRequestForm for the queue head instead of LimitBuffer. That makes more sense.

**Comment by venkyvxl** [comment]
@dev-embedthis, thank you for your response.. Just to confirm again, we may expect more functionality getting added to LimitRequestForm directive in upcoming release, right?

**Comment by dev-embedthis** [comment]
Maybe, still gathering data.

What is your handler for the PUT?

Can you stream the content rather than treat like a buffered form?  Streaming is much more efficient.

**Comment by venkyvxl** [comment]
For streaming, we have handler and this being used for firmware upload/flash upload.. But for some generic operations get/import, we are depending upon appweb's queues for buffering  and transferring of the data ..

**Comment by dev-embedthis** [comment]
Yes, but what handler are you using?  Why do you need to treat the data like a form? Are you using Appweb routing on the contents?

All requests use appweb's queues and buffering. Please give more details, otherwise too hard to understand or help.

**Comment by venkyvxl** [comment]
@dev-embedthis , I am not clear what exactly you meant by "what handler are you using".. 
To give more info, We have one customized handler which reads complete payload data of application/json type data and then writes to file for further processing. 
Necessity for treating the data like a form is because, we have applications which parses payload data once it is completely read and written to file.
No, we are not using routing on contents, but used the same for URIs specifics.

**Comment by dev-embedthis** [comment]
Every appweb request is serviced by a handler. You are doing a PUT request, but what is the handler at the end of the input queue?  CGI, File, ESP, PHP, Custom?
