### ISSUE TITLE
backup ErrorLog bug Report

### ISSUE THREAD

**Issue by Jeff-Kook** [embedthis/appweb#650]
I'm using older mpr module. It seems I found a bug.  
When my log data is too big and need to backup the log file. My program is broke down. 
I found the bug can be fix by change 

in File mpr/mprLib.c
https://github.com/embedthis/appweb/blob/master/src/mpr/mprLib.c#L16179

change
```
if ((file = MPR->logFile) == 0 || msg == 0 || *msg == '\0') {
	return;
}
if (MPR->logBackup && MPR->logSize && (check++ % 1000) == 0) {
	backupLog();
}
```
to
```
if (MPR->logBackup && MPR->logSize && (check++ % 1000) == 0) {
	backupLog();
}
if ((file = MPR->logFile) == 0 || msg == 0 || *msg == '\0') {
	return;
}
```

so that the next function `mprWriteFileString(file, tbuf);` can work normally.

**Comment by dev-embedthis** [comment]
Can you describe the issue you are trying to fix? You say it broke?  But how?

The test for MPR->logFile must be first because you should not be doing a backup if there is no log file opened.

**Comment by Jeff-Kook** [comment]
> Can you describe the issue you are trying to fix? You say it broke? But how?
> 
> The test for MPR->logFile must be first because you should not be doing a backup if there is no log file opened.

Before change.
 `file = MPR->logFile`, after functon `backupLog()`.  `MPR->logFile` is new value, but `file` is old and it is closed in `backupLog`.  So `mprWriteFileString(file, tbuf);` will be broken.

**Comment by dev-embedthis** [comment]
Okay, thank you. Understand.
