### ISSUE TITLE
How to implement the reverse proxy for websocket requests

### ISSUE THREAD

**Issue by TestUser641** [embedthis/appweb#659]
Is there a support by appweb to reverse proxy the websocket requests?
I was going through the documentation and found there is support for both reverse proxy as well as websockets.
But I'm looking to reverse proxy the websocket requests to my backend server, if its possible can you provide a sample route for appweb.conf?

Is something like this possible?
  ```
<Route ^/abc$>
    Reset                   pipeline
    AddFilter               webSocketFilter
    SetHandler              <proxyHandler>
    ProxyConnect            <ip:port> http1 multiplex=20
    LimitWebSockets         15
    LimitWebSocketsMessage  10MB
    LimitWebSocketsPacket   200K
    LimitWebSocketsFrame    4K
    WebSocketsPing          1min
    Methods set GET POST PUT PATCH DELETE
    ProxyLog proxy.log level=4 formatter=pretty anew
    ProxyTrace debug=1 error=1 request=2 result=2 headers=3 context=4 packet=5 dd
etail=6 content=10K
  </Route>
```

**Comment by TestUser641** [comment]
Could I please have any update on this?

**Comment by mobsense** [comment]
Yes, websockets over proxy is supported.

However, you don't want the web socket filter in the front facing appweb. It does not terminate the web socket connection. You just want that routed to the proxy. Your backend app then handles the web sockets. The proxy routes everything to the backend.

Sorry we don't provide free support here. Contact sales@embedthis.com to setup support.

**Comment by TestUser641** [comment]
Ok thanks
