### ISSUE TITLE
appweb worker thread blocking

### ISSUE THREAD

**Issue by farhanz** [embedthis/appweb#661]
1.	We have a product that supports a command line HTTP interface as well as GUI.
2.	The command line HTTP interface is implemented as a custom handler.
a.	The handler has some blocking calls.
3.	The GUI functionality is implemented as a filter.
4.	If the appweb handler worker thread is blocked on I/O, the GUI functionality becomes sluggish.
5.	This is due to appweb’s design where in it reuses the same threads and does not assign a thread per request.
6.	Is there a way to get appweb to use additional worker threads if certain worker threads are blocked?
7.	Our current configuration specifies MinWorkers 2 and LimitWorkers 8.
8.	We tried changing this config to MinWorkers 8 and LimitWorkers 14 but that hasn’t helped.

**Comment by mobsense** [comment]
The httpCreateEvent mentioned in the page still exists and is fully supported.

Also, mprYield(MPR_YIELD_STICKY) does not return a thread to the thread pool. It pauses a thread while GC runs and marks the current thread as being thread-safe with respect to the GC.
