### ISSUE TITLE
Appweb sockets staying in CLOSE_WAIT state

### ISSUE THREAD

**Issue by venkyvxl** [embedthis/appweb#664]
### Environment

1. O/S Version: Linux

2. Appweb Version: 7.1.0

3. Hardware: Embedded system

1. If built from source, what was your configure command line:

### Problem Description:

We are seeing an issue in appweb 7.1.0, when custom handler is processing the specific request type. 
During this processing, if another simple GUI request is made, connections are going into CLOSE_WAIT state and wont come out of this state till custom handler finishes the request.
Please help me in resolving the issue.

Below is the snippet:
tcp      518      0 ::ffff:{IP}:443  ::ffff:{IP}:63493 CLOSE_WAIT  6408/appweb
tcp       32      0 ::ffff:{IP}:443  ::ffff:{IP}:39736 CLOSE_WAIT  6408/appweb
tcp        1      0 ::ffff:{IP}:80     ::ffff:{IP}:33248  CLOSE_WAIT  6408/appweb
tcp       32      0 ::ffff:{IP}:443  ::ffff:{IP}:39724 CLOSE_WAIT  6408/appweb
tcp      518      0 ::ffff:{IP}:443  ::ffff:{IP}:63492 CLOSE_WAIT  6408/appweb
tcp        1      0 ::ffff:{IP}:80     ::ffff:{IP}:33255  CLOSE_WAIT  6408/appweb
tcp        0      0 ::ffff:{IP}:443  ::ffff:{IP}:39740 ESTABLISHED 6408/appweb
tcp       32      0 ::ffff:{IP}:443  ::ffff:{IP}:39738 CLOSE_WAIT  6408/appweb

**Comment by mobsense** [comment]
CLOSE_WAIT indicates that the server has received the first FIN signal from the client and the connection is in the process of being closed.

They will stay in close wait until you close the connection from your end.
